#ifndef ZM_INLINE_FUNCTIONS_IMPL_HPP
#define ZM_INLINE_FUNCTIONS_IMPL_HPP

//--------------------------------------------------------------------------------------------------

KOKKOS_INLINE_FUNCTION
static Real goffgratch_svp_water(
  // Inputs
  const Real& t)    // Temperature                  [K]
{
  // GoffGratch_svp_water
  static constexpr Real magic1 = -7.90298;
  static constexpr Real magic2 = 5.02808;
  static constexpr Real magic3 = 1.3816e-7;
  static constexpr Real magic4 = 11.344;
  static constexpr Real magic5 = 8.1328e-3;
  static constexpr Real magic6 = -3.49149;
  static constexpr Real magic7 = 1013.246;
  return Kokkos::pow(10, magic1*(ZMC::tboil/t-1) +
                  magic2*Kokkos::log10(ZMC::tboil/t) -
                  magic3*(Kokkos::pow(10, magic4*(1 - t/ZMC::tboil)) - 1) +
                  magic5*(Kokkos::pow(10, magic6*(ZMC::tboil/t-1)) - 1) +
                  Kokkos::log10(magic7))*100;
}

//--------------------------------------------------------------------------------------------------

KOKKOS_INLINE_FUNCTION
static Real goffgratch_svp_ice(
  // Inputs
  const Real& t)    // Temperature                  [K]
{
  // good down to -100 C
  static constexpr Real magic1 = -9.09718;
  static constexpr Real magic2 = 3.56654;
  static constexpr Real magic3 = 0.876793;
  static constexpr Real magic4 = 6.1071;

  return Kokkos::pow(10, magic1*(ZMC::h2otrip/t - 1) -
                  magic2*Kokkos::log10(ZMC::h2otrip/t) +
                  magic3*(1 - t/ZMC::h2otrip) +
                  Kokkos::log10(magic4))*100;
}

//--------------------------------------------------------------------------------------------------

KOKKOS_INLINE_FUNCTION
static Real svp_trans(
  // Inputs
  const Real& t)    // Temperature                  [K]
{
  Real es;

  //
  // Water
  //
  if (t >= (PC::Tmelt.value - ZMC::ttrice)) {
    es = goffgratch_svp_water(t);
  }
  else {
    es = 0;
  }

  //
  // Ice
  //
  if (t < PC::Tmelt.value) {

    const Real esice = goffgratch_svp_ice(t);

    Real weight;
    if ( (PC::Tmelt.value - t) > ZMC::ttrice ) {
      weight = 1;
    }
    else {
      weight = (PC::Tmelt.value - t)/ZMC::ttrice;
    }

    es = weight*esice + (1 - weight)*es;
  }
  return es;
}

//--------------------------------------------------------------------------------------------------

KOKKOS_INLINE_FUNCTION
static void qsat_hPa(
  // Inputs
  const Real& t,    // Temperature                  [K]
  const Real& p,    // Pressure                     [hPa]
  // Outputs
  Real& es,         // Saturation vapor pressure    [hPa]
  Real& qm)         // Saturation mass mixing ratio [kg/kg] (vapor mass over dry mass)
{
  es = goffgratch_svp_water(t);

  // If pressure is less than SVP, set qs to maximum of 1.
  if ( (p*100 - es) <= 0 ) {
    qm = 1;
  }
  else {
    qm = PC::ep_2.value*es / (p*100 - ZMC::omeps*es);
  }

  // Ensures returned es is consistent with limiters on qs.
  es = Kokkos::min(es, p*100);

  es = es*0.01;
}

//--------------------------------------------------------------------------------------------------

KOKKOS_INLINE_FUNCTION
static void qsat(
  // Inputs
  const Real& t,    // Temperature                  [K]
  const Real& p,    // Pressure                     [Pa]
  const ZmRuntimeOpt& runtime_opt,
  // Outputs
  Real& es,         // Saturation vapor pressure    [Pa]
  Real& qs)         // Saturation mass mixing ratio [kg/kg] (vapor mass over dry mass)
{
  constexpr Real mmin = 0.0;
  constexpr Real tmin = ZMC::tmin;
  constexpr Real tmax = ZMC::tmax;
  const Real t_tmp = Kokkos::max(Kokkos::min(t, tmax) - tmin, mmin);     // Number of table entries above tmin
  const Int i = int(t_tmp);                        // Corresponding index.
  const Real weight = t_tmp - Kokkos::trunc(t_tmp);// Fractional part of t_tmp (for interpolation).
  es = (1 - weight)*runtime_opt.estbl(i) + weight*runtime_opt.estbl(i+1);

  // If pressure is less than SVP, set qs to maximum of 1.
  if ( (p - es) < 0 ) {
    qs = 1;
  }
  else {
    qs = PC::ep_2.value*es / (p - ZMC::omeps*es);
  }

  // Ensures returned es is consistent with limiters on qs.
  es = Kokkos::min(es, p);
}

//--------------------------------------------------------------------------------------------------

KOKKOS_INLINE_FUNCTION
static bool is_conv_active(
  // Inputs
  const ZmRuntimeOpt& runtime_opt,
  const bool& is_first_step,       // flag for first step of run
  const Real& cape,                // conv. avail. potential energy     [J/kg]
  const Real& dcape,               // CAPE generated by dycor (dCAPE)   [J/kg/s]
  // Outputs
  Real& cape_threshold_loc)        // cape threshold
{
  // set local threshold to be used for zm_closure()
  if ( runtime_opt.trig_dcape && !is_first_step ) {
    cape_threshold_loc = ZMC::cape_threshold_new;
  }
  else {
    cape_threshold_loc = ZMC::cape_threshold_old;
  }

  //--------------------------------------------------------------------------
  // determine if column is active
  if ( runtime_opt.trig_dcape && ! is_first_step ) {
    if ( cape > cape_threshold_loc && dcape > ZMC::dcape_threshold ) {
      return true;
    }
  }
  else {
    if (cape > cape_threshold_loc) {
      return true;
    }
  }

  return false;
}

//--------------------------------------------------------------------------------------------------

#endif