#ifndef ZM_ZM_CONV_MAIN_IMPL_HPP
#define ZM_ZM_CONV_MAIN_IMPL_HPP

#include "zm_functions.hpp" // for ETI only but harmless for GPU

namespace scream {
namespace zm {

/*
 * Implementation of zm zm_conv_main. Clients should NOT
 * #include this file, but include zm_functions.hpp instead.
 */

template<typename S, typename D>
KOKKOS_FUNCTION
void Functions<S,D>::zm_conv_main(
  // Inputs
  const MemberType& team,
  const Int& pver, // number of mid-point levels
  const Int& pverp, // number of interface levels
  const bool& is_first_step, // flag for first step of run
  const Real& time_step, // model time-step                         [s]
  const uview_1d<const Real>& t_mid, // temperature                             [K]
  const uview_1d<const Real>& q_mid_in, // specific humidity                       [kg/kg]
  const uview_1d<const Real>& omega, // vertical pressure velocity              [Pa/s]
  const uview_1d<const Real>& p_mid_in, // mid-point pressure                      [Pa]
  const uview_1d<const Real>& p_int_in, // interface pressure                      [Pa]
  const uview_1d<const Real>& p_del_in, // pressure thickness                      [Pa]
  const Real& geos, // surface geopotential                    [m2/s2]
  const uview_1d<const Real>& z_mid_in, // mid-point geopotential                  [m2/s2]
  const uview_1d<const Real>& z_int_in, // interface geopotential                  [m2/s2]
  const Real& pbl_hgt, // boundary layer height                   [m]
  const Real& tpert, // parcel temperature perturbation         [K]
  const Real& landfrac, // land fraction                           []
  const uview_1d<const Real>& t_star, // for DCAPE - prev temperature            [K]
  const uview_1d<const Real>& q_star, // for DCAPE - prev sp. humidity           [kg/kg]
  // Outputs
  Int& lengath, // number of active columns in chunk for gathering
  Int& gather_index, // flag for active columns
  Int& msemax_klev_g, // gathered level indices of max MSE (msemax_klev)
  Int& jctop, // top-of-deep-convection indices
  Int& jcbot, // base of cloud indices
  Int& jt, // gathered top level index of convection
  Real& prec, // output precipitation                    [m/s]
  const uview_1d<Real>& heat, // dry energy tendency              [W/kg]
  const uview_1d<Real>& qtnd, // specific humidity tendency              [kg/kg/s]
  Real& cape, // conv. avail. potential energy           [J]
  Real& dcape, // CAPE generated by dycor (dCAPE)         [J]
  const uview_1d<Real>& mcon, // convective mass flux                    [mb/s]
  const uview_1d<Real>& pflx, // precip flux at each level               [kg/m2/s]
  const uview_1d<Real>& zdu, // detraining mass flux                    [1/s]
  const uview_1d<Real>& mflx_up, // updraft mass flux                       [mb/s]
  const uview_1d<Real>& entr_up, // updraft entrainment                     [1/s]
  const uview_1d<Real>& detr_up, // updraft detrainment                     [1/s]
  const uview_1d<Real>& mflx_dn, // downdraft mass flux                     [mb/s]
  const uview_1d<Real>& entr_dn, // downdraft entrainment                   [1/s]
  const uview_1d<Real>& p_del, // layer thickness                         [mb]
  Real& dsubcld, // thickness between lcl and msemax_klev   [mb]
  const uview_1d<Real>& ql, // cloud liquid water for chem/wetdep      [?]
  Real& rliq, // reserved liquid (not yet in cldliq) for energy integrals
  const uview_1d<Real>& rprd, // rain production rate                    [kg/kg/s]
  const uview_1d<Real>& dlf) // detrainment rate of cloud liquid water  [kg/kg/s])
{
  // TODO
  // Note, argument types may need tweaking. Generator is not always able to tell what needs to be packed
}

} // namespace zm
} // namespace scream

#endif
