#ifndef ZM_ZM_CONV_MAIN_IMPL_HPP
#define ZM_ZM_CONV_MAIN_IMPL_HPP

#include "zm_functions.hpp" // for ETI only but harmless for GPU

namespace scream {
namespace zm {

/*
 * Implementation of zm zm_conv_main. Clients should NOT
 * #include this file, but include zm_functions.hpp instead.
 */

template<typename S, typename D>
KOKKOS_FUNCTION
bool Functions<S,D>::zm_conv_main(
  // Inputs
  const MemberType& team,
  const Workspace& workspace,
  const ZmRuntimeOpt& runtime_opt,
  const Int& pver, // number of mid-point levels
  const Int& pverp, // number of interface levels
  const bool& is_first_step, // flag for first step of run
  const Real& time_step, // model time-step                         [s]
  const uview_1d<const Real>& t_mid, // temperature                             [K]
  const uview_1d<const Real>& q_mid_in, // specific humidity                       [kg/kg]
  const uview_1d<const Real>& omega, // vertical pressure velocity              [Pa/s]
  const uview_1d<const Real>& p_mid_in, // mid-point pressure                      [Pa]
  const uview_1d<const Real>& p_int_in, // interface pressure                      [Pa]
  const uview_1d<const Real>& p_del_in, // pressure thickness                      [Pa]
  const Real& geos, // surface geopotential                    [m2/s2]
  const uview_1d<const Real>& z_mid_in, // mid-point geopotential                  [m]
  const uview_1d<const Real>& z_int_in, // interface geopotential                  [m]
  const Real& pbl_hgt, // boundary layer height                   [m]
  const Real& tpert, // parcel temperature perturbation         [K]
  const Real& landfrac, // land fraction                           []
  const uview_1d<const Real>& t_star, // for DCAPE - prev temperature            [K]
  const uview_1d<const Real>& q_star, // for DCAPE - prev sp. humidity           [kg/kg]
  // Outputs
  Int& msemax_klev, // indx of max MSE
  Int& jctop, // top-of-deep-convection indices
  Int& jcbot, // base of cloud indices
  Int& jt, // gathered top level index of convection
  Real& prec, // output precipitation                    [m/s]
  const uview_1d<Real>& heat, // dry static energy tendency              [W/kg]
  const uview_1d<Real>& qtnd, // specific humidity tendency              [kg/kg/s]
  Real& cape, // conv. avail. potential energy           [J]
  Real& dcape, // CAPE generated by dycor (dCAPE)         [J]
  const uview_1d<Real>& mcon, // convective mass flux                    [mb/s]
  const uview_1d<Real>& pflx, // precip flux at each level               [kg/m2/s]
  const uview_1d<Real>& zdu, // detraining mass flux                    [1/s]
  const uview_1d<Real>& mflx_up, // updraft mass flux                       [mb/s]
  const uview_1d<Real>& entr_up, // updraft entrainment                     [1/s]
  const uview_1d<Real>& detr_up, // updraft detrainment                     [1/s]
  const uview_1d<Real>& mflx_dn, // downdraft mass flux                     [mb/s]
  const uview_1d<Real>& entr_dn, // downdraft entrainment                   [1/s]
  const uview_1d<Real>& p_del, // layer thickness                         [mb]
  Real& dsubcld, // thickness between lcl and msemax_klev   [mb]
  const uview_1d<Real>& ql, // cloud liquid water for chem/wetdep      [?]
  Real& rliq, // reserved liquid (not yet in cldliq) for energy integrals
  const uview_1d<Real>& rprd, // rain production rate                    [kg/kg/s]
  const uview_1d<Real>& dlf) // detrainment rate of cloud liquid water  [kg/kg/s])
{
  //----------------------------------------------------------------------------
  // Purpose: Main driver for Zhang-McFarlane convection scheme
  //----------------------------------------------------------------------------

  constexpr Real gravit = PC::gravit.value;
  constexpr Real cpair  = PC::Cpair.value;

  //----------------------------------------------------------------------------
  // Set upper limit of convection to "limcnv-1"
  const Int msg = runtime_opt.limcnv - 1;

  //----------------------------------------------------------------------------
  // Allocate workspace arrays
  uview_1d<Real> s_mid, q_mid, p_mid, z_mid, s_int, q_int,
                 t_pcl, q_pcl_sat, t_pcl_m1, q_pcl_sat_m1,
                 dqdt, dsdt, mflx_net, q_upd, s_upd,
    q_dnd, s_dnd, qst, cu, evp, dl, p_int, z_int;
  workspace.template take_many_contiguous_unsafe<23>(
    {"s_mid", "q_mid", "p_mid", "z_mid", "s_int", "q_int",
     "t_pcl", "q_pcl_sat", "t_pcl_m1", "q_pcl_sat_m1",
     "dqdt", "dsdt", "mflx_net", "q_upd", "s_upd",
     "q_dnd", "s_dnd", "qst", "cu", "evp", "dl", "p_int", "z_int"},
    {&s_mid, &q_mid, &p_mid, &z_mid, &s_int, &q_int,
     &t_pcl, &q_pcl_sat, &t_pcl_m1, &q_pcl_sat_m1,
     &dqdt, &dsdt, &mflx_net, &q_upd, &s_upd,
     &q_dnd, &s_dnd, &qst, &cu, &evp, &dl, &p_int, &z_int});

  //----------------------------------------------------------------------------
  // Scalar local variables
  Real z_srf = 0;
  Int  pbl_top = pver - 1;
  Int  lcl = 0, lel = pver - 1;
  Int  lcl_m1 = 0, lel_m1 = pver - 1, msemax_klev_m1 = 0;
  Real cape_m1 = 0, t_pcl_lcl = 400, t_pcl_lcl_m1 = 400;
  Real cld_base_mass_flux = 0, mflx_up_max_val = 0;
  Int  jlcl = 0, j0 = 0, jd = 0;
  Real q_mx = 0, t_mx = 0, q_mx_m1 = 0, t_mx_m1 = 0;
  Real cape_threshold_loc = ZMC::cape_threshold_old;

  //----------------------------------------------------------------------------
  // Initialize output arrays
  Kokkos::parallel_for(Kokkos::TeamVectorRange(team, pver), [&] (const Int& k) {
    heat(k)    = 0;
    qtnd(k)    = 0;
    mcon(k)    = 0;
    pflx(k)    = 0;
    rprd(k)    = 0;
    zdu(k)     = 0;
    ql(k)      = 0;
    dlf(k)     = 0;
    p_del(k)   = 0;
    mflx_up(k) = 0;
    entr_up(k) = 0;
    detr_up(k) = 0;
    mflx_dn(k) = 0;
    entr_dn(k) = 0;
  });
  Kokkos::single(Kokkos::PerTeam(team), [&] () {
    prec       = 0;
    rliq       = 0;
    dsubcld    = 0;
    jctop      = pver - 1;
    jcbot      = 0;
    cape       = 0;
    dcape      = 0;
    msemax_klev = 0;
    // initialize pflx at the last interface (pver index in 0-based, pverp-1)
    pflx(pver) = 0;
  });
  team.team_barrier();

  // Calculate local pressure [mb] and height [m] for both interface and mid-point
  Kokkos::single(Kokkos::PerTeam(team), [&] () {
    z_srf = geos / gravit;
  });
  team.team_barrier();

  Kokkos::parallel_for(Kokkos::TeamVectorRange(team, pver), [&] (const Int& k) {
    p_mid(k) = p_mid_in(k) * 0.01;
    z_mid(k) = z_mid_in(k) + z_srf;
    p_int(k) = p_int_in(k) * 0.01;
    z_int(k) = z_int_in(k) + z_srf;
    if (k == pver-1) {
      p_int(k+1) = p_int_in(k+1) * 0.01;
      z_int(k+1) = z_int_in(k+1) + z_srf;
    }
  });
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Locate PBL top index: find the topmost level (min k) where z_mid is
  // within half a layer thickness of pbl_hgt.
  Int pbl_top_result = pver - 1;
  Kokkos::parallel_reduce(Kokkos::TeamVectorRange(team, msg + 1, pver - 1),
    [&] (const Int& k, Int& val) {
      if (std::abs(z_mid(k) - pbl_hgt) < (z_int(k) - z_int(k + 1)) * 0.5) {
        val = ekat::impl::min(val, k);
      }
    },
    Kokkos::Min<Int>(pbl_top_result));
  team.team_barrier();
  // Min reducer uses max-int as identity; clamp to default if nothing satisfied
  pbl_top = ekat::impl::min(pbl_top_result, pbl_top);

  //----------------------------------------------------------------------------
  // Store input specific humidity for precip calculation
  // Define dry static energy normalized by cp
  // Initialize interface values to mid-point values (updated for active columns later)
  Kokkos::parallel_for(Kokkos::TeamVectorRange(team, pver), [&] (const Int& k) {
    q_mid(k)  = q_mid_in(k);
    s_mid(k)  = t_mid(k) + (gravit / cpair) * z_mid(k);
    t_pcl(k)  = 0;
    s_int(k)  = s_mid(k);
    q_int(k)  = q_mid(k);
  });
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Evaluate Tparcel, qs(Tparcel), buoyancy, CAPE, lcl, lel, parcel launch level
  // - call #1, calc_msemax_klev=true: standard calculation using current step state
  compute_dilute_cape(team, workspace, runtime_opt,
                      pver, pverp,
                      runtime_opt.num_cin, msg,
                      q_mid, t_mid, z_mid, p_mid, p_int,
                      pbl_top, tpert,
                      true,  // calc_msemax_klev
                      0,     // prev_msemax_klev (unused for first call)
                      false, // use_input_tq_mx
                      q_pcl_sat, msemax_klev, lcl, lel, cape,
                      q_mx, t_mx,
                      t_pcl, t_pcl_lcl);
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Calculate DCAPE trigger condition
  // - call #2, calc_msemax_klev=false: use launch level from previous call
  if (!is_first_step && runtime_opt.trig_dcape) {
    const Int prev_msemax_klev_val = msemax_klev;
    compute_dilute_cape(team, workspace, runtime_opt,
                        pver, pverp,
                        runtime_opt.num_cin, msg,
                        q_star, t_star, z_mid, p_mid, p_int,
                        pbl_top, tpert,
                        false, // calc_msemax_klev
                        prev_msemax_klev_val,
                        false, // use_input_tq_mx
                        q_pcl_sat_m1, msemax_klev_m1, lcl_m1, lel_m1, cape_m1,
                        q_mx_m1, t_mx_m1,
                        t_pcl_m1, t_pcl_lcl_m1);
    team.team_barrier();
    Kokkos::single(Kokkos::PerTeam(team), [&] () {
      dcape = (cape - cape_m1) / time_step;
    });
    team.team_barrier();
  }

  //----------------------------------------------------------------------------
  // Determine whether column is active (replaces zm_get_gather_index)
  const bool active = is_conv_active(runtime_opt, is_first_step, cape, dcape, cape_threshold_loc);
  team.team_barrier();

  if (!active) {
    // Column is inactive: outputs remain at zero (already initialized above)
    workspace.template release_many_contiguous<23>(
      {&s_mid, &q_mid, &p_mid, &z_mid, &s_int, &q_int,
       &t_pcl, &q_pcl_sat, &t_pcl_m1, &q_pcl_sat_m1,
       &dqdt, &dsdt, &mflx_net, &q_upd, &s_upd,
       &q_dnd, &s_dnd, &qst, &cu, &evp, &dl, &p_int, &z_int});
    return false;
  }

  //----------------------------------------------------------------------------
  // Convert p_del to mb (gathered layer thickness)
  Kokkos::parallel_for(Kokkos::TeamVectorRange(team, pver), [&] (const Int& k) {
    p_del(k) = p_del_in(k) * 0.01;
  });
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Calculate sub-cloud layer pressure "thickness" for closure and tendency calculations
  Kokkos::parallel_reduce(Kokkos::TeamVectorRange(team, msemax_klev, pver),
    [&] (const Int& k, Real& sum) { sum += p_del(k); }, dsubcld);
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Define interfacial values of (s, q) used in subsequent routines
  Kokkos::parallel_for(Kokkos::TeamVectorRange(team, msg + 1, pver), [&] (const Int& k) {
    Real sdifr = 0, qdifr = 0;
    if (s_mid(k) > 0 || s_mid(k - 1) > 0) {
      sdifr = std::abs((s_mid(k) - s_mid(k - 1)) /
                       ekat::impl::max(s_mid(k - 1), s_mid(k)));
    }
    if (q_mid(k) > 0 || q_mid(k - 1) > 0) {
      qdifr = std::abs((q_mid(k) - q_mid(k - 1)) /
                       ekat::impl::max(q_mid(k - 1), q_mid(k)));
    }
    if (sdifr > ZMC::interp_diff_min) {
      s_int(k) = std::log(s_mid(k - 1) / s_mid(k)) *
                 s_mid(k - 1) * s_mid(k) / (s_mid(k - 1) - s_mid(k));
    } else {
      s_int(k) = 0.5 * (s_mid(k) + s_mid(k - 1));
    }
    if (qdifr > ZMC::interp_diff_min) {
      q_int(k) = std::log(q_mid(k - 1) / q_mid(k)) *
                 q_mid(k - 1) * q_mid(k) / (q_mid(k - 1) - q_mid(k));
    } else {
      q_int(k) = 0.5 * (q_mid(k) + q_mid(k - 1));
    }
  });
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Calculate updraft and downdraft properties
  zm_cloud_properties(team, workspace, runtime_opt,
                      pver, pverp, msg, runtime_opt.limcnv,
                      p_mid, z_mid, z_int,
                      t_mid, s_mid, s_int, q_mid,
                      landfrac, tpert,
                      msemax_klev, lel,
                      // Outputs:
                      jt, jlcl, j0, jd,
                      mflx_up, entr_up, detr_up, mflx_dn, entr_dn, mflx_net,
                      s_upd, q_upd, ql, s_dnd, q_dnd,
                      qst, cu, evp, pflx, rprd);
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Convert from units of "per length" [1/m] to "per pressure" [1/mb]
  Kokkos::parallel_for(Kokkos::TeamVectorRange(team, msg + 1, pver), [&] (const Int& k) {
    const Real dz = z_int(k) - z_int(k + 1);
    detr_up(k) = detr_up(k) * dz / p_del(k);
    entr_up(k) = entr_up(k) * dz / p_del(k);
    entr_dn(k) = entr_dn(k) * dz / p_del(k);
    cu(k)      = cu(k)      * dz / p_del(k);
    rprd(k)    = rprd(k)    * dz / p_del(k);
    evp(k)     = evp(k)     * dz / p_del(k);
  });
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Apply closure assumption to calculate cloud base mass flux
  zm_closure(team, workspace, runtime_opt,
             pver, pverp, msg, cape_threshold_loc,
             lcl, lel, jt, msemax_klev, dsubcld,
             z_mid, z_int,
             p_mid, p_del, t_mid,
             s_mid, q_mid, qst, ql, s_int, q_int,
             t_pcl_lcl, t_pcl, q_pcl_sat,
             s_upd, q_upd,
             mflx_net, detr_up, mflx_up, mflx_dn, q_dnd, s_dnd,
             cape,
             cld_base_mass_flux);
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Limit cloud base mass flux to theoretical upper bound
  Kokkos::parallel_reduce(Kokkos::TeamVectorRange(team, msg + 1, pver),
    [&] (const Int& k, Real& local_max) {
      local_max = ekat::impl::max(local_max, mflx_up(k) / p_del(k));
    },
    Kokkos::Max<Real>(mflx_up_max_val));
  team.team_barrier();

  Kokkos::single(Kokkos::PerTeam(team), [&] () {
    if (mflx_up_max_val > 0) {
      cld_base_mass_flux = ekat::impl::min(cld_base_mass_flux,
                                           1 / (time_step * mflx_up_max_val));
    } else {
      cld_base_mass_flux = 0;
    }
    if (runtime_opt.clos_dyn_adj) {
      cld_base_mass_flux = ekat::impl::max(
        cld_base_mass_flux - omega(pbl_top) * 0.01, Real(0));
    }
  });
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Don't allow convection within PBL (suggestion of Bjorn Stevens, 8-2000)
  if (runtime_opt.no_deep_pbl) {
    Kokkos::single(Kokkos::PerTeam(team), [&] () {
      if (z_mid_in(jt) < pbl_hgt) {
        cld_base_mass_flux = 0;
      }
    });
    team.team_barrier();
  }

  //----------------------------------------------------------------------------
  // Apply cloud base mass flux scaling to all relevant arrays
  Kokkos::parallel_for(Kokkos::TeamVectorRange(team, msg + 1, pver), [&] (const Int& k) {
    mflx_up(k)  *= cld_base_mass_flux;
    mflx_dn(k)  *= cld_base_mass_flux;
    mflx_net(k) *= cld_base_mass_flux;
    detr_up(k)  *= cld_base_mass_flux;
    entr_up(k)  *= cld_base_mass_flux;
    entr_dn(k)  *= cld_base_mass_flux;
    rprd(k)     *= cld_base_mass_flux;
    cu(k)       *= cld_base_mass_flux;
    evp(k)      *= cld_base_mass_flux;
    // pflx is indexed at k+1; scaling for k+1 index (surface pressure flux)
    pflx(k + 1) *= cld_base_mass_flux * 100 / gravit;
  });
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Compute temperature and moisture changes due to convection
  int ktm=jt, ktb=msemax_klev; // TODO fix
  zm_calc_output_tend(team,
                      pver, pverp, msg,
                      jt, msemax_klev, ktm, ktb, dsubcld,
                      p_del,
                      s_int, q_int, s_upd, q_upd,
                      mflx_up, detr_up, mflx_dn, s_dnd, q_dnd,
                      ql, evp, cu,
                      dsdt, dqdt, dl);
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Scatter data (trivial for single column: gather_index = 0)
  Kokkos::parallel_for(Kokkos::TeamVectorRange(team, msg + 1, pver), [&] (const Int& k) {
    // q_mid is updated to compute net precip via change in storage
    q_mid(k) = q_mid_in(k) + time_step * dqdt(k);
    qtnd(k)  = dqdt(k);
    // rprd, pflx, ql are already function output arrays (set by zm_cloud_properties + scaled)
    zdu(k)   = detr_up(k);
    mcon(k)  = mflx_net(k);
    heat(k)  = dsdt(k) * cpair;
    dlf(k)   = dl(k);
  });
  team.team_barrier();

  // Scatter scalar outputs
  Kokkos::single(Kokkos::PerTeam(team), [&] () {
    jctop = jt;
    jcbot = msemax_klev;
    // pflx(pver) is already set by the scale step above
  });
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Compute precip by integrating change in water vapor minus detrained cloud water
  Real prec_sum = 0;
  Kokkos::parallel_reduce(Kokkos::TeamVectorRange(team, msg + 1, pver),
    [&] (const Int& k, Real& local_sum) {
      const Real local = p_del_in(k) * (q_mid(k) - q_mid_in(k)) - p_del_in(k) * dlf(k) * time_step;
      local_sum -= local;
    }, prec_sum);
  team.team_barrier();

  // Obtain final precipitation rate in m/s
  Kokkos::single(Kokkos::PerTeam(team), [&] () {
    prec = (1 / gravit) * ekat::impl::max(prec_sum, Real(0)) / time_step / 1000;
  });
  team.team_barrier();

  //----------------------------------------------------------------------------
  // Compute reserved liquid (and ice) not yet in cldliq for energy integrals
  // Treat rliq as flux out bottom, to be added back later
  Real rliq_sum = 0;
  Kokkos::parallel_reduce(Kokkos::TeamVectorRange(team, pver),
    [&] (const Int& k, Real& local_sum) {
      local_sum += dlf(k) * p_del_in(k) / gravit;
    }, rliq_sum);
  team.team_barrier();

  Kokkos::single(Kokkos::PerTeam(team), [&] () {
    rliq = rliq_sum / 1000;
  });
  team.team_barrier();

  workspace.template release_many_contiguous<23>(
    {&s_mid, &q_mid, &p_mid, &z_mid, &s_int, &q_int,
     &t_pcl, &q_pcl_sat, &t_pcl_m1, &q_pcl_sat_m1,
     &dqdt, &dsdt, &mflx_net, &q_upd, &s_upd,
     &q_dnd, &s_dnd, &qst, &cu, &evp, &dl, &p_int, &z_int});

  return true;
}

} // namespace zm
} // namespace scream

#endif
