#!/usr/bin/env python3

import os
import sys

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")

_LIBDIR = os.path.join(_CIMEROOT, "CIME", "Tools")
sys.path.append(_LIBDIR)

from CIME.buildlib import parse_input
from CIME.case import Case
from standard_script_setup import *

logger = logging.getLogger(__name__)  # noqa: F405


def buildlib(bldroot, installpath, case):
    """
    """
    print("building omega")

    cmake_args = ""

    cmake_args += " -DOMEGA_BUILD_MODE=E3SM"

    print(f"omega cmake options: '{cmake_args}'")

    return cmake_args


def _main(argv, documentation):
    """
    """
    caseroot, libroot, bldroot = parse_input(sys.argv)
    with Case(caseroot, read_only=False) as case:
        buildlib(bldroot, libroot, case)


if (__name__ == "__main__"):
    _main(sys.argv, __doc__)
