#!/usr/bin/env python3

import os
import sys

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    _MSG = "ERROR: must set CIMEROOT environment variable"
    raise SystemExit(_MSG)

_LIBDIR = os.path.join(_CIMEROOT, "CIME", "Tools")
sys.path.append(_LIBDIR)

from CIME.buildlib import parse_input
from CIME.case import Case
from standard_script_setup import *

logger = logging.getLogger(__name__)  # noqa: F405


def buildlib(bldroot, installpath, case):
    """ """
    print("building omega")

    metis_root = os.environ["METIS_ROOT"]
    parmetis_root = os.environ["PARMETIS_ROOT"]

    cmake_args = (
        f" -DOMEGA_BUILD_MODE=E3SM"
        f' -DOMEGA_METIS_ROOT="{metis_root}"'
        f' -DOMEGA_PARMETIS_ROOT="{parmetis_root}"'
    )

    comp_interface = case.get_value("COMP_INTERFACE")
    moab_root = os.environ.get("MOAB_ROOT")
    if comp_interface == "moab" and moab_root:
        cmake_args += f' -DOMEGA_MOAB_ROOT="{moab_root}"'

    print(f"omega cmake options: '{cmake_args}'")

    return cmake_args


def _main(argv, documentation):
    """ """
    caseroot, libroot, bldroot = parse_input(sys.argv)
    with Case(caseroot, read_only=False) as case:
        buildlib(bldroot, libroot, case)


if __name__ == "__main__":
    _main(sys.argv, __doc__)
