#!/usr/bin/env python3

"""
Checks that output on a generic 2d rectilinear (hrrr) grid matches expected values.
The output file is expected to have dims (y,x), with x the fastest varying one,
and the remapped fields are compared against an independent mat-vec computed
directly from the map file.
"""

import argparse, sys, pathlib
from netCDF4 import Dataset
import numpy as np

###############################################################################
def parse_command_line(args, description):
###############################################################################
    parser = argparse.ArgumentParser(
        usage="""\n{0} <param>=<val> [<param>=<val>] ...
OR
{0} --help
""".format(pathlib.Path(args[0]).name),
        description=description,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument("--map-file",required=True,type=str,
        help="The path to the map file used in the io_hrrr test",
    )
    parser.add_argument("--out-file",required=True,type=str,
        help="The name of the output file generated by the io_hrrr test",
    )
    parser.add_argument("--nx",required=True,type=int,
        help="Number of points along x (the fastest varying index) of the tgt grid",
    )
    parser.add_argument("--ny",required=True,type=int,
        help="Number of points along y of the tgt grid",
    )

    return parser.parse_args(args[1:])

###############################################################################
def check_hrrr_output(map_file,out_file,nx,ny):
###############################################################################
    with Dataset(map_file, 'r') as map_ds:
        xc_a = map_ds.variables['xc_a'][:]
        yc_a = map_ds.variables['yc_a'][:]
        xc_b = map_ds.variables['xc_b'][:]
        yc_b = map_ds.variables['yc_b'][:]
        row  = map_ds.variables['row'][:] - 1   # map files are 1-based
        col  = map_ds.variables['col'][:] - 1
        S    = map_ds.variables['S'][:]

    ncols = nx*ny
    assert xc_b.size==ncols, "nx*ny does not match the tgt grid size in the map file"

    # Independent reference mat-vec
    def matvec(src):
        tgt = np.zeros(ncols)
        np.add.at(tgt,row,S*src[col])
        return tgt.reshape(ny,nx)

    # Sanity check: this test is meant for grids where nx is not nlon, and ny is not nlat
    assert len(np.unique(np.round(xc_b,4)))>nx and len(np.unique(np.round(yc_b,4)))>ny, \
        "Test map file is a lat-lon grid. This test requires a non lat-lon rectilinear grid."

    ok = True
    with Dataset(out_file, 'r') as out_ds:
        for d,n in [('x',nx),('y',ny)]:
            if d not in out_ds.dimensions or out_ds.dimensions[d].size!=n:
                print(f"Dimension '{d}' is missing, or has the wrong size (expected {n})")
                ok = False
        for d in ['lat','lon','ncol']:
            if d in out_ds.dimensions:
                print(f"Dimension '{d}' should NOT be in the output file")
                ok = False
        if not ok:
            return False

        for name,src,tgt in [('f_lat',yc_a,yc_b),('f_lon',xc_a,xc_b)]:
            var = out_ds.variables[name]
            if var.dimensions!=('time','y','x'):
                print(f"Variable '{name}' has wrong dims: {var.dimensions}")
                ok = False
                continue
            expected = matvec(src)
            if not np.allclose(var[0,:,:], expected, rtol=1e-5, atol=1e-4):
                print(f"'{name}' does not match the expected remapped values")
                print(var[0,:,:]); print(expected)
                ok = False

            # Remapping lat/lon is only O(1e-1) close to the tgt lat/lon, but it
            # still would catch swapping x and y, or a transposed layout
            if not np.allclose(var[0,:,:], tgt.reshape(ny,nx), rtol=0.1):
                print(f"'{name}' is not close to the tgt grid values (x/y mixup?)")
                ok = False

        # The geo data lat/lon should be 2d fields on (y,x), matching tgt grid coords
        for name,tgt in [('lat',yc_b),('lon',xc_b)]:
            if name not in out_ds.variables:
                print(f"Geo variable '{name}' not found in the output file")
                ok = False
                continue
            var = out_ds.variables[name]
            if var.dimensions!=('y','x'):
                print(f"Geo variable '{name}' has wrong dims: {var.dimensions}")
                ok = False
            elif not np.allclose(var[:,:], tgt.reshape(ny,nx), rtol=1e-6, atol=1e-4):
                print(f"Geo variable '{name}' does not match the map file tgt coordinates")
                ok = False

    return ok

###############################################################################
def _main_func(description):
###############################################################################
    success = check_hrrr_output(**vars(parse_command_line(sys.argv, description)))
    sys.exit(0 if success else 1)

###############################################################################

if (__name__ == "__main__"):
    _main_func(__doc__)
