#! /usr/bin/env perl

use File::Basename;
use Cwd 'abs_path';

sub main
{
    my $script_loc = abs_path(dirname(__FILE__));
    my $cimeroot = abs_path("$script_loc/..");
    my @dirs = ("$cimeroot/scripts/Tools", "$cimeroot/utils/perl5lib/Config", "$cimeroot/utils/perl5lib");
    unshift @INC, @dirs;
    require ConfigCase;
    require Log::Log4perl;
    Log::Log4perl->easy_init({level=>"INFO",
			  layout=>'%m%n'});

    my $xml_file = shift;

    my $file = "$cimeroot/driver_cpl/cime_config/config_component.xml";
    my $srcroot  = abs_path("$cimeroot/../");
    my $caseroot = dirname($xml_file);
    my $cfg_ref = ConfigCase->new("");

    $cfg_ref->add_config_variables($file, $srcroot, $cimeroot);

    while (my $value = shift) {
        my @key_val_pair = split(",", $value);
        $cfg_ref->set($key_val_pair[0], $key_val_pair[1]);
    }

    my $caseheaders = "";
    $cfg_ref->write_file($xml_file, $caseheaders, $caseroot, $cimeroot);
}

main(@ARGV) unless caller();
1;
