.SUFFIXES:
.SUFFIXES: .F .F90 .c .o

CPPDEF    := -DAIX -DSPMD -DHAVE_COMM_F2C

FC := mpxlf90_r
CC := mpcc_r
FFLAGS    := $(CPPDEF) -q64 -qarch=auto
CFLAGS    := $(CPPDEF) -q64 -qkeyword=inline
FREEFLAGS := -qsuffix=f=f90:cpp=F90
FIXEDFLAGS := -qfixed=132

.F90.o:
	$(FC) -c $(FREEFLAGS) $(FFLAGS) -I. $<
.F.o:
	$(FC) -c $(FIXEDFLAGS) $(FFLAGS) -I. $<
.c.o:
	$(CC) -c $(CFLAGS) -I. $<

#------------------------------------------------------------------------
# Targets/rules that depend on architecture specific variables.
#------------------------------------------------------------------------

OBJS := GPTLget_memusage.o GPTLprint_memusage.o GPTLutil.o f_wrappers.o \
        gptl.o gptl_papi.o perf_utils.o perf_mod.o
RM   := rm
AR   := ar
ARFLAGS := -rc
RANLIB  := ranlib

all: libgptl.a

libgptl.a : $(OBJS)
	$(AR) $(ARFLAGS) $@ $(OBJS)
	$(RANLIB) $@

clean:
	$(RM) -f *.o *.mod *.a

