if (MPILIB STREQUAL "mpich")
  string(APPEND CONFIG_ARGS " --host=cray")
endif()
set(USE_CUDA "TRUE")
string(APPEND CPPDEFS " -DGPU")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_NANOTIME -DBIT64 -DHAVE_SLASHPROC -DHAVE_GETTIMEOFDAY")
endif()
string(APPEND CPPDEFS " -DTHRUST_IGNORE_CUB_VERSION_CHECK")
if (MPILIB STREQUAL "mpich")
  string(APPEND CMAKE_CUDA_FLAGS " -ccbin CC -O2 -arch sm_80 --use_fast_math")
else()
  string(APPEND CMAKE_CUDA_FLAGS " -ccbin mpicxx -O2 -arch sm_80 --use_fast_math")
endif()
string(APPEND KOKKOS_OPTIONS " -DKokkos_ARCH_AMPERE80=On -DKokkos_ENABLE_CUDA=On -DKokkos_ENABLE_CUDA_LAMBDA=On -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=Off -DKokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC=OFF")
# Was trying this with cmake 3.30, but then ran into other issues
#string(APPEND KOKKOS_OPTIONS " -DKokkos_ARCH_AMPERE80=On -DKokkos_ENABLE_CUDA=On -DKokkos_ENABLE_CUDA_LAMBDA=On -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=Off -DKokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC=OFF -DCMAKE_CXX_EXTENSIONS=Off")
set(CMAKE_CUDA_ARCHITECTURES "80")
string(APPEND CMAKE_C_FLAGS_RELEASE " -O2")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O2")
if (MPILIB STREQUAL "mpich")
  set(MPICC "cc")
  set(MPICXX "CC")
  set(MPIFC "ftn")
else()
  set(MPICC "mpicc")
  set(MPICXX "mpicxx")
  set(MPIFC "mpifort")
  set(NetCDF_C_PATH "$ENV{NETCDF_PATH}" CACHE FILEPATH "" FORCE)
  set(NetCDF_Fortran_PATH "$ENV{NETCDF_PATH}" CACHE FILEPATH "" FORCE)
  set(BLA_VENDOR Cray CACHE STRING "")
  set(BLAS_LIBRARIES "$ENV{CRAY_LIBSCI_PREFIX_DIR}/lib/libsci_gnu.so" CACHE STRING "" FORCE)
  set(LAPACK_LIBRARIES "$ENV{CRAY_LIBSCI_PREFIX_DIR}/lib/libsci_gnu.so" CACHE STRING "" FORCE)
endif()
set(SCC "cc")
set(SCXX "CC")
set(SFC "ftn")
