if (compile_threaded)
  string(APPEND FFLAGS " -fopenmp")
  string(APPEND CFLAGS " -fopenmp")
  string(APPEND CXXFLAGS " -fopenmp")
  string(APPEND LDFLAGS " -fopenmp")
endif()
string(APPEND CPPDEFS " -DNO_R16 -DCPRAMD -DFORTRANUNDERSCORE")
string(APPEND SLIBS " -L$ENV{PNETCDF_PATH}/lib -lpnetcdf -L$ENV{CRAY_LIBSCI_PREFIX_DIR}/lib -lsci_amd")
set(PNETCDF_PATH "$ENV{PNETCDF_DIR}")
set(CRAY_LIBSCI_PREFIX_DIR "$ENV{CRAY_LIBSCI_PREFIX_DIR}")
set(PIO_FILESYSTEM_HINTS "gpfs")
set(SUPPORTS_CXX "TRUE")
#set(CXX_LINKER "FORTRAN")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DFORTRANUNDERSCORE")
endif()
#
#if (compile_threaded)
#  string(APPEND FFLAGS " -fopenmp")
#  string(APPEND CFLAGS " -fopenmp")
#  string(APPEND CXXFLAGS " -fopenmp")
#  string(APPEND LDFLAGS " -fopenmp")
#  string(APPEND CXX_LIBS " -lsci_amd_mp")
#endif()
#if (NOT compile_threaded)
#  string(APPEND CXX_LIBS " -lsci_amd")
#endif()
#string(APPEND CPPDEFS " -DNO_R16 -DCPRAMD")
#string(APPEND SLIBS " -L$ENV{PNETCDF_PATH}/lib -lpnetcdf")
#set(MPI_LIB_NAME "mpich")
#set(MPI_PATH "$ENV{MPICH_DIR}")
#set(NETCDF_PATH "$ENV{NETCDF_DIR}")
#set(PNETCDF_PATH "$ENV{PNETCDF_DIR}")
#set(PIO_FILESYSTEM_HINTS "gpfs")
#set(SUPPORTS_CXX "TRUE")
##set(CXX_LINKER "CXX")
#set(CXX_LINKER "FORTRAN")
#string(APPEND CXX_LIBS " -lstdc++")
#if (COMP_NAME STREQUAL gptl)
#  string(APPEND CPPDEFS " -DFORTRANUNDERSCORE")
#endif()
