if (NOT DEBUG)
  string(APPEND CFLAGS   " -O2")
  string(APPEND CXXFLAGS " -O2")
  string(APPEND FFLAGS   " -O2")
  string(APPEND HIP_FLAGS " -O3")
endif()
if (DEBUG)
  string(APPEND HIP_FLAGS " -O0 -g")
endif()
string(APPEND CFLAGS   " -I$ENV{MPICH_DIR}/include -I$ENV{ROCM_PATH}/include")
string(APPEND CXXFLAGS " -I$ENV{MPICH_DIR}/include -I$ENV{ROCM_PATH}/include")
string(APPEND FFLAGS   " -I$ENV{MPICH_DIR}/include -I$ENV{ROCM_PATH}/include")
string(APPEND HIP_FLAGS " -D__HIP_ROCclr__ -D__HIP_ARCH_GFX90A__=1 --rocm-path=$ENV{ROCM_PATH} --offload-arch=gfx90a -x hip")

set(PIO_FILESYSTEM_HINTS "gpfs")
set(NETCDF_PATH "$ENV{NETCDF_DIR}")
set(PNETCDF_PATH "$ENV{PNETCDF_DIR}")
string(APPEND SLIBS " -L$ENV{PNETCDF_PATH}/lib -lpnetcdf -L$ENV{CRAY_LIBSCI_PREFIX_DIR}/lib -lsci_amd")
set(CRAY_LIBSCI_PREFIX_DIR "$ENV{CRAY_LIBSCI_PREFIX_DIR}")
set(CMAKE_HIP_COMPILER_ENV_VAR "HIPCXX")
set(CMAKE_HIP_COMPILER_LOADED 1)
set(CMAKE_HIP_COMPILER_ID_RUN 1) 
set(USE_HIP "TRUE")
