string(APPEND CMAKE_EXE_LINKER_FLAGS " -gpu=cc70,cc60 -Minfo=accel")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -L$ENV{ESSL_PATH}/lib64 -lessl")
string(APPEND KOKKOS_OPTIONS " -DKokkos_ARCH_POWER9=On -DKokkos_ARCH_VOLTA70=On -DKokkos_ENABLE_CUDA=On -DKokkos_ENABLE_CUDA_LAMBDA=On")
