if (compile_threaded)
  string(APPEND CMAKE_C_FLAGS          " -qopenmp")
  string(APPEND CMAKE_CXX_FLAGS        " -qopenmp")
  string(APPEND CMAKE_Fortran_FLAGS    " -qopenmp")
  string(APPEND CMAKE_EXE_LINKER_FLAGS " -qopenmp")

  string(APPEND KOKKOS_OPTIONS " -DKokkos_ENABLE_AGGRESSIVE_VECTORIZATION=On")
endif()

string(APPEND CMAKE_C_FLAGS         " -fp-model precise -std=gnu99 -static-intel -march=core-avx2")
string(APPEND CMAKE_C_FLAGS_DEBUG   " -O0 -g")
string(APPEND CMAKE_C_FLAGS_RELEASE " -O3 -debug minimal")
string(APPEND CMAKE_CXX_FLAGS         " -fp-model source -static-intel -axCORE-AVX2")
string(APPEND CMAKE_CXX_FLAGS_DEBUG   " -O0 -g")
string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O3")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -static-intel")
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL")

string(APPEND CMAKE_Fortran_FLAGS         " -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source -static-intel -axCORE-AVX2")
string(APPEND CMAKE_Fortran_FLAGS_DEBUG   " -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created -init=snan,arrays")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O3 -qno-opt-dynamic-align -debug minimal")
string(APPEND CMAKE_Fortran_FORMAT_FIXED_FLAG " -fixed -132")
string(APPEND CMAKE_Fortran_FORMAT_FREE_FLAG " -free")

string(APPEND KOKKOS_OPTIONS " -DKokkos_ARCH_ZEN2=On")

set(HAS_F2008_CONTIGUOUS "TRUE")
set(E3SM_LINK_WITH_FORTRAN "TRUE")
set(PIO_FILESYSTEM_HINTS "gpfs")

if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
if (COMP_NAME STREQUAL cice)
  string(APPEND CMAKE_Fortran_FLAGS_DEBUG " -init=nosnan,arrays")
endif()
if (COMP_NAME STREQUAL gcam)
  string(APPEND CMAKE_C_FLAGS " -mcmodel=medium -shared-intel")
  string(APPEND CMAKE_Fortran_FLAGS " -mcmodel=medium -shared-intel")
  string(APPEND CMAKE_CXX_FLAGS " -shared-intel")
  string(APPEND CMAKE_EXE_LINKER_FLAGS " -shared-intel")
  string(APPEND CMAKE_CXX_FLAGS " -DNDEBUG")
endif()

set(MPICC "mpicc")
set(MPICXX "mpicxx")
set(MPIFC "mpif90")
set(SCC "icc")
set(SCXX "icpc")
set(SFC "ifort")
if (MPILIB STREQUAL impi)
  set(MPICC "mpiicc")
  set(MPICXX "mpiicpc")
  set(MPIFC "mpiifort")
endif()
