if (compile_threaded)
  string(APPEND CFLAGS   " -fopenmp")
  string(APPEND FFLAGS   " -fopenmp")
  string(APPEND CXXFLAGS " -fopenmp")
  string(APPEND LDFLAGS  " -fopenmp")
endif()
if (DEBUG)
  string(APPEND CFLAGS   " -O0 -g")
  string(APPEND FFLAGS   " -O0 -g")
  string(APPEND CXXFLAGS " -O0 -g")
  string(APPEND CPPDEFS  " -DYAKL_DEBUG")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRCRAY")
string(APPEND FC_AUTO_R8 " -s real64")
# -em (default) generates MODULENAME.mod files
string(APPEND FFLAGS " -f free -N 255 -h byteswapio -em")
if (NOT compile_threaded)
	# -M1077 flag used to suppress message about OpenMP directives
	# that are ignored for non-threaded builds. (-h omp inactive)
	# Details: `explain ftn-1077`
  string(APPEND FFLAGS " -M1077")
endif()
string(APPEND FFLAGS_NOOPT " -O0")
set(HAS_F2008_CONTIGUOUS "TRUE")
string(APPEND LDFLAGS " -Wl,--allow-multiple-definition -h byteswapio")
set(SUPPORTS_CXX "TRUE")
set(CXX_LINKER "FORTRAN")
set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "cc")
set(SCXX "CC")
set(SFC "ftn")
