if (compile_threaded)
  string(APPEND CMAKE_C_FLAGS   " -fopenmp")
  string(APPEND CMAKE_Fortran_FLAGS   " -fopenmp")
  string(APPEND CMAKE_CXX_FLAGS " -fopenmp")
  string(APPEND CMAKE_EXE_LINKER_FLAGS  " -fopenmp")
endif()
string(APPEND CMAKE_C_FLAGS_DEBUG   " -O0 -g")
string(APPEND CMAKE_Fortran_FLAGS_DEBUG   " -O0 -g")
string(APPEND CMAKE_CXX_FLAGS_DEBUG " -O0 -g")
string(APPEND CPPDEFS_DEBUG  " -DYAKL_DEBUG")
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRCRAY")
# -em -ef generates modulename.mod files (lowercase), which we must have
string(APPEND CMAKE_Fortran_FLAGS " -f free -em -ef")
if (NOT compile_threaded)
	# -M1077 flag used to suppress message about OpenMP directives
	# that are ignored for non-threaded builds. (-h omp inactive)
	# Details: `explain ftn-1077`
  string(APPEND CMAKE_Fortran_FLAGS " -M1077")
endif()
set(HAS_F2008_CONTIGUOUS "TRUE")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,--allow-multiple-definition -ldl")
set(E3SM_LINK_WITH_FORTRAN "TRUE")
set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "cc")
set(SCXX "CC")
set(SFC "ftn")
