if (compile_threaded)
  string(APPEND CMAKE_C_FLAGS " -fopenmp")
  string(APPEND CMAKE_Fortran_FLAGS " -fopenmp")
  string(APPEND CMAKE_CXX_FLAGS " -fopenmp")
  string(APPEND CMAKE_EXE_LINKER_FLAGS " -fopenmp")
endif()
if (COMP_NAME STREQUAL elm)
  string(APPEND CMAKE_Fortran_FLAGS " -hfp0")
endif()
string(APPEND CMAKE_Fortran_FLAGS " -hipa0 -hzero")
string(APPEND CMAKE_Fortran_FLAGS " -em -ef")

set(PIO_FILESYSTEM_HINTS "gpfs")
