if (NOT DEBUG)
  string(APPEND CFLAGS " -O2 -hnoacc -hzero -hfp0 -hipa0 -I$ENV{MPICH_DIR}/include -I$ENV{ROCM_PATH}/include")
  string(APPEND CXXFLAGS " -O2 -hnoacc -hzero -hfp0 -hipa0 -I$ENV{MPICH_DIR}/include -I$ENV{ROCM_PATH}/include")
  string(APPEND FFLAGS " -O2 -hnoacc -hzero -hfp0 -hipa0 -I$ENV{MPICH_DIR}/include -I$ENV{ROCM_PATH}/include")
  string(APPEND HIP_FLAGS " -O3 -munsafe-fp-atomics -hzero -hfp0 -hfp0 -hipa0 -D__HIP_ROCclr__ -D__HIP_ARCH_GFX90A__=1 --rocm-path=$ENV{ROCM_PATH} --offload-arch=gfx90a -x hip")
endif()
if (DEBUG)
  string(APPEND CFLAGS " -O0 -g -hnoacc -hzero -hfp0 -hipa0 -I$ENV{MPICH_DIR}/include -I$ENV{ROCM_PATH}/include")
  string(APPEND CXXFLAGS " -O0 -g -hnoacc -hzero -hfp0 -hipa0 -I$ENV{MPICH_DIR}/include -I$ENV{ROCM_PATH}/include")
  string(APPEND FFLAGS " -O0 -g -hnoacc -hzero -hfp0 -hipa0 -I$ENV{MPICH_DIR}/include -I$ENV{ROCM_PATH}/include")
  string(APPEND HIP_FLAGS " -O3 -munsafe-fp-atomics -hzero -hipa0 -D__HIP_ROCclr__ -D__HIP_ARCH_GFX90A__=1 --rocm-path=$ENV{ROCM_PATH} --offload-arch=gfx90a -x hip")
endif()
if (compile_threaded)
  string(APPEND CFLAGS " -fopenmp")
  string(APPEND FFLAGS " -fopenmp")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRCRAY")
string(APPEND FC_AUTO_R8 " -s real64")
string(APPEND FFLAGS " -f free -N 255 -h byteswapio -em")
string(APPEND FFLAGS_NOOPT " -O0")
set(HAS_F2008_CONTIGUOUS "TRUE")
string(APPEND LDFLAGS " -Wl,--allow-multiple-definition -h byteswapio --rocm-path=$ENV{ROCM_PATH}")
if (compile_threaded)
  string(APPEND LDFLAGS " -fopenmp")
endif()
set(SUPPORTS_CXX "TRUE")
set(CXX_LINKER "FORTRAN")
set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "cc")
set(SCXX "CC")
set(SFC "ftn")
#set(PIO_FILESYSTEM_HINTS "gpfs")
set(PNETCDF_HINTS "romio_cb_read=disable")
set(PIO_FILESYSTEM_HINTS "romio_cb_read=disable")
set(NETCDF_PATH "$ENV{NETCDF_DIR}")
set(PNETCDF_PATH "$ENV{PNETCDF_DIR}")
string(APPEND SLIBS " $ENV{ROCM_PATH}/lib -lamdhip64")
set(USE_HIP "TRUE")
