string(APPEND CMAKE_C_FLAGS_RELEASE " -O1")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O1")
if (COMP_NAME STREQUAL eam)
  string(APPEND CMAKE_Fortran_FLAGS " -vector0")
endif()
string(APPEND KOKKOS_OPTIONS " -DKokkos_INTERNAL_GCC_TOOLCHAIN=/opt/gcc/9.3.0/snos")
if (compile_threaded)
  string(APPEND CMAKE_CXX_FLAGS " -fopenmp")
endif()
string(APPEND CMAKE_CXX_FLAGS_DEBUG " -g -Wall")
string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O1")
