if (compile_threaded)
  string(APPEND CFLAGS   " -Kopenmp")
  string(APPEND CXXFLAGS " -Kopenmp")
  string(APPEND FFLAGS   " -Kopenmp")
  string(APPEND LDFLAGS  " -Kopenmp")
endif()
if (DEBUG)
  string(APPEND CFLAGS   " -g -Nquickdbg=subchk")
  string(APPEND CXXFLAGS " -g -Nquickdbg=subchk")
  string(APPEND FFLAGS   " -g -Haefosux")
  string(APPEND CPPDEFS  "-DYAKL_DEBUG")
elseif (NOT DEBUG)
  string(APPEND CFLAGS   " -O2")
  string(APPEND CXXFLAGS " -O2")
  string(APPEND FFLAGS   " -O2")
endif()
if (COMP_NAME STREQUAL csm_share)
  string(APPEND CFLAGS " -std=c99")
endif()
set(SUPPORTS_CXX "TRUE")
set(CXX_LINKER "FORTRAN")
set(CXX_LIBS "--linkstl=libfjc++")
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRFJ")
set(FC_AUTO_R8 "-CcdRR8")
set(FFLAGS_NOOPT " -O0")
set(FIXEDFLAGS "-Fixed")
set(FREEFLAGS "-Free")
set(HAS_F2008_CONTIGUOUS "FALSE")
set(MPICC "mpifcc")
set(MPICXX "mpiFCC")
set(MPIFC "mpifrt")
set(SCC "fcc")
set(SCXX "FCC")
set(SFC "frt")
if (COMP_NAME MATCHES "^pio")
  string(APPEND CMAKE_OPTS " -DPIO_ENABLE_TOOLS:BOOL=OFF")
endif()
