string(APPEND CMAKE_C_FLAGS " -mcmodel=medium")
if (compile_threaded)
  string(APPEND CMAKE_C_FLAGS " -fopenmp")
endif()
string(APPEND CMAKE_C_FLAGS_DEBUG " -g -Wall -fbacktrace -fcheck=bounds -ffpe-trap=invalid,zero,overflow")
string(APPEND CMAKE_C_FLAGS_RELEASE " -O")
if (COMP_NAME STREQUAL csm_share)
  string(APPEND CMAKE_C_FLAGS " -std=c99")
endif()
string(APPEND CMAKE_CXX_FLAGS " -std=c++14")
if (compile_threaded)
  string(APPEND CMAKE_CXX_FLAGS " -fopenmp")
endif()
string(APPEND CMAKE_CXX_FLAGS_DEBUG " -g -Wall -fbacktrace")
string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O")
set(CMAKE_AR "/opt/conda/bin/x86_64-conda-linux-gnu-ar")
string(APPEND SPIO_CMAKE_OPTS " -DCMAKE_AR=/opt/conda/bin/x86_64-conda-linux-gnu-ar")
string(APPEND SPIO_CMAKE_OPTS " -DCMAKE_Fortran_COMPILER_RANLIB=/opt/conda/bin/x86_64-conda-linux-gnu-ranlib")
string(APPEND SPIO_CMAKE_OPTS " -DCMAKE_C_COMPILER_RANLIB=/opt/conda/bin/x86_64-conda-linux-gnu-ranlib")
string(APPEND SPIO_CMAKE_OPTS " -DCMAKE_CXX_COMPILER_RANLIB=/opt/conda/bin/x86_64-conda-linux-gnu-ranlib")
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU")
string(APPEND CPPDEFS_DEBUG " -DYAKL_DEBUG")
string(APPEND CMAKE_Fortran_FLAGS " -I/opt/conda/include -mcmodel=medium -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none")
if (compile_threaded)
  string(APPEND CMAKE_Fortran_FLAGS " -fopenmp")
endif()
string(APPEND CMAKE_Fortran_FLAGS_DEBUG " -g -Wall -fbacktrace -fcheck=bounds -ffpe-trap=zero,overflow")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O")
string(APPEND CMAKE_Fortran_FORMAT_FIXED_FLAG " -ffixed-form")
string(APPEND CMAKE_Fortran_FORMAT_FREE_FLAG " -ffree-form")
if (compile_threaded)
  string(APPEND CMAKE_EXE_LINKER_FLAGS " -fopenmp")
endif()
set(CMAKE_EXE_LINKER_FLAGS " -L/opt/conda/lib")
set(MPICC "/opt/conda/bin/mpicc")
set(MPICXX "/opt/conda/bin/mpicxx")
set(MPIFC "/opt/conda/bin/mpif90")
set(SCC "/opt/conda/bin/x86_64-conda-linux-gnu-gcc")
set(SCXX "/opt/conda/bin/x86_64-conda-linux-gnu-g++")
set(SFC "/opt/conda/bin/x86_64-conda-linux-gnu-gfortran")
