if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_VPRINTF -DHAVE_GETTIMEOFDAY -DHAVE_BACKTRACE")
endif()
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -fno-unsafe-math-optimizations ")
string(APPEND CMAKE_Fortran_FLAGS_DEBUG " -g -fbacktrace -fbounds-check -ffpe-trap=invalid,zero,overflow -Wall")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -lcurl")
if (MPILIB STREQUAL mpi-serial)
  set(SCC "gcc")
endif()
if (MPILIB STREQUAL mpi-serial)
  set(SFC "gfortran")
endif()
