set(SUPPORTS_CXX "TRUE")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_VPRINTF -DHAVE_GETTIMEOFDAY -DHAVE_BACKTRACE")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -fno-unsafe-math-optimizations ")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -g -fbacktrace -fbounds-check -ffpe-trap=invalid,zero,overflow -Wall")
endif()
string(APPEND SLIBS " -lcurl")
if (MPILIB STREQUAL mpi-serial)
  set(SCC "gcc")
endif()
if (MPILIB STREQUAL mpi-serial)
  set(SFC "gfortran")
endif()
string(APPEND CXX_LIBS " -lstdc++")
