string(APPEND CONFIG_ARGS " --host=cray")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_NANOTIME -DBIT64 -DHAVE_SLASHPROC -DHAVE_GETTIMEOFDAY")
endif()
string(APPEND SLIBS " -L$ENV{CRAY_HDF5_PARALLEL_PREFIX}/lib -lhdf5_hl -lhdf5 -L$ENV{CRAY_NETCDF_HDF5PARALLEL_PREFIX} -L$ENV{CRAY_PARALLEL_NETCDF_PREFIX}/lib -lpnetcdf -lnetcdf -lnetcdff")
set(CXX_LINKER "FORTRAN")
set(NETCDF_PATH "/opt/cray/pe/netcdf-hdf5parallel/4.7.4.4/gnu/9.1/")
set(NETCDF_C_PATH "/opt/cray/pe/netcdf-hdf5parallel/4.7.4.4/gnu/9.1/")
set(NETCDF_FORTRAN_PATH "/opt/cray/pe/netcdf-hdf5parallel/4.7.4.4/gnu/9.1/")
set(HDF5_PATH "$ENV{CRAY_HDF5_PARALLEL_PREFIX}")
set(PNETCDF_PATH "$ENV{CRAY_PARALLEL_NETCDF_PREFIX}")
if (NOT DEBUG)
  string(APPEND CFLAGS " -O2 -g")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -O2 -g")
endif()
string(APPEND CXX_LIBS " -lstdc++")
set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "gcc")
set(SCXX "g++")
set(SFC "gfortran")
