set(NETCDF_PATH "$ENV{NETCDF_PATH}")
# set(CMAKE_CXX_STANDARD=17)
string(APPEND SLIBS " -L${NETCDF_PATH}/lib -lnetcdff -lnetcdf")
string(APPEND CXX_LIBS " -lstdc++")
string(APPEND CPPFLAGS " -I/opt/homebrew/opt/lapack/include")
string(APPEND CXXFLAGS " -std=c++14")
string(APPEND CFLAGS " -mcmodel=small")
string(APPEND FFLAGS " -mcmodel=small")
string(APPEND FFLAGS " -ffree-line-length-none -ffixed-line-length-none")
string(APPEND FFLAGS " -fallow-argument-mismatch -fallow-invalid-boz")
string(APPEND FFLAGS_NOOPT " -ffree-line-length-none -ffixed-line-length-none")
set(MPICC "mpicc")
set(MPICXX "mpic++")
set(MPIFC "mpif90")
set(SCC "gcc")
set(SCXX "clang++")
set(SFC "gfortran")
string(APPEND LDFLAGS " -L/opt/homebrew/opt/lapack/lib -llapack")
string(APPEND LDFLAGS " -L/opt/homebrew/opt/openblas/lib -lblas")
string(APPEND LDFLAGS " -L/opt/homebrew/opt/curl/lib -lcurl")
string(APPEND LDFLAGS " -L/opt/homebrew/opt/llvm/lib")
string(APPEND LDFLAGS " -L/Users/hannah6/hdf5/install/lib -lhdf5_hl -lhdf5")
string(APPEND SLIBS " -lstdc++")

