string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
if (NOT DEBUG)
  string(APPEND CFLAGS " -O2")
  string(APPEND FFLAGS " -O2")
endif()
set(CXX_LIBS "-lstdc++")
if (COMP_NAME MATCHES "^pio")
  string(APPEND CMAKE_OPTS " -DPIO_ENABLE_TOOLS:BOOL=OFF")
endif()
