if (compile_threaded)
  string(APPEND CFLAGS " -fopenmp")
endif()
if (COMP_NAME STREQUAL cism)
  string(APPEND CMAKE_OPTS " -D CISM_GNU=ON")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16")
set(CXX_LINKER "FORTRAN")
set(FC_AUTO_R8 "-fdefault-real-8")
set(FFLAGS "-O -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none -fno-range-check")
if (compile_threaded)
  string(APPEND FFLAGS " -fopenmp")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -g -Wall")
endif()
set(FIXEDFLAGS "-ffixed-form")
set(FREEFLAGS "-ffree-form")
set(HDF5_PATH "/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/hdf5-parallel/1.8.17/centos7.2_gnu5.3.0")
set(NETCDF_PATH "/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/netcdf-hdf5parallel/4.3.3.1/centos7.2_gnu5.3.0")
set(PNETCDF_PATH "/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/pnetcdf/1.9.0/centos7.2_gnu5.3.0")
set(LAPACK_LIBDIR "/software/tools/compilers/intel_2017/mkl/lib/intel64")
if (compile_threaded)
  string(APPEND LDFLAGS " -fopenmp")
endif()
string(APPEND SLIBS " -L${NETCDF_PATH}/lib -Wl,-rpath=${NETCDF_PATH}/lib -lnetcdff -lnetcdf")
set(MPICC "mpicc")
set(MPICXX "mpic++")
set(MPIFC "mpif90")
set(SCC "gcc")
set(SCXX "gcpp")
set(SFC "gfortran")
set(SUPPORTS_CXX "TRUE")
