if (NOT DEBUG)
  string(APPEND CFLAGS " -O2")
  string(APPEND CXXFLAGS " -O2")
  string(APPEND FFLAGS " -O2")
  string(APPEND CUDA_FLAGS " -gpu -O3 -arch sm_80 --use_fast_math")
endif()
if (DEBUG)
  string(APPEND CFLAGS " -O2 -g")
  string(APPEND CXXFLAGS " -O2 -g")
  string(APPEND FFLAGS " -O2 -g")	
  string(APPEND CUDA_FLAGS " -O0 -g -gpu -arch sm_80 --use_fast_math")
endif()
set(USE_CUDA "TRUE")
string(APPEND CONFIG_ARGS " --host=cray")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_NANOTIME -DBIT64 -DHAVE_SLASHPROC -DHAVE_GETTIMEOFDAY")
endif()
string(APPEND SLIBS " -L$ENV{CRAY_HDF5_PARALLEL_PREFIX}/lib -lhdf5_hl -lhdf5 -L$ENV{CRAY_NETCDF_HDF5PARALLEL_PREFIX} -L$ENV{CRAY_PARALLEL_NETCDF_PREFIX}/lib -lpnetcdf -lnetcdf -lnetcdff")
string(APPEND SLIBS " -L$ENV{LAPACK_PATH}/lib -llapack -L$ENV{OPENBLAS_PATH}/lib -lblas")
string(APPEND SLIBS " $ENV{PE_MPICH_GTL_DIR_nvidia80} $ENV{PE_MPICH_GTL_LIBS_nvidia80}")
if (NOT MPILIB STREQUAL mpi-serial)
#  string(APPEND SLIBS " -L$ENV{ADIOS2_DIR}/lib64 -ladios2_c_mpi -ladios2_c -ladios2_core_mpi -ladios2_core -ladios2_evpath -ladios2_ffs -ladios2_dill -ladios2_atl -ladios2_enet")
endif()
set(CXX_LINKER "FORTRAN")
set(NETCDF_PATH "$ENV{CRAY_NETCDF_HDF5PARALLEL_PREFIX}")
set(NETCDF_C_PATH "$ENV{CRAY_NETCDF_HDF5PARALLEL_PREFIX}")
set(NETCDF_FORTRAN_PATH "$ENV{CRAY_NETCDF_HDF5PARALLEL_PREFIX}")
set(HDF5_PATH "$ENV{CRAY_HDF5_PARALLEL_PREFIX}")
set(PNETCDF_PATH "$ENV{CRAY_PARALLEL_NETCDF_PREFIX}")
if (compile_threaded)
  string(APPEND KOKKOS_OPTIONS " -DKokkos_ENABLE_OPENMP=Off") 
endif()
set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "cc")
set(SCXX "CC")
set(SFC "ftn")
