string(APPEND CMAKE_C_FLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo")
string(APPEND CMAKE_CXX_FLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo")
string(APPEND CMAKE_C_FLAGS_RELEASE " -O3")
string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O2")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O2 -qstrict -Q")
if (compile_threaded)
  string(APPEND CMAKE_C_FLAGS_DEBUG " -qsmp=omp:noopt")
  string(APPEND CMAKE_CXX_FLAGS_DEBUG " -qsmp=omp:noopt")
  string(APPEND CMAKE_Fortran_FLAGS_DEBUG " -qsmp=omp:noopt")
  string(APPEND CMAKE_C_FLAGS_RELEASE " -qsmp=omp")
  string(APPEND CMAKE_CXX_FLAGS_RELEASE " -qsmp=omp")
  string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -qsmp=omp")
endif()

string(APPEND CPPDEFS " -DFORTRAN_SAME -DCPRIBM")
if (COMP_NAME STREQUAL eam)
  string(APPEND CPPDEFS " -DUSE_CBOOL")
endif()
set(CPRE "-WF,-D")
string(APPEND CMAKE_Fortran_FLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo")
string(APPEND CMAKE_Fortran_FLAGS_DEBUG " -qinitauto=7FF7FFFF -qflttrap=ov:zero:inv:en")
string(APPEND CMAKE_Fortran_FORMAT_FIXED_FLAG " -qsuffix=f=f -qfixed=132")
string(APPEND CMAKE_Fortran_FORMAT_FREE_FLAG " -qsuffix=f=f90:cpp=F90")
set(HAS_F2008_CONTIGUOUS "TRUE")
