set(CFLAGS "-g -qfullpath -qmaxmem=-1 -qphsinfo")
if (NOT DEBUG)
  string(APPEND CFLAGS " -O3")
endif()
if (NOT DEBUG AND compile_threaded)
  string(APPEND CFLAGS " -qsmp=omp")
endif()
if (DEBUG AND compile_threaded)
  string(APPEND CFLAGS " -qsmp=omp:noopt")
endif()
set(CXXFLAGS "-g -qfullpath -qmaxmem=-1 -qphsinfo")
if (NOT DEBUG)
  string(APPEND CXXFLAGS " -O2")
endif()
if (NOT DEBUG AND compile_threaded)
  string(APPEND CXXFLAGS " -qsmp=omp")
endif()
if (DEBUG AND compile_threaded)
  string(APPEND CXXFLAGS " -qsmp=omp:noopt")
endif()
string(APPEND CPPDEFS " -DFORTRAN_SAME -DCPRIBM")
if (COMP_NAME STREQUAL eam)
  string(APPEND CPPDEFS " -DUSE_CBOOL")
endif()
set(CPRE "-WF,-D")
set(FC_AUTO_R8 "-qrealsize=8")
set(FFLAGS "-g -qfullpath -qmaxmem=-1 -qphsinfo")
if (NOT DEBUG)
  string(APPEND FFLAGS " -O2 -qstrict -Q")
endif()
if (NOT DEBUG AND compile_threaded)
  string(APPEND FFLAGS " -qsmp=omp")
endif()
if (DEBUG AND compile_threaded)
  string(APPEND FFLAGS " -qsmp=omp:noopt")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -qinitauto=7FF7FFFF -qflttrap=ov:zero:inv:en")
endif()
set(FFLAGS_NOOPT "-O0")
set(FIXEDFLAGS "-qsuffix=f=f -qfixed=132")
set(FREEFLAGS "-qsuffix=f=f90:cpp=F90")
set(HAS_F2008_CONTIGUOUS "TRUE")
