string(APPEND CFLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo")
string(APPEND CXXFLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo")
if (NOT DEBUG)
  string(APPEND CFLAGS " -O3")
  string(APPEND CXXFLAGS " -O2")
  string(APPEND FFLAGS " -O2 -qstrict -Q")
endif()
if (compile_threaded)
  if (DEBUG)
    string(APPEND CFLAGS " -qsmp=omp:noopt")
    string(APPEND CXXFLAGS " -qsmp=omp:noopt")
    string(APPEND FFLAGS " -qsmp=omp:noopt")
  elseif (NOT DEBUG)
    string(APPEND CFLAGS " -qsmp=omp")
    string(APPEND CXXFLAGS " -qsmp=omp")
    string(APPEND FFLAGS " -qsmp=omp")
  endif()
endif()

string(APPEND CPPDEFS " -DFORTRAN_SAME -DCPRIBM")
if (COMP_NAME STREQUAL eam)
  string(APPEND CPPDEFS " -DUSE_CBOOL")
endif()
set(CPRE "-WF,-D")
string(APPEND FC_AUTO_R8 " -qrealsize=8")
string(APPEND FFLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo")
if (DEBUG)
  string(APPEND FFLAGS " -qinitauto=7FF7FFFF -qflttrap=ov:zero:inv:en")
endif()
string(APPEND FFLAGS_NOOPT " -O0")
string(APPEND FIXEDFLAGS " -qsuffix=f=f -qfixed=132")
string(APPEND FREEFLAGS " -qsuffix=f=f90:cpp=F90")
set(HAS_F2008_CONTIGUOUS "TRUE")
