string(APPEND CFLAGS " -qarch=auto -qtune=auto -qcache=auto")
set(CONFIG_SHELL "/usr/bin/bash")
string(APPEND FFLAGS " -qarch=auto -qtune=auto -qcache=auto -qsclk=micro")
if (COMP_NAME STREQUAL eam)
  string(APPEND FFLAGS " -qspill=6000")
endif()
if (DEBUG)
  string(APPEND LDFLAGS " -qsigtrap=xl__trcedump")
endif()
string(APPEND LDFLAGS " -bdatapsize:64K -bstackpsize:64K -btextpsize:32K")
set(MPICC "mpcc_r")
set(MPIFC "mpxlf2003_r")
set(SCC "cc_r")
set(SFC "xlf2003_r")
string(APPEND SLIBS " -lmassv -lessl")
if (NOT DEBUG)
  string(APPEND SLIBS " -lmass")
endif()
