string(APPEND CPPDEFS " -DLINUX")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
string(APPEND CMAKE_Fortran_FLAGS " -qzerosize -qfree=f90 -qxlf2003=polymorphic -qspillsize=2500 -qextname=flush")
if (COMP_NAME STREQUAL cice AND compile_threaded)
  string(APPEND CMAKE_Fortran_FLAGS " -qsmp=omp:noopt")
endif()
string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,--relax -Wl,--allow-multiple-definition")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -lxlopt -lxl -lxlsmp -L$ENV{ESSL_PATH}/lib64 -lessl")
set(MPICC "mpicc")
set(MPICXX "mpiCC")
set(MPIFC "mpif90")
set(PIO_FILESYSTEM_HINTS "gpfs")
set(SCC "xlc_r")
set(SFC "xlf90_r")
set(SCXX "xlc++_r")
string(APPEND KOKKOS_OPTIONS " -DKokkos_ARCH_POWER9=On")
