if (NOT DEBUG AND compile_threaded)
  string(APPEND CFLAGS " -qsmp=omp:nested_par -qsuppress=1520-045")
endif()
if (DEBUG AND compile_threaded)
  string(APPEND CFLAGS " -qsmp=omp:nested_par:noopt -qsuppress=1520-045")
endif()
set(CONFIG_ARGS "--build=powerpc-bgp-linux --host=powerpc64-suse-linux")
string(APPEND CPPDEFS " -DLINUX")
set(FFLAGS "-g -qfullpath -qmaxmem=-1 -qspillsize=2500 -qextname=flush -qphsinfo")
if (NOT DEBUG)
  string(APPEND FFLAGS " -O3 -qstrict -Q")
endif()
if (NOT DEBUG AND compile_threaded)
  string(APPEND FFLAGS " -qsmp=omp:nested_par -qsuppress=1520-045")
endif()
if (DEBUG AND compile_threaded)
  string(APPEND FFLAGS " -qsmp=omp:nested_par:noopt -qsuppress=1520-045")
endif()
set(LDFLAGS "-Wl,--relax -Wl,--allow-multiple-definition")
