string(APPEND CMAKE_C_FLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo")
string(APPEND CMAKE_CXX_FLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo")
string(APPEND CMAKE_Fortran_FLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo -qzerosize -qfree=f90 -qxlf2003=polymorphic -qspillsize=2500 -qextname=flush")
string(APPEND CMAKE_C_FLAGS_RELEASE " -O3")
string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O2")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O2 -qstrict -Q")
if (compile_threaded)
  string(APPEND CMAKE_C_FLAGS_DEBUG " -qsmp=omp:noopt")
  string(APPEND CMAKE_CXX_FLAGS_DEBUG " -qsmp=omp:noopt")
  string(APPEND CMAKE_Fortran_FLAGS_DEBUG " -qsmp=omp:noopt")
  string(APPEND CMAKE_C_FLAGS_RELEASE " -qsmp=omp")
  string(APPEND CMAKE_CXX_FLAGS_RELEASE " -qsmp=omp")
  string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -qsmp=omp")
    if (COMP_NAME STREQUAL cice)
    string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -qsmp=omp:noopt")
    endif()
endif()
string(APPEND CPPDEFS " -DFORTRAN_SAME -DCPRIBM -DLINUX")
if (COMP_NAME STREQUAL eam)
  string(APPEND CPPDEFS " -DUSE_CBOOL")
endif()
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
set(CPRE "-WF,-D")
string(APPEND CMAKE_Fortran_FORMAT_FIXED_FLAG " -qsuffix=f=f -qfixed=132")
string(APPEND CMAKE_Fortran_FORMAT_FREE_FLAG " -qsuffix=f=f90:cpp=F90")
set(HAS_F2008_CONTIGUOUS "TRUE")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,--relax -Wl,--allow-multiple-definition -qsmp -qoffload -lcudart -L$ENV{CUDA_DIR}/lib64")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -lxlopt -lxl -lxlsmp -L$ENV{ESSL_PATH}/lib64 -lessl")
set(MPICC "mpicc")
set(MPICXX "mpiCC")
set(MPIFC "mpif90")
set(PIO_FILESYSTEM_HINTS "gpfs")
set(SCC "xlc_r")
set(SFC "xlf90_r")
set(SCXX "xlc++_r")
string(APPEND KOKKOS_OPTIONS " -DKokkos_ARCH_POWER9=On")
