string(APPEND CFLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo")
string(APPEND CXXFLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo")
string(APPEND FFLAGS " -g -qfullpath -qmaxmem=-1 -qphsinfo -qzerosize -qfree=f90 -qxlf2003=polymorphic -qspillsize=2500 -qextname=flush")
if (NOT DEBUG)
  string(APPEND CFLAGS " -O3")
  string(APPEND CXXFLAGS " -O2")
  string(APPEND FFLAGS " -O2 -qstrict -Q")
endif()
if (compile_threaded)
  if (DEBUG)
    string(APPEND CFLAGS " -qsmp=omp:noopt")
    string(APPEND CXXFLAGS " -qsmp=omp:noopt")
    string(APPEND FFLAGS " -qsmp=omp:noopt")
  elseif (NOT DEBUG)
    string(APPEND CFLAGS " -qsmp=omp")
    string(APPEND CXXFLAGS " -qsmp=omp")
    string(APPEND FFLAGS " -qsmp=omp")
    if (COMP_NAME STREQUAL cice)
      string(APPEND FFLAGS " -qsmp=omp:noopt")
    endif()
  endif()
endif()
string(APPEND CPPDEFS " -DFORTRAN_SAME -DCPRIBM -DLINUX")
if (COMP_NAME STREQUAL eam)
  string(APPEND CPPDEFS " -DUSE_CBOOL")
endif()
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
set(CPRE "-WF,-D")
string(APPEND FC_AUTO_R8 " -qrealsize=8")
string(APPEND FFLAGS_NOOPT " -O0")
string(APPEND FIXEDFLAGS " -qsuffix=f=f -qfixed=132")
string(APPEND FREEFLAGS " -qsuffix=f=f90:cpp=F90")
set(HAS_F2008_CONTIGUOUS "TRUE")
string(APPEND LDFLAGS " -Wl,--relax -Wl,--allow-multiple-definition -qsmp -qoffload -lcudart -L$ENV{CUDA_DIR}/lib64")
string(APPEND SLIBS " -L$ENV{PNETCDF_PATH}/lib -lpnetcdf -L$ENV{HDF5_PATH}/lib -lhdf5_hl -lhdf5 -lxlopt -lxl -lxlsmp -L$ENV{NETCDF_C_PATH}/lib -lnetcdf -L$ENV{NETCDF_FORTRAN_PATH}/lib -lnetcdff -L$ENV{ESSL_PATH}/lib64 -lessl -L$ENV{OLCF_NETLIB_LAPACK_ROOT}/lib64 -llapack")
string(APPEND CXX_LIBS " -lstdc++ -L$ENV{OLCF_XLC_ROOT}/lib -libmc++")
set(MPICC "mpicc")
set(MPICXX "mpiCC")
set(MPIFC "mpif90")
set(PIO_FILESYSTEM_HINTS "gpfs")
set(SCC "xlc_r")
set(SFC "xlf90_r")
set(SCXX "xlc++_r")
set(NETCDF_C_PATH "$ENV{NETCDF_C_PATH}")
set(NETCDF_FORTRAN_PATH "$ENV{NETCDF_FORTRAN_PATH}")
set(PNETCDF_PATH "$ENV{PNETCDF_PATH}")
set(SUPPORTS_CXX "TRUE")
set(KOKKOS_OPTIONS "--arch=Power9 --with-serial")
