string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL")
string(APPEND CMAKE_C_FLAGS " -xCORE_AVX512 -mkl -std=gnu99")
string(APPEND CMAKE_C_FLAGS_RELEASE " -O3 -g -debug minimal")
string(APPEND CMAKE_C_FLAGS_DEBUG " -O0 -g")
string(APPEND CMAKE_CXX_FLAGS " -xCORE_AVX512 -mkl")
string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O3 -g -debug minimal")
string(APPEND CMAKE_CXX_FLAGS_DEBUG " -O0 -g")
if (compile_threaded)
  string(APPEND CMAKE_CXX_FLAGS " -qopenmp")
endif()
string(APPEND CMAKE_Fortran_FLAGS " -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -xCORE_AVX512 -mkl")
if (compile_threaded)
  string(APPEND CMAKE_Fortran_FLAGS " -qopenmp")
endif()
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O3 -g -debug minimal")
string(APPEND CMAKE_Fortran_FLAGS_DEBUG " -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -lstdc++")
if (compile_threaded)
  string(APPEND CMAKE_EXE_LINKER_FLAGS " -qopenmp")
endif()
string(APPEND CMAKE_Fortran_FORMAT_FIXED_FLAG " -fixed -132")
string(APPEND CMAKE_Fortran_FORMAT_FREE_FLAG " -free")
set(HAS_F2008_CONTIGUOUS "TRUE")
set(SFC "ifort")
set(SCC "icc")
set(SCXX "icpc")
