set(PIO_FILESYSTEM_HINTS "lustre")
if (MPILIB STREQUAL impi)
  set(MPICC "mpiicc")
  set(MPICXX "mpiicpc")
  set(MPIFC "mpiifort")
endif()
if (NOT MPILIB STREQUAL impi)
  set(MPICXX "mpic++")
endif()
string(APPEND SLIBS " -lpthread")
set(BLA_VENDOR Intel10_64_dyn)
string(APPEND CXX_LIBS " -lstdc++")
