string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL")
string(APPEND CFLAGS " -xCORE_AVX512 -mkl -std=gnu99")
if (NOT DEBUG)
  string(APPEND CFLAGS " -O3 -g -debug minimal")
endif()
if (DEBUG)
  string(APPEND CFLAGS " -O0 -g")
endif()
string(APPEND CXXFLAGS " -xCORE_AVX512 -mkl")
if (NOT DEBUG)
  string(APPEND CXXFLAGS " -O3 -g -debug minimal")
endif()
if (DEBUG)
  string(APPEND CXXFLAGS " -O0 -g")
endif()
if (compile_threaded)
  string(APPEND CXXFLAGS " -qopenmp")
endif()
string(APPEND FFLAGS " -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -xCORE_AVX512 -mkl")
if (compile_threaded)
  string(APPEND FFLAGS " -qopenmp")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -O3 -g -debug minimal")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
endif()
string(APPEND LDFLAGS " -lstdc++")
if (compile_threaded)
  string(APPEND LDFLAGS " -qopenmp")
endif()
string(APPEND FIXEDFLAGS " -fixed -132")
string(APPEND FREEFLAGS " -free")
set(HAS_F2008_CONTIGUOUS "TRUE")
string(APPEND FC_AUTO_R8 " -r8")
set(SFC "ifort")
set(SCC "icc")
set(SCXX "icpc")
set(CXX_LINKER "FORTRAN")
string(APPEND CXX_LDFLAGS " -cxxlib")
set(SUPPORTS_CXX "TRUE")
