if (compile_threaded)
  string(APPEND CFLAGS " -static-intel")
endif()
if (compile_threaded AND DEBUG)
  string(APPEND CFLAGS " -heap-arrays")
endif()
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -qno-opt-dynamic-align")
endif()
if (compile_threaded)
  string(APPEND FFLAGS " -static-intel")
endif()
if (compile_threaded AND DEBUG)
  string(APPEND FFLAGS " -heap-arrays")
endif()
if (compile_threaded)
  string(APPEND FFLAGS_NOOPT " -static-intel")
  string(APPEND LDFLAGS " -static-intel")
endif()
if (MPILIB STREQUAL impi)
  set(MPICC "mpiicc")
  set(MPICXX "mpiicpc")
  set(MPIFC "mpiifort")
endif()
set(PIO_FILESYSTEM_HINTS "gpfs")
