if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
string(APPEND CFLAGS " -static-intel")
string(APPEND CFLAGS " -march=core-avx2")
if (NOT DEBUG)
  string(APPEND CFLAGS " -O3")
endif()
string(APPEND CXXFLAGS " -static-intel")
string(APPEND CXXFLAGS " -axCORE-AVX2")
if (NOT DEBUG)
  string(APPEND CXXFLAGS " -O3")
endif()
string(APPEND FFLAGS " -static-intel")
string(APPEND FFLAGS " -axCORE-AVX2")
if (NOT DEBUG)
  string(APPEND FFLAGS " -O3 -qno-opt-dynamic-align")
endif()
set(PIO_FILESYSTEM_HINTS "gpfs")
string(APPEND LDFLAGS " -static-intel")
if (MPILIB STREQUAL impi)
  set(MPICC "mpiicc")
  set(MPICXX "mpiicpc")
  set(MPIFC "mpiifort")
endif()
string(APPEND KOKKOS_OPTIONS " -DKokkos_ARCH_ZEN2=On")
if (compile_threaded)
  string(APPEND KOKKOS_OPTIONS " -DKokkos_ENABLE_AGGRESSIVE_VECTORIZATION=On")
endif()
