string(APPEND CPPDEFS " -DLINUX")
if (DEBUG)
  string(APPEND FFLAGS " -check all -ftrapuv -init=snan")
endif()
set(PIO_FILESYSTEM_HINTS "lustre")
set(BLA_VENDOR Intel10_64_dyn)
string(APPEND SLIBS " -lpmi")
