set(ALBANY_PATH "/projects/ccsm/AlbanyTrilinos_20190904/albany-build/install")
set(CLDERA_PATH "/projects/cldera/cldera-tools/install-master/intel/")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
set(ESMF_LIBDIR "/projects/ccsm/esmf-6.3.0rp1/lib/libO/Linux.intel.64.openmpi.default")
set(PIO_FILESYSTEM_HINTS "lustre")
