if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
string(APPEND CFLAGS " -static-intel")
string(APPEND CFLAGS " -march=core-avx2")
if (NOT DEBUG)
  string(APPEND CFLAGS " -O3")
endif()
string(APPEND CXXFLAGS " -static-intel")
string(APPEND CXXFLAGS " -axCORE-AVX2")
if (NOT DEBUG)
  string(APPEND CXXFLAGS " -O3")
endif()
string(APPEND FFLAGS " -static-intel")
string(APPEND FFLAGS " -axCORE-AVX2")
if (NOT DEBUG)
  string(APPEND FFLAGS " -O3 -qno-opt-dynamic-align")
endif()
set(PIO_FILESYSTEM_HINTS "gpfs")
set(MOAB_PATH "/lcrc/soft/climate/moab/chrysalis/intelSep22")
string(APPEND SLIBS " -mkl")
string(APPEND LDFLAGS " -static-intel")
if (MPILIB STREQUAL impi)
  set(MPICC "mpiicc")
  set(MPICXX "mpiicpc")
  set(MPIFC "mpiifort")
endif()
