if (compile_threaded)
  string(APPEND CMAKE_C_FLAGS   " -qopenmp")
  string(APPEND CMAKE_Fortran_FLAGS   " -qopenmp")
  string(APPEND CMAKE_CXX_FLAGS " -qopenmp")
  string(APPEND CMAKE_EXE_LINKER_FLAGS  " -qopenmp")
endif()
string(APPEND CMAKE_C_FLAGS         " -fp-model precise")
string(APPEND CMAKE_C_FLAGS_RELEASE " -O2 -debug minimal")
string(APPEND CMAKE_C_FLAGS_DEBUG   " -O0 -g")

# EAMxx ignores generic CMAKE_CXX_FLAGS, includes CMAKE_CXX_FLAGS_[RELEASE,DEBUG]
string(APPEND CMAKE_CXX_FLAGS         " -fp-model precise")
string(APPEND CMAKE_CXX_FLAGS_RELEASE " -fp-model precise -O2 -debug minimal")
string(APPEND CMAKE_CXX_FLAGS_DEBUG   " -O0 -g")

string(APPEND CMAKE_Fortran_FLAGS " -traceback -convert big_endian -assume byterecl -ftz -assume realloc_lhs -fp-model source")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O2 -debug minimal")
string(APPEND CMAKE_Fortran_FLAGS_DEBUG   " -O0 -g -check bounds -check pointers -check noarg_temp_created")

string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRINTEL -DHAVE_SLASHPROC -DHIDE_MPI")
string(APPEND CMAKE_Fortran_FORMAT_FIXED_FLAG " -fixed -132")
string(APPEND CMAKE_Fortran_FORMAT_FREE_FLAG " -free")
set(HAS_F2008_CONTIGUOUS "TRUE")
set(MPIFC "mpifort")
set(MPICC "mpicc")
set(MPICXX "mpicxx")
set(SCC "icx")
set(SCXX "icpx")
set(SFC "ifx")
set(E3SM_LINK_WITH_FORTRAN "TRUE")

if (COMP_NAME STREQUAL gcam)
  string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,--no-relax")
  string(APPEND CMAKE_Fortran_FLAGS " -mcmodel=medium")
  string(APPEND CMAKE_C_FLAGS " -mcmodel=medium")
  string(APPEND CMAKE_CXX_FLAGS " -DNDEBUG")
endif()

