string(APPEND CFLAGS " -O2 -I/soft/intel/x86_64/2013/composer_xe_2013/composer_xe_2013_sp1.3.174/mkl/include")
if (compile_threaded)
  string(APPEND CFLAGS " -openmp")
endif()
string(APPEND FFLAGS " -I/soft/intel/x86_64/2013/composer_xe_2013/composer_xe_2013_sp1.3.174/mkl/include")
if (compile_threaded)
  string(APPEND FFLAGS " -openmp")
  string(APPEND LDFLAGS " -openmp")
endif()
set(MPICC "mpiicc")
set(MPICXX "mpiicpc")
set(MPIFC "mpiifort")
string(APPEND SLIBS " -openmp -fPIC -lpthread -lm")
