string(APPEND FFLAGS " -fp-model consistent -fimf-use-svml")
string(APPEND CXXFLAGS " -fp-model consistent")
if (NOT DEBUG)
  string(APPEND FFLAGS " -qno-opt-dynamic-align")
endif()
set(BLA_VENDOR Intel10_64_dyn)
string(APPEND SLIBS " -lpthread")
