set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "nvcc")
set(SCXX "nvc++")
set(SFC "nvfortran")
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRNVIDIA")
string(APPEND CMAKE_C_FLAGS_RELEASE " -O0 -Mnofma -Mvect=nosimd")
string(APPEND CMAKE_C_FLAGS_DEBUG " -g")
string(APPEND CMAKE_Fortran_FLAGS " -i4 -Mstack_arrays  -Mextend -byteswapio -Mflushz -Kieee -DHAVE_IEEE_ARITHMETIC -Mallocatable=03 -DNO_R16 -traceback")
string(APPEND CMAKE_Fortran_FLAGS_DEBUG " -O0 -g -Ktrap=fp -Mbounds -Kieee")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O1")
string(APPEND CMAKE_CXX_FLAGS_DEBUG " -g -O0 -Mnofma -Wall -Kieee -traceback")
string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O2")
if (compile_threaded)
  string(APPEND CMAKE_Fortran_FLAGS " -mp")
  string(APPEND CMAKE_C_FLAGS " -mp")
  string(APPEND CMAKE_CXX_FLAGS " -mp")
  string(APPEND CMAKE_EXE_LINKER_FLAGS " -mp")
endif()
string(APPEND CMAKE_Fortran_FORMAT_FIXED_FLAG " -Mfixed")
string(APPEND CMAKE_Fortran_FORMAT_FREE_FLAG " -Mfree")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,--allow-multiple-definition -lstdc++")
set(E3SM_LINK_WITH_FORTRAN "TRUE")

