if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -qno-opt-dynamic-align")
set(PIO_FILESYSTEM_HINTS "gpfs")
if (MPILIB STREQUAL impi)
  set(MPICC  "mpiicx")
  set(MPICXX "mpiicpx")
  set(MPIFC  "mpiifx")
endif()
