if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
if (NOT DEBUG)
  string(APPEND CFLAGS   " -O3")
  string(APPEND CXXFLAGS " -O3")
  string(APPEND FFLAGS   " -O3 -qno-opt-dynamic-align")
endif()
set(PIO_FILESYSTEM_HINTS "gpfs")
if (MPILIB STREQUAL impi)
  set(MPICC "mpiicx")
  set(MPICXX "mpiicpx")
  set(MPIFC "mpiifx")
endif()
