if (compile_threaded)
  string(APPEND CFLAGS " -mp")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRPATHSCALE")
string(APPEND FC_AUTO_R8 " -r8")
string(APPEND FFLAGS " -O -extend_source -ftpp -fno-second-underscore -funderscoring -byteswapio")
if (compile_threaded)
  string(APPEND FFLAGS " -mp")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -g -trapuv -Wuninitialized")
endif()
string(APPEND FFLAGS_NOOPT " -O0")
set(HAS_F2008_CONTIGUOUS "FALSE")
if (compile_threaded)
  string(APPEND LDFLAGS " -mp")
endif()
set(MPICC "mpicc")
set(MPIFC "mpif90")
