string(APPEND CFLAGS " -time")
if (compile_threaded)
  string(APPEND CFLAGS " -mp")
endif()
string(APPEND CXXFLAGS " -time -std=c++14")
if (compile_threaded)
  string(APPEND CXXFLAGS " -mp")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_SHR_VMATH -DNO_R16 -DCPRPGI")
set(CXX_LINKER "CXX")
string(APPEND FC_AUTO_R8 " -r8")
string(APPEND FFLAGS " -i4 -time -Mstack_arrays  -Mextend -byteswapio -Mflushz -Kieee -Mallocatable=03")
if (compile_threaded)
  string(APPEND FFLAGS " -mp")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -O0 -g -Ktrap=fp -Mbounds")
endif()
if (COMP_NAME STREQUAL datm)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (COMP_NAME STREQUAL dlnd)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (COMP_NAME STREQUAL drof)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (COMP_NAME STREQUAL dwav)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (COMP_NAME STREQUAL dice)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (COMP_NAME STREQUAL docn)
  string(APPEND FFLAGS " -Mnovect")
endif()
string(APPEND FFLAGS_NOOPT " -O0")
string(APPEND FIXEDFLAGS " -Mfixed")
string(APPEND FREEFLAGS " -Mfree")
set(HAS_F2008_CONTIGUOUS "FALSE")
string(APPEND LDFLAGS " -time -Wl,--allow-multiple-definition")
if (compile_threaded)
  string(APPEND LDFLAGS " -mp")
endif()
set(MPICC "mpicc")
set(MPICXX "mpicxx")
set(MPIFC "mpif90")
set(SCC "pgcc")
set(SCXX "pgc++")
set(SFC "pgf95")
