if (NOT DEBUG)
  string(APPEND CFLAGS " -O2")
endif()
string(APPEND CPPDEFS " -DLINUX")
if (NOT DEBUG)
  string(APPEND FFLAGS " -O2")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -traceback  -fpe0 -check  all -check noarg_temp_created -ftrapuv")
  string(APPEND FFLAGS " -C -Mchkfpstk -Mchkstk -Mdalign  -Mdepchk -Miomutex -Mrecursive -Meh_frame")
endif()
set(PIO_FILESYSTEM_HINTS "lustre")
string(APPEND SLIBS " -lpmi -L$ENV{MPI_LIB} -lmpich")
