if (MPILIB STREQUAL "mpich")
  string(APPEND CONFIG_ARGS " --host=cray")
endif()
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_NANOTIME -DBIT64 -DHAVE_SLASHPROC -DHAVE_GETTIMEOFDAY")
endif()
string(APPEND CMAKE_C_FLAGS_RELEASE " -O2 -g")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O2 -g")

if (MPILIB STREQUAL "mpich")
  set(MPICC "cc")
  set(MPICXX "CC")
  set(MPIFC "ftn")
else()
  set(MPICC "mpicc")
  set(MPICXX "mpicxx")
  set(MPIFC "mpifort")
  set(NetCDF_C_PATH "$ENV{NETCDF_PATH}" CACHE FILEPATH "" FORCE)
  set(NetCDF_Fortran_PATH "$ENV{NETCDF_PATH}" CACHE FILEPATH "" FORCE)
  set(BLA_VENDOR Cray CACHE STRING "")
  set(BLAS_LIBRARIES "$ENV{CRAY_LIBSCI_PREFIX_DIR}/lib/libsci_gnu.so" CACHE STRING "" FORCE)
  set(LAPACK_LIBRARIES "$ENV{CRAY_LIBSCI_PREFIX_DIR}/lib/libsci_gnu.so" CACHE STRING "" FORCE)
endif()
set(SCC "gcc")
set(SCXX "g++")
set(SFC "gfortran")
