string(APPEND CONFIG_ARGS " --host=cray")

set(MPICC "mpicc")
set(MPICXX "mpicxx")
set(MPIFC "mpifort")
set(SCC "gcc")
set(SCXX "g++")
set(SFC "gfortran")

if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_NANOTIME -DBIT64 -DHAVE_VPRINTF -DHAVE_BACKTRACE -DHAVE_SLASHPROC -DHAVE_COMM_F2C -DHAVE_TIMES -DHAVE_GETTIMEOFDAY")
endif()

string(APPEND CMAKE_EXE_LINKER_FLAGS " -lxpmem -L$ENV{CRAY_MPICH_ROOTDIR}/gtl/lib -lmpi_gtl_hsa -Wl,-rpath,$ENV{CRAY_MPICH_ROOTDIR}/gtl/lib")

# Need to look into using _APU
string(APPEND KOKKOS_OPTIONS " -DKokkos_ENABLE_HIP=ON -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=OFF -DKokkos_ARCH_ZEN4=ON -DKokkos_ARCH_AMD_GFX942=OFF -DKokkos_ARCH_AMD_GFX942_APU=OFF")

string(APPEND CMAKE_HIP_FLAGS "${CXXFLAGS} -O2 -munsafe-fp-atomics")

string(APPEND CMAKE_C_FLAGS_RELEASE " -O2")
string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O2")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O2")

set(PIO_FILESYSTEM_HINTS "lustre")
