# anlworkstation

SET (CMAKE_Fortran_COMPILER mpif90 CACHE FILEPATH "")
SET (CMAKE_C_COMPILER mpicc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER mpicxx CACHE FILEPATH "")

#SET (CMAKE_Fortran_FLAGS "-WF,-C! -O2 -Ipreqx_modules" CACHE STRING "")
#SET (FORCE_Fortran_FLAGS "-WF,-C!" CACHE STRING "")
SET (ENABLE_OPENMP TRUE CACHE BOOL "")

SET (PNETCDF_DIR $ENV{PNETCDF_PATH} CACHE FILEPATH "")
SET (NETCDF_DIR $ENV{NETCDF_PATH} CACHE FILEPATH "")
SET (ENV{HDF5} $ENV{HDF5_PATH} CACHE FILEPATH "")
SET (CPRNC_DIR /home/climate1/acme/cprnc/build CACHE FILEPATH "")

SET (USE_QUEUING FALSE CACHE BOOL "")
SET (USE_MPIEXEC mpiexec CACHE FILEPATH "")

SET (HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")
SET (ENV{PATH} "$ENV{NETCDF_PATH}:$ENV{PATH}")
SET (ENV{LD_LIBRARY_PATH} "$ENV{HDF5_PATH}/lib:$ENV{LD_LIBRARY_PATH}")

SET (BUILD_HOMME_SWEQX FALSE CACHE BOOL "")
