# CMake initial cache file for cab
SET (CMAKE_Fortran_COMPILER mpif90 CACHE FILEPATH "")
SET (CMAKE_C_COMPILER mpicc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER mpicxx CACHE FILEPATH "")

SET (DEBUG_FLAGS " " CACHE STRING "")

SET (HOMME_USE_MKL "TRUE" CACHE FILEPATH "") # for Intel

SET (NETCDF_DIR $ENV{NETCDF} CACHE FILEPATH "")
SET (HDF5_DIR $ENV{HDF5} CACHE FILEPATH "")
SET (HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")
SET (USE_MPIEXEC "srun" CACHE STRING "")

#Regression test parameters
SET (USE_QUEUING FALSE CACHE BOOL "")


