# CMake initial cache file for LC machines
SET (CMAKE_Fortran_COMPILER $ENV{MPIF90} CACHE FILEPATH "")
SET (CMAKE_C_COMPILER $ENV{MPICC} CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER $ENV{MPICXX} CACHE FILEPATH "")

SET (OPT_FLAGS "-O0" CACHE STRING "")
SET (DEBUG_FLAGS "-g" CACHE STRING "")
#SET (DEBUG_FFLAGS "-g -traceback -ftrapuv -fpe0 -check bounds,uninit" CACHE STRING "")

SET (NETCDF_DIR $ENV{NETCDF} CACHE FILEPATH "")
SET (WITH_PNETCDF FALSE CACHE BOOL "")
SET (HDF5_DIR $ENV{HDF5} CACHE FILEPATH "")
SET (HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")
SET (ENABLE_OPENMP FALSE CACHE BOOL "")
SET (SUNDIALS_DIR $ENV{SUNDIALS} CACHE FILEPATH "")

SET (HOMME_PROJID "climalg" CACHE STRING "")
