# CMake initial cache file for Linux 64bit RHEL6/CENTOS6
# tested with stock gcc/gfortran & openmpi
#
SET (CMAKE_Fortran_COMPILER mpif90 CACHE FILEPATH "")
SET (CMAKE_C_COMPILER mpicc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER mpicxx CACHE FILEPATH "")



EXECUTE_PROCESS(COMMAND pnetcdf-config --prefix
  RESULT_VARIABLE PNCCONFIG_RESULT
  OUTPUT_VARIABLE PNCCONFIG_OUTPUT
  ERROR_VARIABLE  PNCCONFIG_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
SET (PnetCDF_PATH "${PNCCONFIG_OUTPUT}" CACHE STRING "")

EXECUTE_PROCESS(COMMAND nf-config --prefix
  RESULT_VARIABLE NFCONFIG_RESULT
  OUTPUT_VARIABLE NFCONFIG_OUTPUT
  ERROR_VARIABLE  NFCONFIG_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
SET (NetCDF_Fortran_PATH "${NFCONFIG_OUTPUT}" CACHE STRING "")

EXECUTE_PROCESS(COMMAND nc-config --prefix
  RESULT_VARIABLE NCCONFIG_RESULT
  OUTPUT_VARIABLE NCCONFIG_OUTPUT
  ERROR_VARIABLE  NCCONFIG_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
SET (NetCDF_C_PATH "${NCCONFIG_OUTPUT}" CACHE STRING "")






#SET (WITH_PNETCDF FALSE CACHE FILEPATH "")
#SET (NETCDF_DIR $ENV{NETCDF_FORTRAN_ROOT} CACHE FILEPATH "")
#SET (NetCDF_C_PATH "$ENV${NETCDF_C_PATH}" CACHE STRING "")
#SET (PNETCDF_DIR $ENV{PNETCDF_PATH} CACHE FILEPATH "")
#SET (HDF5_DIR $ENV{SEMS_HDF5_ROOT} CACHE FILEPATH "")
#SET (ZLIB_DIR $ENV{SEMS_ZLIB_ROOT} CACHE FILEPATH "")

SET (CPRNC_DIR /sems-data-store/ACME/mappy/cprnc CACHE FILEPATH "")

SET (USE_QUEUING FALSE CACHE BOOL "")
SET (HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")

SET (USE_MPI_OPTIONS "-mca btl tcp,self --bind-to core:overload-allowed " CACHE FILEPATH "")
