# CMake initial cache file for Linux 64bit RHEL6/CENTOS6
# tested with stock gcc/gfortran & openmpi
#
SET (CMAKE_Fortran_COMPILER mpif90 CACHE FILEPATH "")
SET (CMAKE_C_COMPILER mpicc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER mpicxx CACHE FILEPATH "")

SET (WITH_PNETCDF FALSE CACHE FILEPATH "")

SET (NetCDF_Fortran_PATH "$ENV{NETCDF_FORTRAN_ROOT}" CACHE STRING "" FORCE)
SET (NetCDF_C_PATH "$ENV{NETCDF_C_ROOT}" CACHE STRING "" FORCE)

SET (CPRNC_DIR /sems-data-store/ACME/mappy/cprnc CACHE FILEPATH "")

SET (USE_QUEUING FALSE CACHE BOOL "")
SET (HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")

SET(USE_MPIEXEC "srun" CACHE STRING "")
SET(USE_MPI_OPTIONS "--cpu-bind=cores" CACHE STRING "")
