# CMake initial cache file for titan
SET (CMAKE_Fortran_COMPILER ftn CACHE FILEPATH "")
SET (ADD_Fortran_FLAGS "-Mstack_arrays " CACHE STRING "")

SET (CMAKE_C_COMPILER cc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER CC CACHE FILEPATH "")
SET (NETCDF_DIR $ENV{NETCDF_DIR} CACHE FILEPATH "")
SET (PNETCDF_DIR $ENV{PARALLEL_NETCDF_DIR} CACHE FILEPATH "")
SET (HDF5_DIR $ENV{HDF5_DIR} CACHE FILEPATH "")
SET (DEBUG_FLAGS " " CACHE STRING "")
SET (Netcdf_NC_CONFIG_BIN "/opt/cray/netcdf/4.3.3.1/bin" CACHE FILEPATH "")
SET (HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")
SET (USE_MPIEXEC "aprun" CACHE STRING "")

# The following is required for cross compilation
SET (CMAKE_SYSTEM_NAME Catamount CACHE FILEPATH "")

#Regression test parameters
SET (USE_QUEUING FALSE CACHE BOOL "")
SET (USE_NUM_PROCS 64 CACHE STRING "")


