# CMake initial cache file for titan
SET (CMAKE_Fortran_COMPILER ftn CACHE FILEPATH "")
SET (ADD_Fortran_FLAGS "-Mstack_arrays " CACHE STRING "")

SET (CMAKE_C_COMPILER cc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER CC CACHE FILEPATH "")
SET (NETCDF_DIR $ENV{NETCDF_DIR} CACHE FILEPATH "")
SET (PNETCDF_DIR $ENV{PARALLEL_NETCDF_DIR} CACHE FILEPATH "")
SET (HDF5_DIR $ENV{HDF5_DIR} CACHE FILEPATH "")

# The following is required for cross compilation
SET (CMAKE_SYSTEM_NAME Catamount CACHE FILEPATH "")
SET (USE_QUEUING FALSE CACHE BOOL "")

SET (ENABLE_CUDA_FORTRAN TRUE CACHE BOOL "")
SET (CUDA_VERSION 5.0 CACHE BOOL "")
SET (CUDA_DEVICE_CAPABILITY cc3x CACHE BOOL "")
SET (CMAKE_EXE_LINKER_FLAGS "-lcudafor4"  CACHE BOOL "")

