# CMake initial cache file for yellowstone pgi
SET (CMAKE_Fortran_COMPILER mpipf90 CACHE FILEPATH "")
SET (CMAKE_C_COMPILER mpipcc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER mpipCC CACHE FILEPATH "")
SET (NETCDF_DIR $ENV{NETCDF} CACHE FILEPATH "")
SET (PNETCDF_DIR $ENV{PNETCDF} CACHE FILEPATH "")
SET (PREFER_SHARED TRUE CACHE FILEPATH "")
