version: 2

updates:

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
    assignees:
      - "bartgol"
    reviewers:
      - "mahf708"
