version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "rljacob"
    reviewers:
      - "mahf708"
      - "bartgol"
    labels:
      - "AT: Integrate Without Testing"
