!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Math and Computer Science Division, Argonne National Laboratory   !
!BOP -------------------------------------------------------------------
!
! !MODULE: m_GeneralGrid -- Sparse Matrix class and methods.
!
! !DESCRIPTION:
! The GeneralGrid data type is a special case of the  AttrVect data 
! type (see m_AttrVect for details).  This data type has two storage 
! arrays, one for integer attributes (GeneralGrid\%iAttr) to hold 
! indexing information ({\em e.g.}, indices for each dimension if the
! grid was generated by a Cartesian product, or "unraveled" indices if
! a multidimensional grid is being represented as a vector), and one 
! for real attributes (GeneralGrid\%rAttr) which holds the coordinates
! of each point on the grid.
!
! The set of attributes in each storage array are defined by a List; 
! {\tt GeneralGrid\%iList} for integer attributes, and 
! {\tt GeneralGrid\%rList} ! for real attributes (that is, the coordinates).
!
! !INTERFACE:

 module m_GeneralGrid
!
! !USES:
!
      use m_AttrVect, only : AttrVect
      use m_AttrVect, only : AttrVect_init => init

      implicit none

      private   ! except

      public :: GeneralGrid    ! The class data structure
      public :: init           ! Create a GeneralGrid
      public :: clean          ! Destroy a GeneralGrid

    interface init  ; module procedure init_  ; end interface
    interface clean ; module procedure clean_ ; end interface

! !REVISION HISTORY:
!       25Sep00 - J.W. Larson <larson@mcs.anl.gov> - initial prototype
!       31Oct00 - J.W. Larson <larson@mcs.anl.gov> - modified the
!                 GeneralGrid type to allow inclusion of grid cell
!                 dimensions (lengths) and area/volume weights.
!EOP ___________________________________________________________________

  character(len=*),parameter :: myname='m_GeneralGrid'


 contains

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Math and Computer Science Division, Argonne National Laboratory   !
!BOP -------------------------------------------------------------------
!
! !IROUTINE: init_ - initialize a GeneralGrid
!
! !DESCRIPTION:
!
! !INTERFACE:

 subroutine init_(sGrid, lsize )
!
! !USES:
!
      use m_AttrVect, only : AttrVect_init => init
      use m_die

      implicit none

      type(GeneralGrid), intent(out)         :: sGrid
      integer,         optional,intent(in)   :: lsize

! !REVISION HISTORY:
!       25Sep00 - Jay Larson <larson@mcs.anl.gov> - initial prototype
!EOP ___________________________________________________________________
!
  character(len=*),parameter :: myname_=myname//'::init_'

  integer :: n

        ! if lsize is present, use it to set n; if not, set n=0

  n = 0
  if(present(lsize)) n=lsize


        ! Initialize sMat using AttrVect_init

  call AttrVect_init(sGrid, GeneralGrid_iList, GeneralGrid_rList, n)

 end subroutine init_

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Math and Computer Science Division, Argonne National Laboratory   !
!BOP -------------------------------------------------------------------
!
! !IROUTINE: clean_ - Destroy a GeneralGrid.
!
! !DESCRIPTION:
!
! !INTERFACE:

    subroutine clean_(sGrid)
!
! !USES:
!
      use m_AttrVect,only : AttrVect_clean => clean

      implicit none

      type(GeneralGrid), intent(inout) :: sGrid

! !REVISION HISTORY:
!       25Sep00 - J.W. Larson <larson@mcs.anl.gov> - initial prototype
!EOP ___________________________________________________________________

  character(len=*),parameter :: myname_=myname//'::clean_'

  call AttrVect_clean(sGrid)

 end subroutine clean_

 end module m_GeneralGrid

