#!/usr/bin/env csh -f 
#===============================================================================
# Automatically generated module settings for eastwind
# DO NOT EDIT THIS FILE DIRECTLY!  Please edit env_mach_specific.xml 
# in your CASEROOT
#===============================================================================

source /etc/profile.d/modules.csh
module purge 
module load pgi/11.3
module load mpi/mvapich2/1.5.1p1/pgi11.3
module load netcdf/4.1.2/pgi
