#!/usr/bin/env sh -f 
#===============================================================================
# Automatically generated module settings for mira
# DO NOT EDIT THIS FILE DIRECTLY!  Please edit env_mach_specific.xml 
# in your CASEROOT. This file is overwritten every time modules are loaded!
#===============================================================================

.  /etc/profile.d/00softenv.sh
CIME_REPO=`./xmlquery CIME_REPOTAG -value`
if [ -n $CIME_REPO  ]
then 
  COMPILER=`./xmlquery  COMPILER          -value`
  MPILIB=`./xmlquery  MPILIB        -value`
  DEBUG=`./xmlquery  DEBUG         -value`
  OS=`./xmlquery  OS        -value`
  PROFILE_PAPI_ENABLE=`./xmlquery  PROFILE_PAPI_ENABLE -value`
fi
soft add +mpiwrapper-xl 
soft add @ibm-compilers-2015-02 
soft add +cmake 
soft add +python 
export MPI_TYPE_MAX=$MPI_TYPE_MAX
export OMP_DYNAMIC=$OMP_DYNAMIC
