MACRO (GET_MPI_DISTRIBUTION_NAME MPI_DISTRO_NAME)

  execute_process(COMMAND ${CMAKE_CXX_COMPILER} 
                  ${CMAKE_SOURCE_DIR}/cmake/TryCompileOpenMPI.cpp
                  RESULT_VARIABLE HAVE_OPENMPI_MPI)

  IF (NOT HAVE_OPENMPI_MPI)
    SET (MPI_CXX_BACK_END_COMPILER_VAR_NAME  OMPI_CXX)
    SET (MPI_DISTRO_NAME "OPENMPI")
  ELSE ()
    execute_process(COMMAND ${CMAKE_CXX_COMPILER} 
                    ${CMAKE_SOURCE_DIR}/cmake/TryCompileMPICH.cpp
                    RESULT_VARIABLE HAVE_MPICH_MPI)

    IF (HAVE_MPICH_MPI)
      SET (MPI_DISTRO_NAME "MPICH")
      SET (MPI_CXX_BACK_END_COMPILER_VAR_NAME MPICH_CXX)
    ELSE ()
      SET (MPI_DISTRO_NAME "NOT-FOUND")
      SET (MPICXX_BACK_END_COMPILER_VAR_NAME MPI_CXX_BACK_END_COMPILER_VAR_NAME)
    ENDIF()
  ENDIF()
ENDMACRO()
