module esmfshr_mod
#ifdef USE_ESMF_LIB

! Author: Fei Liu

use esmf2mct_mod
use mct2esmf_mod
use esmfshr_util_mod
use esmfshr_infodata_mod

implicit none

private

public esmf2mct_init
public esmf2mct_copy
public mct2esmf_init
public mct2esmf_copy
public mct2esmf_create
public esmfshr_util_ArrayGetIndex
public esmfshr_util_ArrayGetName
public esmfshr_util_ArrayGetSize
public esmfshr_util_ArrayGetField
public esmfshr_util_ArrayPutField
public esmfshr_util_DistgridCreate
public esmfshr_util_StateArrayDestroy
public esmfshr_util_StateADistgridDestroy
public esmfshr_util_CheckRC
public esmfshr_util_ArrayCopy
public esmfshr_util_ArraySum
public esmfshr_util_ArrayZero
public esmfshr_util_ArrayAvg
public esmfshr_infodata_infodata2state
public esmfshr_infodata_state2infodata

#endif
end module
