case_id = 'set5_ANN_PRECT_GPCP'
reference_data_path = '/space1/test_data/obs_for_diagnostics/'
test_data_path = '/space/golaz1/ACME_simulations/20160520.A_WCYCL1850.ne30_oEC.edison.alpha6_01/pp/clim_rgr/0070-0099/'
#reference_data_path = '/Users/shaheen2/github/acme_diags/acme_diags/'
#test_data_path = '/Users/shaheen2/github/acme_diags/acme_diags/'
reference_data_set = 'GPCP_ANN_climo.nc'  # observation
test_data_set = '20160520.A_WCYCL1850.ne30_oEC.edison.alpha6_01_ANN_climo.nc'  # model
variables = 'PRECT'
season = 'ANN'
output_file = 'test.png'
