#!/usr/bin/env bash

# Run genf90 on all files that need it in this directory

genf90=../../../../../../../../tools/cprnc/genf90/genf90.pl

for fl in *.in; do
    echo $fl
    $genf90 $fl > `basename $fl .in`
done
