#! /usr/bin/env perl
use strict;
use Cwd;

if ($#ARGV == -1) {
    die " ERROR dlnd.buildexe: must specify a caseroot input argument";
}
my ($CASEROOT) = @ARGV;
chdir "${CASEROOT}";

my $CIMEROOT	= `./xmlquery  CIMEROOT	   -value`;
my $NINST_LND	= `./xmlquery  NINST_LND   -value`;
my $RUNDIR	= `./xmlquery  RUNDIR      -value`;
my $CIMEROOT	= `./xmlquery  CIMEROOT    -value`;

my @dirs = ("${CIMEROOT}/utils/perl5lib");
unshift @INC, @dirs;
require Config::SetupTools;
my $sysmod; 

if (! -d "$CASEROOT/Buildconf/dlndconf" ) {
    $sysmod = "mkdir $CASEROOT/Buildconf/dlndconf";
    system($sysmod) == 0 or die "ERROR dlnd.buildnml: $sysmod failed: $?\n";
}
chdir "$CASEROOT/Buildconf/dlndconf";

my $inst_string;
my $inst_counter = 1;
while ($inst_counter <= $NINST_LND) {

    # -----------------------------------------------------
    # determine instance string 
    # -----------------------------------------------------

    $inst_string = "";       
    if ($NINST_LND > 1) {
	$inst_string = `printf _%04d $inst_counter`;

	# If multi-instance case does not have restart file, use single-case restart
	# for each instance
	if ( (! -e "$RUNDIR/rpointer.lnd${inst_string}") && (-e "$RUNDIR/rpointer.lnd") ) {
	    $sysmod = "cp -v $RUNDIR/rpointer.lnd $RUNDIR/rpointer.lnd${inst_string}";
	    system($sysmod) == 0 or die "ERROR dlnd.buildnml: $sysmod failed: $?\n";
	}
    }

    # -----------------------------------------------------
    # create dlndconf/cesm_namelist
    # -----------------------------------------------------

    SetupTools::create_namelist_infile("$CASEROOT", 
				       "$CASEROOT/user_nl_dlnd${inst_string}", 
				       "$CASEROOT/Buildconf/dlndconf/cesm_namelist"); 

    # -----------------------------------------------------
    # call build-namelist
    # -----------------------------------------------------

    $sysmod = "$CIMEROOT/components/data_comps/dlnd/bld/build-namelist";
    $sysmod = "$sysmod -infile $CASEROOT/Buildconf/dlndconf/cesm_namelist";
    $sysmod = "$sysmod -caseroot $CASEROOT";
    $sysmod = "$sysmod -cimeroot $CIMEROOT";
    $sysmod = "$sysmod -inst_string \"$inst_string\"";
    $sysmod = "$sysmod -user_xml_dir \"$CASEROOT/SourceMods/src.dlnd\"";
    system($sysmod) == 0 or die "ERROR dlnd.buildnml: $sysmod failed: $?\n";

    if (-d ${RUNDIR}) {
	$sysmod = "cp $CASEROOT/Buildconf/dlndconf/dlnd_in     ${RUNDIR}/dlnd_in${inst_string}";
	system($sysmod) == 0 or die "ERROR dlnd.buildnml: $sysmod failed: $?\n";

	$sysmod = "cp $CASEROOT/Buildconf/dlndconf/dlnd_lnd_in ${RUNDIR}/dlnd_lnd_in${inst_string}";
	system($sysmod) == 0 or die "ERROR dlnd.buildnml: $sysmod failed: $?\n";

	$sysmod = "cp $CASEROOT/Buildconf/dlndconf/*txt* ${RUNDIR}/ >& /dev/null";
	system($sysmod) == 0;
    }

    # -----------------------------------------------------
    # increment instance counter
    # -----------------------------------------------------

    $inst_counter = $inst_counter + 1;

}

exit (0);
