# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /glade/u/apps/opt/cmake/2.8.10.2/gnu/4.7.2/bin/cmake

# The command to remove a file.
RM = /glade/u/apps/opt/cmake/2.8.10.2/gnu/4.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /glade/u/apps/opt/cmake/2.8.10.2/gnu/4.7.2/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /glade/u/home/jedwards/pio_trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /glade/u/home/jedwards/pio_trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/glade/u/apps/opt/cmake/2.8.10.2/gnu/4.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/glade/u/apps/opt/cmake/2.8.10.2/gnu/4.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /glade/u/home/jedwards/pio_trunk && $(CMAKE_COMMAND) -E cmake_progress_start /glade/u/home/jedwards/pio_trunk/CMakeFiles /glade/u/home/jedwards/pio_trunk/pio/CMakeFiles/progress.marks
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f CMakeFiles/Makefile2 pio/all
	$(CMAKE_COMMAND) -E cmake_progress_start /glade/u/home/jedwards/pio_trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f CMakeFiles/Makefile2 pio/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f CMakeFiles/Makefile2 pio/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f CMakeFiles/Makefile2 pio/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /glade/u/home/jedwards/pio_trunk && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
pio/CMakeFiles/pio.dir/rule:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f CMakeFiles/Makefile2 pio/CMakeFiles/pio.dir/rule
.PHONY : pio/CMakeFiles/pio.dir/rule

# Convenience name for target.
pio: pio/CMakeFiles/pio.dir/rule
.PHONY : pio

# fast build rule for target.
pio/fast:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/build
.PHONY : pio/fast

alloc_mod.o: alloc_mod.F90.o
.PHONY : alloc_mod.o

# target to build an object file
alloc_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/alloc_mod.F90.o
.PHONY : alloc_mod.F90.o

box_rearrange.o: box_rearrange.F90.o
.PHONY : box_rearrange.o

# target to build an object file
box_rearrange.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/box_rearrange.F90.o
.PHONY : box_rearrange.F90.o

calcdecomp.o: calcdecomp.F90.o
.PHONY : calcdecomp.o

# target to build an object file
calcdecomp.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/calcdecomp.F90.o
.PHONY : calcdecomp.F90.o

calcdisplace_mod.o: calcdisplace_mod.F90.o
.PHONY : calcdisplace_mod.o

# target to build an object file
calcdisplace_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/calcdisplace_mod.F90.o
.PHONY : calcdisplace_mod.F90.o

iompi_mod.o: iompi_mod.F90.o
.PHONY : iompi_mod.o

# target to build an object file
iompi_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/iompi_mod.F90.o
.PHONY : iompi_mod.F90.o

ionf_mod.o: ionf_mod.F90.o
.PHONY : ionf_mod.o

# target to build an object file
ionf_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/ionf_mod.F90.o
.PHONY : ionf_mod.F90.o

nf_mod.o: nf_mod.F90.o
.PHONY : nf_mod.o

# target to build an object file
nf_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/nf_mod.F90.o
.PHONY : nf_mod.F90.o

pio.o: pio.F90.o
.PHONY : pio.o

# target to build an object file
pio.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio.F90.o
.PHONY : pio.F90.o

pio_kinds.o: pio_kinds.F90.o
.PHONY : pio_kinds.o

# target to build an object file
pio_kinds.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio_kinds.F90.o
.PHONY : pio_kinds.F90.o

pio_mpi_utils.o: pio_mpi_utils.F90.o
.PHONY : pio_mpi_utils.o

# target to build an object file
pio_mpi_utils.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio_mpi_utils.F90.o
.PHONY : pio_mpi_utils.F90.o

pio_msg_callbacks.o: pio_msg_callbacks.F90.o
.PHONY : pio_msg_callbacks.o

# target to build an object file
pio_msg_callbacks.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio_msg_callbacks.F90.o
.PHONY : pio_msg_callbacks.F90.o

pio_msg_getput_callbacks.o: pio_msg_getput_callbacks.F90.o
.PHONY : pio_msg_getput_callbacks.o

# target to build an object file
pio_msg_getput_callbacks.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio_msg_getput_callbacks.F90.o
.PHONY : pio_msg_getput_callbacks.F90.o

pio_msg_mod.o: pio_msg_mod.F90.o
.PHONY : pio_msg_mod.o

# target to build an object file
pio_msg_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio_msg_mod.F90.o
.PHONY : pio_msg_mod.F90.o

pio_nf_utils.o: pio_nf_utils.F90.o
.PHONY : pio_nf_utils.o

# target to build an object file
pio_nf_utils.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio_nf_utils.F90.o
.PHONY : pio_nf_utils.F90.o

pio_spmd_utils.o: pio_spmd_utils.F90.o
.PHONY : pio_spmd_utils.o

# target to build an object file
pio_spmd_utils.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio_spmd_utils.F90.o
.PHONY : pio_spmd_utils.F90.o

pio_support.o: pio_support.F90.o
.PHONY : pio_support.o

# target to build an object file
pio_support.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio_support.F90.o
.PHONY : pio_support.F90.o

pio_types.o: pio_types.F90.o
.PHONY : pio_types.o

# target to build an object file
pio_types.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio_types.F90.o
.PHONY : pio_types.F90.o

pio_utils.o: pio_utils.F90.o
.PHONY : pio_utils.o

# target to build an object file
pio_utils.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pio_utils.F90.o
.PHONY : pio_utils.F90.o

piodarray.o: piodarray.F90.o
.PHONY : piodarray.o

# target to build an object file
piodarray.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/piodarray.F90.o
.PHONY : piodarray.F90.o

piolib_mod.o: piolib_mod.F90.o
.PHONY : piolib_mod.o

# target to build an object file
piolib_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/piolib_mod.F90.o
.PHONY : piolib_mod.F90.o

pionfatt_mod.o: pionfatt_mod.F90.o
.PHONY : pionfatt_mod.o

# target to build an object file
pionfatt_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pionfatt_mod.F90.o
.PHONY : pionfatt_mod.F90.o

pionfget_mod.o: pionfget_mod.F90.o
.PHONY : pionfget_mod.o

# target to build an object file
pionfget_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pionfget_mod.F90.o
.PHONY : pionfget_mod.F90.o

pionfput_mod.o: pionfput_mod.F90.o
.PHONY : pionfput_mod.o

# target to build an object file
pionfput_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pionfput_mod.F90.o
.PHONY : pionfput_mod.F90.o

pionfread_mod.o: pionfread_mod.F90.o
.PHONY : pionfread_mod.o

# target to build an object file
pionfread_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pionfread_mod.F90.o
.PHONY : pionfread_mod.F90.o

pionfwrite_mod.o: pionfwrite_mod.F90.o
.PHONY : pionfwrite_mod.o

# target to build an object file
pionfwrite_mod.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/pionfwrite_mod.F90.o
.PHONY : pionfwrite_mod.F90.o

rearrange.o: rearrange.F90.o
.PHONY : rearrange.o

# target to build an object file
rearrange.F90.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/rearrange.F90.o
.PHONY : rearrange.F90.o

topology.o: topology.c.o
.PHONY : topology.o

# target to build an object file
topology.c.o:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/topology.c.o
.PHONY : topology.c.o

topology.i: topology.c.i
.PHONY : topology.i

# target to preprocess a source file
topology.c.i:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/topology.c.i
.PHONY : topology.c.i

topology.s: topology.c.s
.PHONY : topology.s

# target to generate assembly for a file
topology.c.s:
	cd /glade/u/home/jedwards/pio_trunk && $(MAKE) -f pio/CMakeFiles/pio.dir/build.make pio/CMakeFiles/pio.dir/topology.c.s
.PHONY : topology.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pio"
	@echo "... rebuild_cache"
	@echo "... alloc_mod.o"
	@echo "... box_rearrange.o"
	@echo "... calcdecomp.o"
	@echo "... calcdisplace_mod.o"
	@echo "... iompi_mod.o"
	@echo "... ionf_mod.o"
	@echo "... nf_mod.o"
	@echo "... pio.o"
	@echo "... pio_kinds.o"
	@echo "... pio_mpi_utils.o"
	@echo "... pio_msg_callbacks.o"
	@echo "... pio_msg_getput_callbacks.o"
	@echo "... pio_msg_mod.o"
	@echo "... pio_nf_utils.o"
	@echo "... pio_spmd_utils.o"
	@echo "... pio_support.o"
	@echo "... pio_types.o"
	@echo "... pio_utils.o"
	@echo "... piodarray.o"
	@echo "... piolib_mod.o"
	@echo "... pionfatt_mod.o"
	@echo "... pionfget_mod.o"
	@echo "... pionfput_mod.o"
	@echo "... pionfread_mod.o"
	@echo "... pionfwrite_mod.o"
	@echo "... rearrange.o"
	@echo "... topology.o"
	@echo "... topology.i"
	@echo "... topology.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /glade/u/home/jedwards/pio_trunk && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

