#!/bin/csh
# need to use single thread
foreach component ( ATM LND ICE OCN CPL GLC ROF WAV )
 ./xmlchange NTASKS_$component=1
 ./xmlchange NTHRDS_$component=1
 ./xmlchange ROOTPE_$component=0
end
# Restart capability is not currently supported for SCM
./xmlchange REST_OPTION=never
# Disable the monthly cice file 
cat <<EOF >> user_nl_cice
  histfreq='y','x','x','x','x'
EOF
