#!/bin/bash

# CMake sets this variable
HOMME_DIR=@Homme_Build_DIR@

# Whether to run the OpenMP tests
RUN_OPENMP=false

# Source the following file to get the rest of the cmake variables
source ${HOMME_DIR}/tests/cmake_variables.sh

# A list (generated by CMake) of all of the tests
source ${HOMME_TESTING_DIR}/test_list.sh

# Functions used to generate the run scripts 
source ${HOMME_TESTING_DIR}/testing-utils.sh

if [ "$1" == all ] ; then

  # The location of all of the lsf scripts generated here
  lsfListFile=${HOMME_TESTING_DIR}/submission-list.sh

  createAllRunScripts

else

  THIS_TEST_FILE=$1

  createRunScript

fi

exit 0
