#! /usr/bin/env perl
use strict;
use Cwd;

if ($#ARGV == -1) {
    die " ERROR mpaso buildnml: must specify a caseroot input argument";
}
my ($CASEROOT) = @ARGV;
chdir "${CASEROOT}";

my $CIMEROOT            = `./xmlquery  CIMEROOT		-value`;
my $CASEROOT		= `./xmlquery  CASEROOT		-value`;
my $CASEBUILD		= `./xmlquery  CASEBUILD	-value`;
my $SRCROOT		= `./xmlquery  SRCROOT		-value`;
my $OBJROOT		= `./xmlquery  OBJROOT		-value`;
my $COMP_INTERFACE	= `./xmlquery  COMP_INTERFACE	-value`;
my $DIN_LOC_ROOT	= `./xmlquery  DIN_LOC_ROOT	-value`;
my $OCN_GRID		= `./xmlquery  OCN_GRID		-value`;
my $OCN_MASK		= `./xmlquery  MASK_GRID	-value`;
my $OCN_FORCING		= `./xmlquery  MPASO_FORCING	-value`;
my $OCN_BGC		= `./xmlquery  MPASO_BGC	-value`;
my $OCN_CO2_TYPE	= `./xmlquery  OCN_CO2_TYPE	-value`;
my $ATM_CO2_CONST_VAL	= `./xmlquery  CCSM_CO2_PPMV	-value`;
my $ICE_BGC		= `./xmlquery  MPASI_BGC	-value`;
my $NTASKS_OCN		= `./xmlquery  NTASKS_OCN	-value`;
my $OCN_PIO_TYPENAME	= `./xmlquery  OCN_PIO_TYPENAME	-value`;
#my $NINST_OCN		= `./xmlquery  NINST_OCN	-value`;
my $NINST_OCN = 1; # Change if you want multiple instances... though this isn't coded yet.
my $RUNDIR		= `./xmlquery  RUNDIR		-value`;
my $RUN_TYPE		= `./xmlquery  RUN_TYPE		-value`;
my $RUN_STARTDATE	= `./xmlquery  RUN_STARTDATE	-value`;
my $RUN_REFCASE		= `./xmlquery  RUN_REFCASE	-value`;
my $RUN_REFDATE		= `./xmlquery  RUN_REFDATE	-value`;
my $RUN_REFTOD		= `./xmlquery  RUN_REFTOD	-value`;
my $STREAM_NAME		= 'streams.ocean';

my @dirs = ("$CIMEROOT/utils/perl5lib");
unshift @INC, @dirs;
require Config::SetupTools;
my $sysmod;

if (! -d "$CASEBUILD/mpasoconf" ) {
    $sysmod = "mkdir $CASEBUILD/mpasoconf";
    system($sysmod) == 0 or die "ERROR mpaso buildnml: $sysmod failed: $?\n";
}

#--------------------------------------------------------------------
# Determine date stamp, from grid names
#--------------------------------------------------------------------

my $decomp_date = '';
my $decomp_prefix = '';
my $ic_date = '';
my $ic_prefix = '';
my $restoring_file = '';
my $analysis_mask_file = '';

if ( $OCN_GRID eq 'oEC60to30' ) {
	$ic_date .= '151031';
	$ic_prefix .= 'oEC60to30';
	$decomp_date .= '151031';
	$decomp_prefix .= 'mpas-o.graph.info.';
} elsif ( $OCN_GRID eq 'oEC60to30_ICG' ) {
        $ic_date .= '160827';
        $ic_prefix .= 'oEC60to30.restartFrom_eos1b';
	$decomp_date .= '151031';
        $decomp_prefix .= 'mpas-o.graph.info.';
} elsif ( $OCN_GRID eq 'oEC60to30v3' ) {
        $ic_date .= '170905';
        $ic_prefix .= 'oEC60to30v3_60layer';
	$decomp_date .= '161222';
        $decomp_prefix .= 'mpas-o.graph.info.';
        $restoring_file .= 'sss.monthlyClimatology.PHC2_salx_040803.oEC60to30v3.nc';
	$analysis_mask_file .= 'oEC60to30v3_Atlantic_region_and_southern_transect.nc';
} elsif ( $OCN_GRID eq 'oEC60to30v3_ICG' ) {
        $ic_date .= '171101';
        $ic_prefix .= 'oEC60to30v3_60layer.restartFrom_anvil0926';
        $decomp_date .= '161222';
        $decomp_prefix .= 'mpas-o.graph.info.';
	$analysis_mask_file .= 'oEC60to30v3_Atlantic_region_and_southern_transect.nc';
} elsif ( $OCN_GRID eq 'oEC60to30wLI' ) {
        $ic_date .= '160830';
        $ic_prefix .= 'oEC60to30wLI';
	$decomp_date .= '160830';
        $decomp_prefix .= 'mpas-o.graph.info.';
} elsif ( $OCN_GRID eq 'oEC60to30v3wLI' ) {
        $ic_date .= '170328';
        $ic_prefix .= 'oEC60to30v3wLI';
        $decomp_date .= '170328';
        $decomp_prefix .= 'mpas-o.graph.info.';
        $restoring_file .= 'sss.monthlyClimatology.PHC2_salx_040803.oEC60to30v3wLI.nc';
	$analysis_mask_file .= 'masks_SingleRegionAtlanticWTransportTransects_EC60to30v3wLI_171116.nc';
} elsif ( $OCN_GRID eq 'oEC60to30v3wLI_ICG' ) {
        $ic_date .= '171116';
        $ic_prefix .= 'oEC60to30v3wLI60lev.restart_theta_year26';
        $decomp_date .= '170328';
        $decomp_prefix .= 'mpas-o.graph.info.';
        $restoring_file .= 'sss.monthlyClimatology.PHC2_salx.EC60to30v3wLI.170328.nc';
	$analysis_mask_file .= 'masks_SingleRegionAtlanticWTransportTransects_EC60to30v3wLI_171116.nc';
} elsif ( $OCN_GRID eq 'oQU240' ) {
	$ic_date .= '151209';
	$ic_prefix .= 'ocean.QU.240km';
	$decomp_date .= '151209';
	$decomp_prefix .= 'mpas-o.graph.info.';
} elsif ( $OCN_GRID eq 'oQU240wLI' ) {
        $ic_date .= '160929';
        $ic_prefix .= 'ocean.QU.240wLI';
        $decomp_date .= '160929';
        $decomp_prefix .= 'mpas-o.graph.info.';
} elsif ( $OCN_GRID eq 'oQU120' ) {
	$ic_date .= '160318';
 	$ic_prefix .= 'ocean.QU.120km';
	$decomp_date .= '160318';
	$decomp_prefix .= 'mpas-o.graph.info.';
} elsif ( $OCN_GRID eq 'mpas120' ) {
	$ic_date .= '151031';
	$ic_prefix .= 'ocean120km';
	$decomp_date .= '151031';
	$decomp_prefix .= 'mpas-o.graph.info.';
} elsif ( $OCN_GRID eq 'oRRS30to10' ) {
	$ic_date .= '151031';
	$ic_prefix .= 'ocean.RRS.30-10km';
	$decomp_date .= '151031';
        $decomp_prefix .= 'mpas-o.graph.info.';
} elsif ( $OCN_GRID eq 'oRRS30to10v3' ) {
	$ic_date .= '171128';
	$ic_prefix .= 'oRRS30to10v3';
	$decomp_date .= '171128';
	$decomp_prefix .= 'mpas-o.graph.info.';
	$restoring_file .= 'sss.monthlyClimatology.PHC2_salx_040803.oRRS30to10v3.nc';
	$analysis_mask_file .= 'masks_SingleRegionAtlanticWTransportTransects_RRS30to10v3.nc';
} elsif ( $OCN_GRID eq 'oRRS30to10v3wLI' ) {
	$ic_date .= '171109';
	$ic_prefix .= 'oRRS30to10v3wLI';
	$decomp_date .= '171109';
	$decomp_prefix .= 'mpas-o.graph.info.';
	$restoring_file .= 'sss.monthlyClimatology.PHC2_salx_040803.oRRS30to10v3wLI.nc';
	$analysis_mask_file .= 'masks_SingleRegionAtlanticWTransportTransects_RRS30to10v3wLI.nc';
} elsif ( $OCN_GRID eq 'oRRS18to6' ) {
	$ic_date .= '160830';
	$ic_prefix .= 'ocean.RRS.18-6km';
	$decomp_date .= '160830';
	$decomp_prefix .= 'mpas-o.graph.info.';
} elsif ( $OCN_GRID eq 'oRRS18to6v3' ) {
	$ic_date .= '171116';
	$ic_prefix .= 'oRRS18to6v3';
	$decomp_date .= '170111';
	$decomp_prefix .= 'mpas-o.graph.info.';
	$restoring_file .= 'sss.monthlyClimatology.PHC2_salx_040803.oRRS18to6v3.nc';
	$analysis_mask_file .= 'oRRS18to6v3.170111.SingleRegionAtlanticWTransportTransects_masks.nc';
} elsif ( $OCN_GRID eq 'oRRS18to6v3_ICG' ) {
	$ic_date .= '171031';
        $ic_prefix .= 'oRRS18to6v3_80Layer.restartFromAnvil';
	$decomp_date .= '170111';
	$decomp_prefix .= 'mpas-o.graph.info.';
	$analysis_mask_file .= 'oRRS18to6v3.170111.SingleRegionAtlanticWTransportTransects_masks.nc';
} elsif ( $OCN_GRID eq 'oRRS15to5' ) {
	$ic_date .= '151209';
	$ic_prefix .= 'ocean.RRS.15-5km';
	$decomp_date .= '151209';
	$decomp_prefix .= 'mpas-o.graph.info.';
}

chdir "$CASEBUILD/mpasoconf";

#--------------------------------------------------------------------
# Set OCN_FORCING = core_forced_restoring if restoring file is available
#--------------------------------------------------------------------
if ($OCN_FORCING eq 'core_forced') {
	if ($restoring_file ne '') {
		$OCN_FORCING = 'core_forced_restoring';
	} else {
		print "WARNING: Should be running with salinity restoring on!\n";
		print "         But no file available for this grid.\n";
	}
}

#--------------------------------------------------------------------
# Set the initial file, changing to a restart file for branch and hybrid runs
# Note: this is not setup for multiple instances
#--------------------------------------------------------------------

my $input_file = "$DIN_LOC_ROOT/ocn/mpas-o/$OCN_MASK/$ic_prefix.$ic_date.nc";
if (( $RUN_TYPE eq 'hybrid') || ( $RUN_TYPE eq 'branch' )) {
    $input_file = "$RUNDIR/mpaso.rst.${RUN_REFDATE}_${RUN_REFTOD}.nc";
    if (! -e "$input_file") {
        die " ERROR mpaso buildnml: missing specified restart file for branch or hybrid run: $input_file ";
    }
}

#--------------------------------------------------------------------
# Generate input data file with stream-specified files
#--------------------------------------------------------------------

open(my $input_list, "+>", "$CASEBUILD/mpaso.input_data_list");
print $input_list "mesh = $DIN_LOC_ROOT/ocn/mpas-o/$OCN_MASK/$ic_prefix.$ic_date.nc\n";
print $input_list "ic = $input_file\n";
if ($analysis_mask_file ne '') {
        print $input_list "moc = $DIN_LOC_ROOT/ocn/mpas-o/$OCN_MASK/$analysis_mask_file\n";
}
if ( $OCN_FORCING eq 'core_forced_restoring' ) {
	print $input_list "sss = $DIN_LOC_ROOT/ocn/mpas-o/$OCN_MASK/$restoring_file\n";
}
close($input_list);

#--------------------------------------------------------------------
# Invoke mpas build-namelist - output will go in $CASEBUILD/mpasoconf
#--------------------------------------------------------------------

my $inst_string;
my $inst_counter = 1;
while ($inst_counter <= $NINST_OCN) {

    # -----------------------------------------------------
    # determine instance string 
    # -----------------------------------------------------

    $inst_string = "";       
    if ($NINST_OCN > 1) {
		$inst_string = `printf _%04d $inst_counter`;

		# If multi-instance case does not have restart file, use single-case restart
		# for each instance
		if ( (! -e "$RUNDIR/rpointer.ocn${inst_string}") && (-e "$RUNDIR/rpointer.ocn") ) {
				$sysmod = "cp -v $RUNDIR/rpointer.ocn $RUNDIR/rpointer.ocn${inst_string}";
				system($sysmod) == 0 or die "ERROR mpaso buildnml: $sysmod failed: $?\n";
		}
    }

    # -----------------------------------------------------
    # create mpasoconf/cesm_namelist
    # -----------------------------------------------------

    SetupTools::create_namelist_infile("$CASEROOT", 
				       "$CASEROOT/user_nl_mpaso${inst_string}", 
				       "$CASEBUILD/mpasoconf/cesm_namelist"); 

    # -----------------------------------------------------
    # call build-namelist- output will go in $CASEBUILD/mpasoconf/mpaso_in
    # -----------------------------------------------------

    #$sysmod = "$SRCROOT/components/mpas-ocean/bld/build-namelist";
    #$sysmod = "$sysmod -infile $CASEBUILD/mpasoconf/cesm_namelist";
    #$sysmod = "$sysmod -inputdata $CASEBUILD/mpaso.input_data_list";
    #$sysmod = "$sysmod -rundir $RUNDIR";
    #$sysmod = "$sysmod -caseroot $CASEROOT";
    #$sysmod = "$sysmod -cimeroot $CIMEROOT";
    #$sysmod = "$sysmod -inst_string \"$inst_string\"";
    #$sysmod = "$sysmod -namelist \"\&cice $CICE_NAMELIST_OPTS\/\" ";
    #$sysmod = "$sysmod -config config_cache.xml";

    $sysmod =  "$SRCROOT/components/mpas-ocean/bld/build-namelist";
	$sysmod .= " -infile $CASEBUILD/mpasoconf/cesm_namelist";
	$sysmod .= " -caseroot $CASEROOT";
	$sysmod .= " -casebuild $CASEBUILD";
	$sysmod .= " -cimeroot $CIMEROOT";
	$sysmod .= " -inst_string '$inst_string'";
	$sysmod .= " -decomp_prefix '$decomp_prefix'";
	$sysmod .= " -date_stamp '$decomp_date'";
	$sysmod .= " -ocn_grid '$OCN_MASK'";
	$sysmod .= " -ocn_forcing '$OCN_FORCING'";
	$sysmod .= " -ocn_bgc '$OCN_BGC'";
	$sysmod .= " -ocn_co2_type '$OCN_CO2_TYPE'";
	$sysmod .= " -atm_co2_const_val '$ATM_CO2_CONST_VAL'";
	$sysmod .= " -ice_bgc '$ICE_BGC'";
    # pass in OCN_MASK for now as a short-cut for the grid
    # at some point, we may want to pass both -- but for now this is simpler

    system($sysmod) == 0 or die "ERROR mpaso buildnml: $sysmod failed: $?\n";

    # -----------------------------------------------------
    # Copy resolved namelist to $RUNDIR
    # -----------------------------------------------------

    my $default_in_filename = "mpaso_in";
    my $in_filename = "${default_in_filename}${inst_string}";
    if ( -d ${RUNDIR} ) {
	$sysmod = "cp $CASEBUILD/mpasoconf/mpaso_in ${RUNDIR}/$in_filename";
	system($sysmod) == 0 or die "ERROR mpaso buildnml: $sysmod failed: $?\n";
    }

    # -----------------------------------------------------
    # increment instance counter
    # -----------------------------------------------------

    $inst_counter = $inst_counter + 1;
}

# Write streams file if there isn't one in SourceMods

if ( -e "$CASEROOT/SourceMods/src.mpaso/$STREAM_NAME" ) {
	$sysmod = "cp $CASEROOT/SourceMods/src.mpaso/$STREAM_NAME $RUNDIR/$STREAM_NAME";
	system($sysmod) == 0 or die "ERROR mpaso buildnml: $sysmod fails: $?\n";
} else {
	open(my $stream_file, "+>", "$RUNDIR/$STREAM_NAME");
	print $stream_file '<streams>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<immutable_stream name="mesh"' . "\n";
	print $stream_file '                  type="none"' . "\n";
	if ( $OCN_GRID =~ m/^oRRS1/ ) {
		print $stream_file '                  io_type="pnetcdf,cdf5"' . "\n";
	} else {
		print $stream_file '                  io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
	print $stream_file "                  filename_template=" . '"'
					. "$DIN_LOC_ROOT/ocn/mpas-o/$OCN_MASK/$ic_prefix.$ic_date.nc"
					. '"' . "\n";
	print $stream_file '/>' . "\n";
	print $stream_file '<immutable_stream name="input"' . "\n";
	print $stream_file '                  type="input"' . "\n";
	if ( $OCN_GRID =~ m/^oRRS1/ ) {
		print $stream_file '                  io_type="pnetcdf,cdf5"' . "\n";
	} else {
		print $stream_file '                  io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
	print $stream_file '                  input_interval="initial_only"' . "\n";
        if ( $OCN_BGC eq 'eco_only' || $OCN_BGC eq 'eco_and_dms' || $OCN_BGC eq 'eco_and_macromolecules' || $OCN_BGC eq 'eco_and_dms_and_macromolecules') {
	print $stream_file "                  filename_template=" . '"'
                                        . "$DIN_LOC_ROOT/ocn/mpas-o/$OCN_MASK/oEC60to30v3.161222+BGC_IC.nc"
                                        . '"' . "\n";
        } else {
	print $stream_file "                  filename_template=" . '"'
                                        . "$input_file"
                                        . '"' . "\n";
        }
	print $stream_file '/>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<!--' . "\n";
	print $stream_file 'The restart stream is actually controlled via the coupler.' . "\n";
	print $stream_file 'Changing output_interval here will not have any affect on' . "\n";
	print $stream_file 'the frequency restart files are written.' . "\n";
	print $stream_file '' . "\n";
	print $stream_file 'Changing the output_interval could cause loss of data.' . "\n";
	print $stream_file '' . "\n";
	print $stream_file 'The output_interval is set to 1 second to ensure each restart frame has a' . "\n";
	print $stream_file 'unique file.' . "\n";
	print $stream_file '-->' . "\n";
	print $stream_file '<immutable_stream name="restart"' . "\n";
	print $stream_file '				  type="input;output"' . "\n";
	if ( $OCN_GRID =~ m/^oRRS1/ ) {
		print $stream_file '				  io_type="pnetcdf,cdf5"' . "\n";
	} else {
		print $stream_file '				  io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
	print $stream_file '				  filename_template="mpaso.rst.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '				  filename_interval="output_interval"' . "\n";
	print $stream_file '				  clobber_mode="truncate"' . "\n";
	print $stream_file '				  input_interval="initial_only"' . "\n";
	print $stream_file '				  reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '				  output_interval="00-00-00_00:00:01"/>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<!--' . "\n";
	print $stream_file 'output is the main history output stream. You can add auxiliary streams to' . "\n";
	print $stream_file 'this stream to include more fields.' . "\n";
	print $stream_file '-->' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="output"' . "\n";
	print $stream_file '		type="output"' . "\n";
	if ( $OCN_GRID =~ m/^oRRS1/ ) {
		print $stream_file '		io_type="pnetcdf,cdf5"' . "\n";
	} else {
		print $stream_file '		io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
	print $stream_file '		filename_template="mpaso.hist.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '		filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '		clobber_mode="truncate"' . "\n";
	print $stream_file '		reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '		output_interval="none">' . "\n";
	print $stream_file '' . "\n";
        print $stream_file '    <var_array name="activeTracerHorizontalAdvectionTendency"/>' . "\n";
        print $stream_file '    <var_array name="activeTracerVerticalAdvectionTendency"/>' . "\n";
	print $stream_file '    <var_array name="activeTracerVertMixTendency"/>' . "\n";
	print $stream_file '    <var_array name="activeTracerSurfaceFluxTendency"/>' . "\n";
	print $stream_file '    <var_array name="temperatureShortWaveTendency"/>' . "\n";
	print $stream_file '    <var_array name="activeTracerNonLocalTendency"/>' . "\n";
	print $stream_file '    <var name="salinitySurfaceRestoringTendency"/>' . "\n";
	print $stream_file '    <var name="vertTransportVelocityTop"/>' . "\n";
	print $stream_file '    <var name="vertGMBolusVelocityTop"/>' . "\n";
	print $stream_file '    <var name="vertAleTransportTop"/>' . "\n";
	print $stream_file '    <var name="tendSSH"/>' . "\n";
	print $stream_file '    <var_struct name="tracers"/>' . "\n";
	print $stream_file '    <var name="layerThickness"/>' . "\n";
	print $stream_file '    <var name="normalVelocity"/>' . "\n";
	print $stream_file '    <var name="ssh"/>' . "\n";
	print $stream_file '    <var name="maxLevelEdgeTop"/>' . "\n";
	print $stream_file '    <var name="vertCoordMovementWeights"/>' . "\n";
	print $stream_file '    <var name="edgeMask"/>' . "\n";
	print $stream_file '    <var name="cellMask"/>' . "\n";
	print $stream_file '    <var name="vertexMask"/>' . "\n";
	print $stream_file '    <var name="refZMid"/>' . "\n";
	print $stream_file '    <var name="refLayerThickness"/>' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="kineticEnergyCell"/>' . "\n";
	print $stream_file '    <var name="relativeVorticityCell"/>' . "\n";
	print $stream_file '    <var name="relativeVorticity"/>' . "\n";
	print $stream_file '    <var name="divergence"/>' . "\n";
	print $stream_file '    <var name="areaCellGlobal"/>' . "\n";
	print $stream_file '    <var name="areaEdgeGlobal"/>' . "\n";
	print $stream_file '    <var name="areaTriangleGlobal"/>' . "\n";
	print $stream_file '    <var name="volumeCellGlobal"/>' . "\n";
	print $stream_file '    <var name="volumeEdgeGlobal"/>' . "\n";
	print $stream_file '    <var name="CFLNumberGlobal"/>' . "\n";
	print $stream_file '    <var name="BruntVaisalaFreqTop"/>' . "\n";
	print $stream_file '    <var name="vertVelocityTop"/>' . "\n";
	print $stream_file '    <var name="velocityZonal"/>' . "\n";
	print $stream_file '    <var name="velocityMeridional"/>' . "\n";
	print $stream_file '    <var name="displacedDensity"/>' . "\n";
	print $stream_file '    <var name="potentialDensity"/>' . "\n";
	print $stream_file '    <var name="pressure"/>' . "\n";
	print $stream_file '    <var name="refBottomDepth"/>' . "\n";
	print $stream_file '    <var name="zMid"/>' . "\n";
	print $stream_file '    <var name="bottomDepth"/>' . "\n";
	print $stream_file '    <var name="maxLevelCell"/>' . "\n";
	print $stream_file '    <var name="maxLevelEdgeTop"/>' . "\n";
	print $stream_file '    <var name="maxLevelEdgeBot"/>' . "\n";
	print $stream_file '    <var name="columnIntegratedSpeed"/>' . "\n";
	print $stream_file '    <var name="landIceFreshwaterFlux"/>' . "\n";
	print $stream_file '    <var name="landIceHeatFlux"/>' . "\n";
	print $stream_file '    <var name="heatFluxToLandIce"/>' . "\n";
        if ( $OCN_BGC eq 'eco_only' || $OCN_BGC eq 'eco_and_dms' || $OCN_BGC eq 'eco_and_macromolecules' || $OCN_BGC eq 'eco_and_dms_and_macromolecules') {
        	print $stream_file '    <var_struct name="ecosysDiagFieldsLevel1"/>' . "\n";
        	print $stream_file '    <var_struct name="ecosysAuxiliary"/>' . "\n";
        }
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<!--' . "\n";
	print $stream_file 'Block debugging stream produces a file per core where errors have occured.' . "\n";
	print $stream_file '-->' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="block_debug_output"' . "\n";
	print $stream_file '		type="output"' . "\n";
	print $stream_file '		io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '		filename_template="mpaso.output_debug_block_$B.nc"' . "\n";
	print $stream_file '		reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '		filename_interval="1000-00-00_00:00:00"' . "\n";
	print $stream_file '		clobber_mode="truncate"' . "\n";
	print $stream_file '		output_interval="1000-00-00_00:00:00">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '	<stream name="mesh"/>' . "\n";
	print $stream_file '	<var name="xtime"/>' . "\n";
	print $stream_file '	<var_struct name="tracers"/>' . "\n";
	print $stream_file '	<var name="layerThickness"/>' . "\n";
	print $stream_file '	<var name="normalVelocity"/>' . "\n";
	print $stream_file '	<var name="ssh"/>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<!--' . "\n";
	print $stream_file 'Streams between this line and the auxiliary stream line below are analysis member streams.' . "\n";
	print $stream_file 'They can be used to perform online analysis of the simulation and control the output of' . "\n";
	print $stream_file 'the analysis data.' . "\n";
	print $stream_file '-->' . "\n";
	print $stream_file '' . "\n";
	if ($OCN_FORCING eq 'core_forced_restoring') {
		print $stream_file '<stream name="surface_salinity_monthly_data"' . "\n";
		print $stream_file '       type="input"' . "\n";
		print $stream_file "       filename_template=" . '"'
						. "$DIN_LOC_ROOT/ocn/mpas-o/$OCN_MASK/$restoring_file"
						. '"' . "\n";
		print $stream_file '       input_interval="none"' . "\n";
		print $stream_file '       packages="activeTracersSurfaceRestoringPKG">' . "\n";
		print $stream_file '' . "\n";
		print $stream_file '       <var name="xtime"/>' . "\n";
		print $stream_file '       <var name="surfaceSalinityMonthlyClimatologyValue"/>' . "\n";
		print $stream_file '</stream>' . "\n";
		print $stream_file '' . "\n";
	}
	if ($analysis_mask_file ne '') {
		print $stream_file '<stream name="transectMasksInput"' . "\n";
		print $stream_file '        type="input"' . "\n";
		print $stream_file "        filename_template=" . '"'
						. "$DIN_LOC_ROOT/ocn/mpas-o/$OCN_MASK/$analysis_mask_file"
						. '"' . "\n";
		print $stream_file '        input_interval="initial_only">' . "\n";
		print $stream_file '' . "\n";
		print $stream_file '        <var name="transectEdgeMasks"/>' . "\n";
		print $stream_file '        <var name="transectNames"/>' . "\n";
		print $stream_file '        <var name="nTransectsInGroup"/>' . "\n";
		print $stream_file '        <var name="transectsInGroup"/>' . "\n";
		print $stream_file '        <var name="transectGroupNames"/>' . "\n";
		print $stream_file '        <var name="transectEdgeMaskSigns"/>' . "\n";
		print $stream_file '</stream>' . "\n";
		print $stream_file '' . "\n";
	}
	if ($analysis_mask_file ne '') {
		print $stream_file '<stream name="regionalMasksInput"' . "\n";
		print $stream_file '        type="input"' . "\n";
		print $stream_file "        filename_template=" . '"'
						. "$DIN_LOC_ROOT/ocn/mpas-o/$OCN_MASK/$analysis_mask_file"
						. '"' . "\n";
		print $stream_file '        input_interval="initial_only">' . "\n";
		print $stream_file '' . "\n";
		print $stream_file '        <var name="regionCellMasks"/>' . "\n";
		print $stream_file '        <var name="regionNames"/>' . "\n";
		print $stream_file '        <var name="nRegionsInGroup"/>' . "\n";
		print $stream_file '        <var name="regionsInGroup"/>' . "\n";
		print $stream_file '        <var name="regionGroupNames"/>' . "\n";
		print $stream_file '</stream>' . "\n";
		print $stream_file '' . "\n";
	}
	print $stream_file '<stream name="mocStreamfunctionOutput"' . "\n";
	print $stream_file '	    type="output"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.mocStreamfunctionOutput.$Y-$M-$D.nc"'. "\n";
	print $stream_file '        filename_interval="01-00-00_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none"' . "\n";
	print $stream_file '        packages="mocStreamfunctionAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '        <var name="xtime"/>' . "\n";
	print $stream_file '        <var name="mocStreamvalLatAndDepth"/>' . "\n";
	print $stream_file '        <var name="mocStreamvalLatAndDepthRegion"/>' . "\n";
	print $stream_file '        <var name="binBoundaryMocStreamfunction"/>' . "\n";
	print $stream_file '        <var name="refBottomDepth"/>' . "\n";
	print $stream_file '        <var name="regionGroupNames"/>' . "\n";
	print $stream_file '        <var name="minMaxLatRegion"/>' . "\n";
	print $stream_file '        <var name="regionNames"/>' . "\n";
	print $stream_file '        <var name="nRegionsInGroup"/>' . "\n";
	print $stream_file '        <var name="regionsInGroup"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="globalStatsOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="netcdf"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.globalStats.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-00-01_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="globalStatsAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '    <var_array name="minGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="maxGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="sumGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="rmsGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="avgGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="vertSumMinGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="vertSumMaxGlobalStats"/>' . "\n";
	print $stream_file '    <var name="volumeCellGlobal"/>' . "\n";
	print $stream_file '    <var name="CFLNumberGlobal"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="surfaceAreaWeightedAveragesOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="netcdf"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.surfaceAreaWeightedAverages.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="surfaceAreaWeightedAveragesAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '    <var_array name="minValueWithinOceanRegion"/>' . "\n";
	print $stream_file '    <var_array name="maxValueWithinOceanRegion"/>' . "\n";
	print $stream_file '    <var_array name="avgValueWithinOceanRegion"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="waterMassCensusOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.waterMassCensus.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="waterMassCensusAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '    <var_array name="waterMassCensusTemperatureValues"/>' . "\n";
	print $stream_file '    <var_array name="waterMassCensusSalinityValues"/>' . "\n";
	print $stream_file '    <var_array name="waterMassFractionalDistribution"/>' . "\n";
	print $stream_file '    <var_array name="potentialDensityOfTSDiagram"/>' . "\n";
	print $stream_file '    <var_array name="zPositionOfTSDiagram"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="layerVolumeWeightedAverageOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.layerVolumeWeightedAverage.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="layerVolumeWeightedAverageAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '    <var_array name="minValueWithinOceanLayerRegion"/>' . "\n";
	print $stream_file '    <var_array name="maxValueWithinOceanLayerRegion"/>' . "\n";
	print $stream_file '    <var_array name="avgValueWithinOceanLayerRegion"/>' . "\n";
	print $stream_file '    <var_array name="minValueWithinOceanVolumeRegion"/>' . "\n";
	print $stream_file '    <var_array name="maxValueWithinOceanVolumeRegion"/>' . "\n";
	print $stream_file '    <var_array name="avgValueWithinOceanVolumeRegion"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="zonalMeanOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.zonalMeans.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none"' . "\n";
	print $stream_file '        ulobber_mode="truncate"' . "\n";
	print $stream_file '        packages="zonalMeanAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '    <var_array name="tracersZonalMean"/>' . "\n";
	print $stream_file '    <var name="binCenterZonalMean"/>' . "\n";
	print $stream_file '    <var name="binBoundaryZonalMean"/>' . "\n";
	print $stream_file '    <var name="velocityZonalZonalMean"/>' . "\n";
	print $stream_file '    <var name="velocityMeridionalZonalMean"/>' . "\n";
	print $stream_file '    <var name="refZMid"/>' . "\n";
	print $stream_file '    <var name="refBottomDepth"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="meridionalHeatTransportOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.meridionalHeatTransport.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="meridionalHeatTransportAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '    <var name="binBoundaryMerHeatTrans"/>' . "\n";
	print $stream_file '    <var name="meridionalHeatTransportLatZ"/>' . "\n";
	print $stream_file '    <var name="meridionalHeatTransportLat"/>' . "\n";
	print $stream_file '    <var name="refZMid"/>' . "\n";
	print $stream_file '    <var name="refBottomDepth"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="eddyProductVariablesOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	if ( $OCN_GRID =~ m/^oRRS1/ ) {
        	print $stream_file '        io_type="pnetcdf,cdf5"' . "\n";
        } else {
		print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
	print $stream_file '        filename_template="mpaso.hist.am.eddyProductVariables.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="eddyProductVariablesAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="SSHSquared"/>' . "\n";
	print $stream_file '    <var name="velocityZonalSquared"/>' . "\n";
	print $stream_file '    <var name="velocityMeridionalSquared"/>' . "\n";
	print $stream_file '    <var name="velocityZonalTimesTemperature"/>' . "\n";
	print $stream_file '    <var name="velocityMeridionalTimesTemperature"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="highFrequencyOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.highFrequencyOutput.$Y-$M-$D_$h.$m.$s.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-00-05_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="highFrequencyOutputAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '    <var_array name="activeTracersAtSurface"/>' . "\n";
	print $stream_file '    <var_array name="activeTracersAt250m"/>' . "\n";
	print $stream_file '    <var_array name="activeTracersAtBottom"/>' . "\n";
	print $stream_file '    <var name="kineticEnergyAtSurface"/>' . "\n";
	print $stream_file '    <var name="kineticEnergyAt250m"/>' . "\n";
	print $stream_file '    <var name="relativeVorticityAt250m"/>' . "\n";
	print $stream_file '    <var name="ssh"/>' . "\n";
	print $stream_file '    <var name="pressureAdjustedSSH"/>' . "\n";
	print $stream_file '    <var name="boundaryLayerDepth"/>' . "\n";
	print $stream_file '    <var name="dThreshMLD"/>' . "\n";
	print $stream_file '    <var name="tThreshMLD"/>' . "\n";
	print $stream_file '    <var name="columnIntegratedSpeed"/>' . "\n";
	print $stream_file '    <var name="barotropicSpeed"/>' . "\n";
	print $stream_file '    <var name="landIceFreshwaterFlux"/>' . "\n";
	print $stream_file '    <var name="pressureAdjustedSSH"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="mixedLayerDepthsOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.mixedLayerDepths.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="mixedLayerDepthsAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '    <var name="tThreshMLD"/>' . "\n";
	print $stream_file '    <var name="dThreshMLD"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsDailyOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.timeSeriesStatsDaily.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-00-01_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="timeSeriesStatsDailyAMPKG"' . "\n";
	print $stream_file '        runtime_format="single_file">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var_array name="tracersSurfaceValue"/>' . "\n";
	print $stream_file '    <var_array name="surfaceVelocity"/>' . "\n";
	print $stream_file '    <var_array name="SSHGradient"/>' . "\n";
	print $stream_file '    <var name="xtime"/>' . "\n";
	print $stream_file '    <var name="ssh"/>' . "\n";
	print $stream_file '    <var name="normalVelocity"/>' . "\n";
	print $stream_file '    <var name="velocityZonal"/>' . "\n";
	print $stream_file '    <var name="velocityMeridional"/>' . "\n";
	print $stream_file '    <var name="vertVelocityTop"/>' . "\n";
	print $stream_file '    <var name="normalTransportVelocity"/>' . "\n";
	print $stream_file '    <var name="transportVelocityZonal"/>' . "\n";
	print $stream_file '    <var name="transportVelocityMeridional"/>' . "\n";
	print $stream_file '    <var name="vertTransportVelocityTop"/>' . "\n";
        print $stream_file '    <var_array name="activeTracerHorizontalAdvectionTendency"/>' . "\n";
        print $stream_file '    <var_array name="activeTracerVerticalAdvectionTendency"/>' . "\n";
	print $stream_file '    <var_array name="activeTracerVertMixTendency"/>' . "\n";
	print $stream_file '    <var_array name="avgValueWithinOceanLayerRegion"/>' . "\n";
	print $stream_file '    <var_array name="avgValueWithinOceanVolumeRegion"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsMonthlyOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
        if ( $OCN_GRID =~ m/^oRRS1/ ) {
        	print $stream_file '        io_type="pnetcdf,cdf5"' . "\n";
        } else {
		print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
	print $stream_file '        filename_template="mpaso.hist.am.timeSeriesStatsMonthly.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="timeSeriesStatsMonthlyAMPKG"' . "\n";
	print $stream_file '        runtime_format="single_file">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '    <var name="binBoundaryMerHeatTrans"/>' . "\n";
	print $stream_file '    <var name="ssh"/>' . "\n";
	print $stream_file '	<var_struct name="tracers"/>' . "\n";
	print $stream_file '    <var name="velocityMeridional"/>' . "\n";
	print $stream_file '    <var name="velocityZonal"/>' . "\n";
	print $stream_file '    <var name="layerThickness"/>' . "\n";
	print $stream_file '    <var name="density"/>' . "\n";
	print $stream_file '    <var name="potentialDensity"/>' . "\n";
	print $stream_file '    <var name="windStressZonal"/>' . "\n";
	print $stream_file '    <var name="windStressMeridional"/>' . "\n";
	print $stream_file '    <var name="frazilLayerThicknessTendency"/>' . "\n";
	print $stream_file '    <var_array name="avgValueWithinOceanRegion"/>' . "\n";
	print $stream_file '    <var_array name="avgValueWithinOceanLayerRegion"/>' . "\n";
	print $stream_file '    <var_array name="avgValueWithinOceanVolumeRegion"/>' . "\n";
	print $stream_file '    <var name="meridionalHeatTransportLatZ"/>' . "\n";
	print $stream_file '    <var name="meridionalHeatTransportLat"/>' . "\n";
	print $stream_file '    <var_array name="minGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="maxGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="sumGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="rmsGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="avgGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="vertSumMinGlobalStats"/>' . "\n";
	print $stream_file '    <var_array name="vertSumMaxGlobalStats"/>' . "\n";
	print $stream_file '    <var name="tThreshMLD"/>' . "\n";
	print $stream_file '    <var name="dThreshMLD"/>' . "\n";
	print $stream_file '    <var name="normalVelocity"/>' . "\n";
	print $stream_file '    <var name="vertVelocityTop"/>' . "\n";
        if ( $OCN_GRID !~ m/^oRRS1/ ) { 
		print $stream_file '    <var name="normalGMBolusVelocity"/>' . "\n";
		print $stream_file '    <var name="vertGMBolusVelocityTop"/>' . "\n";
	}
	print $stream_file '    <var_struct name="tracersSurfaceFlux"/>' . "\n";
	print $stream_file '    <var name="penetrativeTemperatureFlux"/>' . "\n";
	print $stream_file '    <var name="latentHeatFlux"/>' . "\n";
	print $stream_file '    <var name="sensibleHeatFlux"/>' . "\n";
	print $stream_file '    <var name="longWaveHeatFluxUp"/>' . "\n";
	print $stream_file '    <var name="longWaveHeatFluxDown"/>' . "\n";
	print $stream_file '    <var name="seaIceHeatFlux"/>' . "\n";
	print $stream_file '    <var name="shortWaveHeatFlux"/>' . "\n";
	print $stream_file '    <var name="evaporationFlux"/>' . "\n";
	print $stream_file '    <var name="seaIceSalinityFlux"/>' . "\n";
	print $stream_file '    <var name="seaIceFreshWaterFlux"/>' . "\n";
	print $stream_file '    <var name="riverRunoffFlux"/>' . "\n";
	print $stream_file '    <var name="iceRunoffFlux"/>' . "\n";
	print $stream_file '    <var name="rainFlux"/>' . "\n";
	print $stream_file '    <var name="snowFlux"/>' . "\n";
	print $stream_file '    <var name="vertNonLocalFlux"/>' . "\n";
	print $stream_file '    <var_array name="activeTracersTend"/>' . "\n";
	print $stream_file '    <var name="salinitySurfaceRestoringTendency"/>' . "\n";
        print $stream_file '    <var_array name="activeTracerHorizontalAdvectionTendency"/>' . "\n";
        print $stream_file '    <var_array name="activeTracerVerticalAdvectionTendency"/>' . "\n";
        print $stream_file '    <var_array name="activeTracerVertMixTendency"/>' . "\n";
	print $stream_file '    <var_array name="activeTracerSurfaceFluxTendency"/>' . "\n";
	print $stream_file '    <var_array name="temperatureShortWaveTendency"/>' . "\n";
	print $stream_file '    <var_array name="activeTracerNonLocalTendency"/>' . "\n";
	print $stream_file '    <var name="areaCellGlobal"/>' . "\n";
	print $stream_file '    <var name="areaEdgeGlobal"/>' . "\n";
	print $stream_file '    <var name="areaTriangleGlobal"/>' . "\n";
	print $stream_file '    <var name="volumeCellGlobal"/>' . "\n";
	print $stream_file '    <var name="volumeEdgeGlobal"/>' . "\n";
	print $stream_file '    <var name="CFLNumberGlobal"/>' . "\n";
	print $stream_file '    <var name="vertDiffTopOfCell"/>' . "\n";
	print $stream_file '    <var name="vertViscTopOfCell"/>' . "\n";
	print $stream_file '    <var name="bulkRichardsonNumber"/>' . "\n";
	print $stream_file '    <var name="boundaryLayerDepth"/>' . "\n";
	print $stream_file '    <var name="columnIntegratedSpeed"/>' . "\n";
	print $stream_file '    <var name="landIceFreshwaterFlux"/>' . "\n";
	print $stream_file '    <var name="landIceHeatFlux"/>' . "\n";
	print $stream_file '    <var name="heatFluxToLandIce"/>' . "\n";
	print $stream_file '    <var name="mocStreamvalLatAndDepth"/>' . "\n";
	print $stream_file '    <var name="mocStreamvalLatAndDepthRegion"/>' . "\n";
	print $stream_file '    <var name="binBoundaryMocStreamfunction"/>' . "\n";
	print $stream_file '    <var name="surfaceBuoyancyForcing"/>' . "\n";
	print $stream_file '    <var name="tendLayerThickness"/>' . "\n";
	print $stream_file '    <var name="boundaryLayerDepthSmooth"/>' . "\n";
	print $stream_file '    <var name="pressureAdjustedSSH"/>' . "\n";
	print $stream_file '    <var name="SSHSquared"/>' . "\n";
	print $stream_file '    <var name="velocityZonalSquared"/>' . "\n";
	print $stream_file '    <var name="velocityMeridionalSquared"/>' . "\n";
	print $stream_file '    <var name="velocityZonalTimesTemperature"/>' . "\n";
	print $stream_file '    <var name="velocityMeridionalTimesTemperature"/>' . "\n";
        if ( $OCN_BGC eq 'eco_only' || $OCN_BGC eq 'eco_and_dms' || $OCN_BGC eq 'eco_and_macromolecules' || $OCN_BGC eq 'eco_and_dms_and_macromolecules') {
        	print $stream_file '    <var_struct name="ecosysDiagFieldsLevel1"/>' . "\n";
        	print $stream_file '    <var_struct name="ecosysAuxiliary"/>' . "\n";
        }
	print $stream_file '</stream>' . "\n";
        print $stream_file '' . "\n";
        print $stream_file '<stream name="timeSeriesStatsMonthlyMaxOutput"' . "\n";
        print $stream_file '        type="output"' . "\n";
        if ( $OCN_GRID =~ m/^oRRS1/ ) {
                print $stream_file '        io_type="pnetcdf,cdf5"' . "\n";
        } else {
                print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
        print $stream_file '        filename_template="mpaso.hist.am.timeSeriesStatsMonthlyMax.$Y-$M-$D.nc"' . "\n";
        print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
        print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
        print $stream_file '        output_interval="00-01-00_00:00:00"' . "\n";
        print $stream_file '        clobber_mode="truncate"' . "\n";
        print $stream_file '        packages="timeSeriesStatsMonthlyMaxAMPKG"' . "\n";
        print $stream_file '        runtime_format="single_file">' . "\n";
        print $stream_file '' . "\n";
        print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
        print $stream_file '    <var name="ssh"/>' . "\n";
        print $stream_file '    <var name="windStressZonal"/>' . "\n";
        print $stream_file '    <var name="windStressMeridional"/>' . "\n";
        print $stream_file '    <var name="tThreshMLD"/>' . "\n";
        print $stream_file '    <var name="dThreshMLD"/>' . "\n";
        print $stream_file '    <var_struct name="tracersSurfaceFlux"/>' . "\n";
        print $stream_file '    <var name="penetrativeTemperatureFlux"/>' . "\n";
        print $stream_file '    <var name="latentHeatFlux"/>' . "\n";
        print $stream_file '    <var name="sensibleHeatFlux"/>' . "\n";
        print $stream_file '    <var name="longWaveHeatFluxUp"/>' . "\n";
        print $stream_file '    <var name="longWaveHeatFluxDown"/>' . "\n";
        print $stream_file '    <var name="seaIceHeatFlux"/>' . "\n";
        print $stream_file '    <var name="shortWaveHeatFlux"/>' . "\n";
        print $stream_file '    <var name="evaporationFlux"/>' . "\n";
        print $stream_file '    <var name="seaIceSalinityFlux"/>' . "\n";
        print $stream_file '    <var name="seaIceFreshWaterFlux"/>' . "\n";
        print $stream_file '    <var name="riverRunoffFlux"/>' . "\n";
        print $stream_file '    <var name="iceRunoffFlux"/>' . "\n";
        print $stream_file '    <var name="rainFlux"/>' . "\n";
        print $stream_file '    <var name="snowFlux"/>' . "\n";
        print $stream_file '    <var name="boundaryLayerDepth"/>' . "\n";
        print $stream_file '    <var name="landIceFreshwaterFlux"/>' . "\n";
        print $stream_file '    <var name="landIceHeatFlux"/>' . "\n";
        print $stream_file '    <var name="heatFluxToLandIce"/>' . "\n";
        print $stream_file '    <var name="surfaceBuoyancyForcing"/>' . "\n";
        print $stream_file '    <var name="boundaryLayerDepthSmooth"/>' . "\n";
        print $stream_file '    <var name="SSHSquared"/>' . "\n";
	print $stream_file '</stream>' . "\n";
        print $stream_file '' . "\n";
        print $stream_file '<stream name="timeSeriesStatsMonthlyMinOutput"' . "\n";
        print $stream_file '        type="output"' . "\n";
        if ( $OCN_GRID =~ m/^oRRS1/ ) {
                print $stream_file '        io_type="pnetcdf,cdf5"' . "\n";
        } else {
                print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
        print $stream_file '        filename_template="mpaso.hist.am.timeSeriesStatsMonthlyMin.$Y-$M-$D.nc"' . "\n";
        print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
        print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
        print $stream_file '        output_interval="00-01-00_00:00:00"' . "\n";
        print $stream_file '        clobber_mode="truncate"' . "\n";
        print $stream_file '        packages="timeSeriesStatsMonthlyMinAMPKG"' . "\n";
        print $stream_file '        runtime_format="single_file">' . "\n";
        print $stream_file '' . "\n";
        print $stream_file '    <var name="daysSinceStartOfSim"/>' . "\n";
        print $stream_file '    <var name="ssh"/>' . "\n";
        print $stream_file '    <var name="windStressZonal"/>' . "\n";
        print $stream_file '    <var name="windStressMeridional"/>' . "\n";
        print $stream_file '    <var name="tThreshMLD"/>' . "\n";
        print $stream_file '    <var name="dThreshMLD"/>' . "\n";
        print $stream_file '    <var_struct name="tracersSurfaceFlux"/>' . "\n";
        print $stream_file '    <var name="penetrativeTemperatureFlux"/>' . "\n";
        print $stream_file '    <var name="latentHeatFlux"/>' . "\n";
        print $stream_file '    <var name="sensibleHeatFlux"/>' . "\n";
        print $stream_file '    <var name="longWaveHeatFluxUp"/>' . "\n";
        print $stream_file '    <var name="longWaveHeatFluxDown"/>' . "\n";
        print $stream_file '    <var name="seaIceHeatFlux"/>' . "\n";
        print $stream_file '    <var name="shortWaveHeatFlux"/>' . "\n";
        print $stream_file '    <var name="evaporationFlux"/>' . "\n";
        print $stream_file '    <var name="seaIceSalinityFlux"/>' . "\n";
        print $stream_file '    <var name="seaIceFreshWaterFlux"/>' . "\n";
        print $stream_file '    <var name="riverRunoffFlux"/>' . "\n";
        print $stream_file '    <var name="iceRunoffFlux"/>' . "\n";
        print $stream_file '    <var name="rainFlux"/>' . "\n";
        print $stream_file '    <var name="snowFlux"/>' . "\n";
        print $stream_file '    <var name="boundaryLayerDepth"/>' . "\n";
        print $stream_file '    <var name="landIceFreshwaterFlux"/>' . "\n";
        print $stream_file '    <var name="landIceHeatFlux"/>' . "\n";
        print $stream_file '    <var name="heatFluxToLandIce"/>' . "\n";
        print $stream_file '    <var name="surfaceBuoyancyForcing"/>' . "\n";
        print $stream_file '    <var name="boundaryLayerDepthSmooth"/>' . "\n";
        print $stream_file '    <var name="SSHSquared"/>' . "\n";
	print $stream_file '</stream>' . "\n";
        print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsClimatologyOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.timeSeriesStatsClimatology.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-03-00_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="timeSeriesStatsClimatologyAMPKG"' . "\n";
	print $stream_file '        runtime_format="single_file">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsCustomOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.hist.am.timeSeriesStatsCustom.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="timeSeriesStatsCustomAMPKG"' . "\n";
	print $stream_file '        runtime_format="single_file">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsDailyRestart"' . "\n";
	print $stream_file '        type="input;output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.rst.am.timeSeriesStatsDaily.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '        filename_interval="output_interval"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        input_interval="none"' . "\n";
	print $stream_file '        packages="timeSeriesStatsDailyAMPKG"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none">' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsMonthlyRestart"' . "\n";
	print $stream_file '        type="input;output"' . "\n";
        if ( $OCN_GRID =~ m/^oRRS1/ ) {
        	print $stream_file '        io_type="pnetcdf,cdf5"' . "\n";
        } else {
		print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
	print $stream_file '        filename_template="mpaso.rst.am.timeSeriesStatsMonthly.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '        filename_interval="output_interval"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        input_interval="none"' . "\n";
	print $stream_file '        packages="timeSeriesStatsMonthlyAMPKG"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none">' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsMonthlyMaxRestart"' . "\n";
	print $stream_file '        type="input;output"' . "\n";
        if ( $OCN_GRID =~ m/^oRRS1/ ) {
        	print $stream_file '        io_type="pnetcdf,cdf5"' . "\n";
        } else {
		print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
	print $stream_file '        filename_template="mpaso.rst.am.timeSeriesStatsMonthlyMax.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '        filename_interval="output_interval"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        input_interval="none"' . "\n";
	print $stream_file '        packages="timeSeriesStatsMonthlyMaxAMPKG"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none">' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsMonthlyMinRestart"' . "\n";
	print $stream_file '        type="input;output"' . "\n";
        if ( $OCN_GRID =~ m/^oRRS1/ ) {
        	print $stream_file '        io_type="pnetcdf,cdf5"' . "\n";
        } else {
		print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
        }
	print $stream_file '        filename_template="mpaso.rst.am.timeSeriesStatsMonthlyMin.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '        filename_interval="output_interval"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        input_interval="none"' . "\n";
	print $stream_file '        packages="timeSeriesStatsMonthlyMinAMPKG"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="none">' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsClimatologyRestart"' . "\n";
	print $stream_file '        type="input;output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.rst.am.timeSeriesStatsClimatology.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '        filename_interval="output_interval"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        input_interval="initial_only"' . "\n";
	print $stream_file '        packages="timeSeriesStatsClimatologyAMPKG"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="stream:restart:output_interval">' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsCustomRestart"' . "\n";
	print $stream_file '        type="input;output"' . "\n";
	print $stream_file '        io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '        filename_template="mpaso.rst.am.timeSeriesStatsCustom.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '        filename_interval="output_interval"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        input_interval="initial_only"' . "\n";
	print $stream_file '        packages="timeSeriesStatsCustomAMPKG"' . "\n";
	print $stream_file '        reference_time="01-01-01_00:00:00"' . "\n";
	print $stream_file '        output_interval="stream:restart:output_interval">' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
        if ( $OCN_BGC eq 'eco_only' || $OCN_BGC eq 'eco_and_dms' || $OCN_BGC eq 'eco_and_macromolecules' || $OCN_BGC eq 'eco_and_dms_and_macromolecules') {
        	print $stream_file '<stream name="ecosys_monthly_flux"' . "\n";
        	print $stream_file '        type="input"' . "\n";
        	print $stream_file "        filename_template=" . '"'
                                        . "$DIN_LOC_ROOT/ocn/mpas-o/$OCN_MASK/oEC60to30v3.monthlySurfaceForcingBGC.170301.nc"
                                        . '"' . "\n";
        	print $stream_file '        input_interval="none"' . "\n";
        	print $stream_file '        packages="ecosysTracersPKG">' . "\n";
        	print $stream_file '    <var name="xtime"/>' . "\n";
        	print $stream_file '    <var name="depositionFluzNO3"/>' . "\n";
        	print $stream_file '    <var name="depositionFluzNH4"/>' . "\n";
        	print $stream_file '    <var name="IRON_FLUZ_IN"/>' . "\n";
        	print $stream_file '    <var name="dust_FLUZ_IN"/>' . "\n";
        	print $stream_file '    <var name="riverFluzNO3"/>' . "\n";
        	print $stream_file '    <var name="riverFluzPO4"/>' . "\n";
        	print $stream_file '    <var name="riverFluzDON"/>' . "\n";
        	print $stream_file '    <var name="riverFluzDOP"/>' . "\n";
        	print $stream_file '    <var name="riverFluzSiO3"/>' . "\n";
        	print $stream_file '    <var name="riverFluzFe"/>' . "\n";
        	print $stream_file '    <var name="riverFluzDIC"/>' . "\n";
        	print $stream_file '    <var name="riverFluzALK"/>' . "\n";
        	print $stream_file '    <var name="riverFluzDOC"/>' . "\n";
        	print $stream_file '</stream>' . "\n";
        	print $stream_file '' . "\n";
        }
	print $stream_file '<!--' . "\n";
	print $stream_file 'All streams below this line are auxiliary streams. They are provided as' . "\n";
	print $stream_file 'groupings of fields that one might be interested in. You can either enable the' . "\n";
	print $stream_file 'stream to write a file for the fileds, or add the stream to another stream that' . "\n";
	print $stream_file 'will already be written.  ' . "\n";
	print $stream_file '-->' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="forcing"' . "\n";
	print $stream_file '		type="none"' . "\n";
	print $stream_file '		io_type="' . "$OCN_PIO_TYPENAME" . '"' . "\n";
	print $stream_file '		filename_template="mpaso.hist.forcing_variables.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '		filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '		clobber_mode="truncate">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '	<stream name="mesh"/>' . "\n";
	print $stream_file '	<var_struct name="tracersSurfaceFlux"/>' . "\n";
	print $stream_file '	<var_array name="tracersSurfaceValue"/>' . "\n";
	print $stream_file '	<var_array name="surfaceVelocity"/>' . "\n";
	print $stream_file '	<var_array name="SSHGradient"/>' . "\n";
	print $stream_file '	<var_array name="vertNonLocalFlux"/>' . "\n";
	print $stream_file '	<var name="surfaceStressMagnitude"/>' . "\n";
	print $stream_file '	<var name="surfaceStress"/>' . "\n";
	print $stream_file '	<var name="surfaceThicknessFlux"/>' . "\n";
	print $stream_file '	<var name="seaIceEnergy"/>' . "\n";
	print $stream_file '	<var name="penetrativeTemperatureFlux"/>' . "\n";
	print $stream_file '	<var name="fractionAbsorbed"/>' . "\n";
	print $stream_file '	<var name="windStressZonal"/>' . "\n";
	print $stream_file '	<var name="windStressMeridional"/>' . "\n";
	print $stream_file '	<var name="latentHeatFlux"/>' . "\n";
	print $stream_file '	<var name="sensibleHeatFlux"/>' . "\n";
	print $stream_file '	<var name="longWaveHeatFluxUp"/>' . "\n";
	print $stream_file '	<var name="longWaveHeatFluxDown"/>' . "\n";
	print $stream_file '	<var name="seaIceHeatFlux"/>' . "\n";
	print $stream_file '	<var name="shortWaveHeatFlux"/>' . "\n";
	print $stream_file '	<var name="evaporationFlux"/>' . "\n";
	print $stream_file '	<var name="seaIceSalinityFlux"/>' . "\n";
	print $stream_file '	<var name="seaIceFreshWaterFlux"/>' . "\n";
	print $stream_file '	<var name="riverRunoffFlux"/>' . "\n";
	print $stream_file '	<var name="iceRunoffFlux"/>' . "\n";
	print $stream_file '	<var name="rainFlux"/>' . "\n";
	print $stream_file '	<var name="snowFlux"/>' . "\n";
	print $stream_file '	<var name="iceFraction"/>' . "\n";
	print $stream_file '	<var name="nAccumulatedCoupled"/>' . "\n";
	print $stream_file '	<var name="thermalExpansionCoeff"/>' . "\n";
	print $stream_file '	<var name="salineContractionCoeff"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '</streams>' . "\n";
}

exit (0);


