language: python

before_install:
  - sudo apt-get install -y libxml2-utils

install:
  - pip install pylint

python:
  - '2.7'
  - '3.6'

env:
  - CIME_MODEL=cesm

script: cd scripts/tests; ./scripts_regression_tests.py --machine centos7-linux   A_RunUnitTests B_CheckCode G_TestMacrosBasic H_TestMakeMacros I_TestCMakeMacros

# In addition to building PRs, also run the build on the following branches whenever
# it's pushed
branches:
  only:
  - master
  - maint-5.6
  - nuopc-cmeps
