TEXFILES= 		\
m_Accumulator.tex       \
m_AccumulatorComms.tex  \
m_AttrVect.tex          \
m_AttrVectComms.tex     \
m_AttrVectReduce.tex    \
m_ConvertMaps.tex       \
m_ExchangeMaps.tex	\
m_GeneralGrid.tex	\
m_GeneralGridComms.tex	\
m_GlobalMap.tex         \
m_GlobalSegMap.tex      \
m_GlobalToLocal.tex	\
m_MCTWorld.tex		\
m_MatAttrVectMul.tex    \
m_Merge.tex		\
m_NBSend.tex		\
m_Navigator.tex         \
m_Rearranger.tex	\
m_Router.tex		\
m_SparseMatrix.tex      \
m_SparseMatrixComms.tex \
m_SparseMatrixDecomp.tex \
m_SparseMatrixToMaps.tex \
m_SpatialIntegral.tex \
m_String.tex \
m_Transfer.tex \
m_List.tex

