name: Bug Report
description: File a bug report to help us improve e3sm_diags
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Thanks for reporting a bug! Please describe what you were trying to get done.
        Tell us what happened, what went wrong.
    validations:
      required: true

  - type: textarea
    id: what-did-you-expect-to-happen
    attributes:
      label: What did you expect to happen? Are there are possible answers you came across?
      description: |
        Describe what you expected to happen. Include links to pages you've researched (e.g., software docs, Stack Overflow posts).
    validations:
      required: false

  - type: textarea
    id: sample-code
    attributes:
      label: Minimal Complete Verifiable Example (MVCE)
      description: |
        Minimal, self-contained copy-pastable example that generates the issue if possible. Please be concise with code posted (e.g., module imports, publicly accessible files).
        Bug reports that follow these guidelines are easier to diagnose, and so are often handled much more quickly. This section will be automatically formatted into code, so no need for markdown backticks.

        See guidelines below on how to provide a good MCVE:

          - [Minimal Complete Verifiable Examples](https://stackoverflow.com/help/mcve)
          - [Craft Minimal Bug Reports](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)
      render: python

  - type: textarea
    id: log-output
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant output. This will be automatically formatted into code, so no need for markdown backticks.
      render: python

  - type: textarea
    id: extra
    attributes:
      label: Anything else we need to know?
      description: |
        Please describe any other information you want to share.

  - type: textarea
    id: show-versions
    attributes:
      label: Environment
      description: |
        Paste your conda environment here (`conda info`).
    validations:
      required: true
