#!/bin/bash
# override mach-specific PE-defaults
if [ `./xmlquery --value MACH` == chrysalis ]; then
  ./xmlchange MAX_TASKS_PER_NODE=64
  ./xmlchange MAX_MPITASKS_PER_NODE=64
fi

# Run on 8 full nodes MPI-only
ppn=`./xmlquery --value MAX_MPITASKS_PER_NODE`
./xmlchange NTASKS=$(($ppn * 8))
./xmlchange NTHRDS=1
./xmlchange ROOTPE=0
./xmlchange PSTRID=1

