#!/usr/bin/env python

"""
build clm library
"""
import sys, os

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")

_LIBDIR = os.path.join(_CIMEROOT, "scripts", "Tools")
sys.path.append(_LIBDIR)

from standard_script_setup import *
from CIME.buildlib         import parse_input
from CIME.case             import Case
from CIME.utils            import expect, run_bld_cmd_ensure_logging, safe_copy
from CIME.build            import get_standard_cmake_args

logger = logging.getLogger(__name__)

###############################################################################
def buildlib(bldroot, installpath, case):
###############################################################################
    casebuild = case.get_value("CASEBUILD")
    srcroot   = case.get_value("SRCROOT")
    gmake_j   = case.get_value("GMAKE_J")
    gmake     = case.get_value("GMAKE")
    cmake_args = get_standard_cmake_args(case)

    #-------------------------------------------------------
    # create Filepath in bldroot
    #-------------------------------------------------------

    filepath_src = os.path.join(casebuild, "clmconf", "Filepath")
    expect(os.path.exists(filepath_src), "Missing {}".format(filepath_src))
    safe_copy(filepath_src, bldroot)

    #-------------------------------------------------------
    # create the library in libroot
    #-------------------------------------------------------

    # Note that casebuild/clmconf/CCSM_cppdefs is created
    # by the call to clm's bld/configure in clm's cime_config/buildnml

    with open(os.path.join(casebuild, "clmconf", "CCSM_cppdefs"), "r") as fd:
        clmdefs = fd.read().strip()

    clm_config_opts = case.get_value("CLM_CONFIG_OPTS")
    complib = "clm"
    if "clm4_0" in clm_config_opts:
        complib = "lnd"

    run_bld_cmd_ensure_logging('cmake -DMODEL=clm -DCOMPLIB={complib} -DUSER_CPPDEFS="{clmdefs}" {cmake_args} {srcroot}/components'.format(complib=complib, clmdefs=clmdefs, cmake_args=cmake_args, srcroot=srcroot), logger, from_dir=bldroot)
    run_bld_cmd_ensure_logging("{} -j {}".format(gmake, gmake_j), logger, from_dir=bldroot)

###############################################################################
def _main_func():
###############################################################################
    caseroot, libroot, bldroot = parse_input(sys.argv)
    with Case(caseroot, read_only=False) as case:
        buildlib(bldroot, libroot, case)

###############################################################################

if __name__ == "__main__":
    _main_func()
