.\" $Id$
.TH GPTLget_memusage 3 "February, 2007" "GPTL"

.SH NAME
GPTLget_memusage \- Return current memory usage info

.SH SYNOPSIS
.B C Interface:
.nf
int GPTLget_memusage (int *size, int *rss, int *share, 
                      int *text, int *datastack);
.fi

.B Fortran Interface:
.nf
integer gptlget_memusage (integer size, integer rss, integer share, 
                          integer text, integer datastack)
.fi

.SH DESCRIPTION
returns information about current memory usage of the process.

.SH ARGUMENTS
.TP
.I *size
-- Total process size (KB)
.TP
.I *rss
-- Resident set size (KB)
.TP
.I *share
-- Number of pages that are shared
.TP
.I *text
-- Number of pages that are code
.TP
.I *datastack
-- Number of pages that are data/stack

.SH RESTRICTIONS
None

.SH RETURN VALUE
On success, this function returns 0.
On error, -1 is returned.

.SH SEE ALSO
.BR GPTLprint_memusage "(3)" 
