# CMake initial cache file for eurus
SET (CMAKE_Fortran_COMPILER mpif90 CACHE FILEPATH "")
SET (CMAKE_C_COMPILER mpicc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER mpicxx CACHE FILEPATH "")
SET (NETCDF_DIR /home/jamroz/software/netcdf-4.3.0 CACHE FILEPATH "")
SET (HDF5_DIR /home/jamroz/software/hdf5-1.8.11 CACHE FILEPATH "")
SET (SZIP_DIR /home/jamroz/software/szip-2.1 CACHE FILEPATH "")
SET (ZLIB_DIR /home/jamroz/software/zlib-1.2.8 CACHE FILEPATH "")
SET (Trilinos_DIR /home/jamroz/software/trilinos-11.4.3/lib/cmake/Trilinos CACHE FILEPATH "")
SET (PNETCDF_DIR /home/jamroz/software/pnetcdf-1.3.1 CACHE FILEPATH "")
