
SET (CMAKE_Fortran_COMPILER ftn CACHE FILEPATH "")
SET (CMAKE_C_COMPILER cc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER CC CACHE FILEPATH "")
SET (HOMME_USE_MKL "TRUE" CACHE FILEPATH "") # for Intel

SET (HDF5_DIR $ENV{HDF5_DIR} CACHE FILEPATH "")
SET (NETCDF_DIR $ENV{NETCDF_DIR} CACHE FILEPATH "")
SET (PNETCDF_DIR $ENV{PARALLEL_NETCDF_DIR} CACHE FILEPATH "")
SET (CPRNC_DIR /projects/ccsm/acme/tools/cprnc CACHE FILEPATH "")
SET (PREFER_SHARED FALSE CACHE FILEPATH "")
SET (PREFER_STATIC TRUE CACHE FILEPATH "")

SET (USE_QUEUING FALSE CACHE BOOL "")
SET (USE_MPIEXEC "aprun" CACHE STRING "")

