# Conda development environment for testing local source code changes to `e3sm_diags` before merging them to production (`master` branch).
name: e3sm_diags_dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Base
  # =================
  - python >=3.9
  - pip
  - beautifulsoup4
  - cartopy >=0.17.0
  - cartopy_offlinedata
  - cdms2 3.1.5
  - cdutil 8.2.1
  - dask
  - esmpy >=8.4.0
  - genutil 8.2.1
  - lxml
  - mache >=0.15.0
  - matplotlib-base
  - netcdf4
  - output_viewer >=1.3.0
  - numpy >=1.23.0
  - shapely >=2.0.0,<3.0.0
  - xarray >=2023.02.0
  # Testing
  # =======================
  - scipy
  - pytest
  - pytest-cov
  # Documentation
  # =======================
  - sphinx
  - sphinx_rtd_theme
  - sphinx-multiversion
  # Quality Assurance Tools
  # =======================
  # Run `pre-commit autoupdate` to get the latest pinned versions of 'rev' in
  # `.pre-commit.config.yaml`, then update the pinned versions here.
  - black=23.9.1
  - flake8=6.1.0
  - flake8-isort=6.1.0
  - isort=5.12.0
  - mypy=1.5.1
  - pre-commit >=3.0.0
  - types-PyYAML >=6.0.0
  # Developer Tools
  # =======================
  - tbump=6.9.0
  - ipykernel
