{% set name = "e3sm_diags" %}
{% set version = "2.1.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/E3SM-Project/e3sm_diags/archive/v{{ version }}.tar.gz
    sha256: 9c169c27fcdfec870b4e20fd71c24a3a426136424c32003bb9a714af157a3cb5

build:
    number: 0
    noarch: python
    script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - cdp >=1.6.0
    - vcs >=8.2
    - vtk-cdat 8.2.0.8.2
    - vcsaddons >=8.2
    - dv3d >=8.2
    - cdms2 >=3.1.4
    - cdutil >=8.2
    - genutil >=8.2
    - cdtime >=3.1.2
    - numpy
    - matplotlib
    - cartopy
    - beautifulsoup4
    - lxml
    - dask 2.15.0

about:
    home: https://github.com/E3SM-Project/e3sm_diags
    license: BSD-3-Clause
    license_file: LICENSE
    summary: Diagnostics package for the DOE's Energy Exascale Earth System Model (E3SM) project.
