package:
    name: e3sm_diags
    version: {{ environ['VERSION'] }}

source:
    git_url: https://github.com/E3SM-Project/acme_diags

build:
    script: python setup.py install
    script_env:
     - VERSION
     - CONDA_BLD_PATH

requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - cdp 1.4.1
    - vcs 8.0
    - vtk-cdat 8.0.1.8.0
    - vcsaddons 8.0
    - dv3d 8.0
    - cdms2 3.0
    - cdutil 8.0
    - genutil 8.0
    - cdtime 3.0
    - numpy
    - matplotlib
    - cartopy
    - beautifulsoup4
    - lxml

about:
    home: https://github.com/E3SM-Project/acme_diags
    summary: Diagnostics package for the DOE's Energy Exascale Earth System Model (E3SM) project.
