package:
    name: e3sm_diags
    version: 2.1.0

source:
    #path: ..
    git_url: https://github.com/E3SM-Project/e3sm_diags
    git_rev: v2.1.0

build:
    number: 0
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - cdp >=1.6.0
    - vcs >=8.2
    - vtk-cdat 8.2.0.8.2
    - vcsaddons >=8.2
    - dv3d >=8.2
    - cdms2 >=3.1.4
    - cdutil >=8.2
    - genutil >=8.2
    - cdtime >=3.1.2
    - numpy
    - matplotlib
    - cartopy
    - beautifulsoup4
    - lxml

about:
    home: https://github.com/E3SM-Project/e3sm_diags
    summary: Diagnostics package for the DOE's Energy Exascale Earth System Model (E3SM) project.
