package:
    name: e3sm_diags
    version: 2.0.0

source:
    #path: ..
    git_url: https://github.com/E3SM-Project/e3sm_diags
    git_rev: v2.0.0

build:
    number: 0
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - cdp >=1.6.0
    - vcs >=8.0
    - vtk-cdat 8.2.0rc2.8.1
    - vcsaddons >=8.0
    - dv3d >=8.0
    - cdms2 >=3.0.1
    - cdutil >=8.0
    - genutil >=8.0
    - cdtime >=3.0
    - numpy
    - matplotlib
    - cartopy
    - beautifulsoup4
    - lxml

about:
    home: https://github.com/E3SM-Project/e3sm_diags
    summary: Diagnostics package for the DOE's Energy Exascale Earth System Model (E3SM) project.
