package:
    name: acme_diags
    version: {{ environ['VERSION'] }}

source:
    git_url: git://github.com/ACME-Climate/acme_diags

build:
    script: python setup.py install
    script_env:
     - VERSION
     - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools

  run:
    - cdp 1.1.1
    - vcs 2.12
    - vtk-cdat 7.1.0.2.12
    - vcsaddons 2.12
    - dv3d 2.12
    - cdms2 2.12
    - cdutil 2.12
    - genutil 2.12
    - cdtime 2.12
    - numpy
    - matplotlib <2.1.0
    - cartopy
    - beautifulsoup4
    - lxml

about:
    home: https://github.com/ACME-Climate/acme_diags
    summary: This is the new version of ACME Diagnostics.
