{% set name = "e3sm_diags" %}
{% set version = "2.5.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: git://github.com/E3SM-Project/e3sm_diags
    git_rev: v{{ version }}

build:
    number: 0
    noarch: python
    script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - cdp >=1.7.0
    - cdms2
    - cdutil
    - genutil
    - cdtime
    - numpy
    - netcdf4
    - matplotlib
    - cartopy
    - beautifulsoup4
    - lxml
    - dask
    - scipy
    - output_viewer >=1.3.3

about:
    home: https://github.com/E3SM-Project/e3sm_diags
    license: BSD-3-Clause
    license_file: LICENSE
    summary: Diagnostics package for the DOE's Energy Exascale Earth System Model (E3SM) project.
