package:
    name: acme_diags
    version: {{ environ['VERSION'] }}

source:
    git_url: git://github.com/zshaheen/acme-diags

build:
    script: python setup.py install
    script_env:
     - VERSION
     - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools

  run:
    - cdp 2017.04.26
    - vcs
    - cdms2
    - cdutil
    - genutil
    - numpy
    - output_viewer
    - matplotlib 1.5.1
    - cartopy
    - mesalib <8
    - ffmpeg <3

about:
    home: https://github.com/zshaheen/acme-diags
    summary: This is a new version of ACME Diagnostics.
