package:
    name: acme_diags
    version: {{ environ['VERSION'] }}

source:
    git_url: https://github.com/ACME-Climate/acme_diags

build:
    script: python setup.py install
    script_env:
     - VERSION
     - CONDA_BLD_PATH

requirements:
  build:
    - python 2
    - setuptools

  run:
    - python 2
    - cdp 1.3.0
    - vcs 8.0
    - vtk-cdat 8.0.1.8.0
    - vcsaddons 8.0
    - dv3d 8.0
    - mesalib
    - cdms2 3.0
    - cdutil 8.0
    - genutil 8.0
    - cdtime 3.0
    - numpy
    - matplotlib
    - cartopy
    - beautifulsoup4
    - lxml

about:
    home: https://github.com/ACME-Climate/acme_diags
    summary: This is the new version of ACME Diagnostics.
