package:
    name: acme_diags
    version: {{ environ['VERSION'] }}

source:
    git_url: git://github.com/ACME-Climate/acme_diags

build:
    script: python setup.py install
    script_env:
     - VERSION
     - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools

  run:
    - cdp 2017.07.28
    - vcs-nox 2.8.2017.04.04.16.48.c22e1d924a0145ef526b56a8ca123484adfd660a
    - vtk-cdat-nox 7.1.0.2.8.2017.03.23.16.48.73fb094d17ccdd594a6abf9ff8732149c88dc2e6
    - mesalib <8
    - ffmpeg <3
    - vcsaddons-nox 2.8
    - dv3d-nox 2.8
    - cdms2 2.10
    - cdutil 2.10
    - genutil 2.10
    - cdtime 2.10
    - output_viewer
    - numpy
    - matplotlib
    - cartopy
    - dask

about:
    home: https://github.com/ACME-Climate/acme_diags
    summary: This is the new version of ACME Diagnostics.
