function(build_mpas_model MODEL_ARG)

  if (MODEL_ARG STREQUAL "mpaso")
    set(CORE "ocean")
    set(DRIVER "ocean_cesm_driver")
    set(MPAS_COMPNAME "ocn" PARENT_SCOPE)
  elseif (MODEL_ARG STREQUAL "mpassi")
    set(CORE "seaice")
    set(DRIVER "seaice_acme_driver")
    set(MPAS_COMPNAME "ice" PARENT_SCOPE)
  elseif (MODEL_ARG STREQUAL "mpasli")
    set(CORE "landice")
    set(DRIVER "glc_cesm_driver")
    set(MPAS_COMPNAME "glc" PARENT_SCOPE)
    if (USE_ALBANY)
      set(ALBANY True)
    endif()
  else()
    message(FATAL "Unrecognized MPAS model ${MODEL_ARG}")
  endif()

  add_subdirectory("mpas-source/src")

endfunction(build_mpas_model)
