#!/usr/bin/env perl 

use strict;

my @dirs = ('../../ccsm_utils/Tools/per5lib', '../../ccsm_utils/Tools/perl5lib/Build');
unshift @INC, @dirs;
require XML::Lite;
use lib "../../ccsm_utils/Tools/perl5lib";

my $image_dir  = "./images";

print <<"END_of_Start";

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>CESM Component Models Namelist Definitions </title>
  <link rel="stylesheet" type="text/css" href="/models/cesm1.0/cam/docs/namelist/nl_style_sheet.css" />
  <script src=./showinfo.js> </script>
</head>

<body>

<h2>Search or Browse env_run.xml variables </h2>
<p>
This page contains the complete list of xml variables in env_run.xml,
They are grouped by categories designed to aid browsing.  Clicking on the name
of a variable will display descriptive information.  If search terms
are entered in the text box below, the list will be condensed to
contain only matched variables.  </p>

<form id="filter_form" name="filter_form" style="margin: 0px; padding: 0px;" action="javascript:void(0);">
  <table border="0" cellpadding="2" cellspacing="1">
    <tbody>
      <tr>
        <td valign="top">
          <input id="filter_text" name="filter_text" size="40"
                 onkeydown="if (event.keyCode==13) applyFilter(document.getElementById('filter_text').value);"
                 type="text">
          <input id="btn_search" value="Search Variable Names"
                 onclick="applyFilter(document.getElementById('filter_text').value);"
		 type="button">
          <input id="btn_show_all" value="Show All Variable Names"
		 onclick="clearFilter();return false;"
                 type="button">
          <br>
          <label>
            <input id="logical_operator_and" name="logical_operator" value="AND" 
                   type="radio" checked> AND
          </label>
          <label>
            <input id="logical_operator_or" name="logical_operator" value="OR"
                   type="radio"> OR
          </label>
          (separate search terms with spaces)
          <br>
          <label>
            <input id="search_help_text" name="search_help_text" type="checkbox"> Also search help text
          </label>
        </td>
      </tr>
    </tbody>
  </table>
</form>

<div id="filter_matches" style="visibility: hidden; margin-bottom: 10px;">
  Found <span id="filter_matches_num"></span> standard names matching query: <span id="filter_matches_query"></span>
</div>

<p>

<center>
<input id="btn_expand_help" value="Show All Help Text" 
       onclick="expandAllHelp();return false;"
       type="button">
<input id="btn_collapse_help" value="Collapse All Help Text" 
       onclick="collapseAllHelp();return false;"
       type="button">
</center>

END_of_Start

my ($file) = "../../ccsm_utils/Case.template/config_definition.xml";
my $xml = XML::Lite->new( $file );
my $root = $xml->root_element();

# Check for valid root node
my $name = $root->get_name();
$name eq "config_definition" or die
	"file $file is not a config definitions file\n";

# Print table for env_run.xml

my @groups = ("run_desc",
	      "run_start",
	      "run_stop",
	      "run_rest",
	      "run_flags",
	      "run_pio",
	      "run_mpi",
	      "run_cplhist",
	      "run_coupling",
	      "run_defpts",
	      "run_domain",
	      "run_din",
	      "run_dout",
	      "run_cesm",
	      "run_component_cam",
	      "run_component_clm",
	      "run_component_cice",
	      "run_component_pop2",
	      "run_component_cism",
	      "run_component_datm",
	      "run_component_dice",
	      "run_component_docn",
	      "run_component_dlnd",
	      "run_component_drof",
	      "run_sstice",
	      );

my %cat_headings = ("run_desc"           => '<a name="run_desc"    >Run description variables</a> ',
		    "run_start"          => '<a name="run_start"   >Run start control variables</a> ',
		    "run_stop"           => '<a name="run_stop"    >Run stop control variables</a>',
		    "run_rest"           => '<a name="run_rest"    >Run restart control variables</a>',
		    "run_pio"            => '<a name="run_pio"     >Parallel I/O (PIO) control variables</a>',
		    "run_mpi"            => '<a name="run_mpi"     >MPI library setting</a>',
		    "run_cplhist"        => '<a name="run_cplhist" >Coupler history output control variables</a>',
		    "run_coupling"       => '<a name="run_cplfreq" >Component coupling frequency variables</a>',
		    "run_flags"          => '<a name="run_cplperf" >Coupler performance/diagnostic flags</a>',
		    "run_defpts"         => '<a name="run_domspt"  >Domain - single point settings</a>',
		    "run_domain"         => '<a name="run_domglo"  >Domain - global settings</a>',
		    "run_din"            => '<a name="run_datinp"  >Input data control</a>',
		    "run_dout"           => '<a name="run_datout"  >Output data control (short and long term archiving)</a>',
		    "run_cesm"           => '<a name="run_compwide">Component wide run-time settings</a>',
		    "run_component_cam"  => '<a name="run_cam"     >CAM run-time settings</a>',
		    "run_component_clm"  => '<a name="run_clm"     >CLM run-time settings</a>',
		    "run_component_cice" => '<a name="run_cice"    >CICE run-time settings</a>',
		    "run_component_pop2" => '<a name="run_pop"     >POP2 run-time settings</a>',
		    "run_component_cism" => '<a name="run_cism"    >CISM run-time settings</a>',
		    "run_component_datm" => '<a name="run_datm"    >DATM run-time settings</a>',
		    "run_component_dice" => '<a name="run_dice"    >DICE run-time settings</a>',
		    "run_component_docn" => '<a name="run_docn"    >DOCN run-time settings</a>',
		    "run_component_dlnd" => '<a name="run_dlnd"    >DLND run-time settings</a>',
		    "run_component_drof" => '<a name="run_drof"    >DROF run-time settings</a>',
		    "run_sstice"         => '<a name="run_sstice"  >PRESCRIBED SST/ICE run-time settings</a>',
		    );

foreach my $group (@groups) { 
    print_start_table($group, $cat_headings{$group});
    my @e = $xml->elements_by_name( "entry" );
    my %a = ();
    while ( my $e = shift @e ) {
	%a = $e->get_attributes();
	my $var = $a{'id'};
	my $doc = $a{'sdesc'}; 
	if ($a{'ldesc'}) {
	    $doc = "$doc . $a{'ldesc'}";	
	}
	my $valid_values = $a{'valid_values'};
	if ($valid_values ne "") {
	    $doc = $doc . "\nValid Values: $valid_values ";
	}
	my $grp = $a{'group'};
	$grp =~ m/([^_]*)_(.*)/;
	$grp = "env_$1.xml"; 
	if (($grp eq "env_run.xml") && ($a{'group'} eq "$group")) {
	    print_row($var, $doc, $grp, $valid_values);
	}
    }
    print_end_table();
}

# Finish
print <<"END_of_html";
</body>
</html>
END_of_html

#--------------------------------------------------------------------------------------------

sub print_start_table {
    my $category = shift;
    my $hdr      = shift;

print <<"START_table";
<h3><span style="background-color: #00FFFF" font color="purple">$hdr</h3></span>
<table id="${category}_table" border="1" width="100%" cellpadding="2" cellspacing="0">
  <th width="80%">Variable Name</th>
  <th width="10%">File Name</th>
START_table
}

#--------------------------------------------------------------------------------------------

sub print_row {

    my $name = shift;
    my $doc  = shift;
    my $grp  = shift;

print <<"END_of_row";
  <tr id="${name}_tr">
    <td><a name="$name"></a>
        <img id="${name}_arrow" src="$image_dir/arrow_right.gif">
        <code class="varname">
          <a href="javascript:void(0)"
             onclick="toggleHelp('${name}')">$name</a>
        </code>
        <div id="${name}_help" style="display: none;
             padding-left: 16px; margin-top: 4px; border-top: 1px dashed
             #cccccc;">
	     <pre>$doc</pre>
        </div>
    </td>
    <td>$grp</td>
  </tr>
END_of_row
}

#--------------------------------------------------------------------------------------------

sub print_end_table {

print <<"END_table";
</table>
END_table
}

#--------------------------------------------------------------------------------------------

