# CMake initial cache file for janus
SET (CMAKE_Fortran_COMPILER mpif90 CACHE FILEPATH "")
SET (CMAKE_C_COMPILER mpicc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER mpiCC CACHE FILEPATH "")
SET (NETCDF_DIR $ENV{NETCDFDIR} CACHE FILEPATH "")
SET (PNETCDF_DIR $ENV{PNETCDFDIR} CACHE FILEPATH "")
SET (HDF5_DIR $ENV{H5DIR} CACHE FILEPATH "")
SET (SZIP_DIR $ENV{SZIPDIR} CACHE FILEPATH "")
SET (ZLIB_DIR $ENV{ZLIBDIR} CACHE FILEPATH "")
