set(CTEST_PROJECT_NAME "CIME")
string(TIMESTAMP CURRTIME "%H:%M:%S" UTC)
set(CTEST_NIGHTLY_START_TIME "${CURRTIME} UTC")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=CIME")
set(CTEST_DROP_SITE_CDASH TRUE)

set(CTEST_TEST_TIMEOUT 82800 CACHE STRING "")
set(DART_TESTING_TIMEOUT 82800 CACHE STRING "")

set(BUILDNAME "cime_regression_$ENV{SHELL}")
