include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)
common_setup()

set (BLAS_LIBRARIES $ENV{NETLIB_LAPACK_ROOT}/lib64/libblas.so CACHE STRING "")
set (LAPACK_LIBRARIES $ENV{NETLIB_LAPACK_ROOT}/lib64/liblapack.so CACHE STRING "")
set(SCREAM_INPUT_ROOT "/home/projects/e3sm/scream/data" CACHE STRING "")
#set(CMAKE_CXX_FLAGS "-DTHRUST_IGNORE_CUB_VERSION_CHECK" CACHE STRING "" FORCE)
set(CMAKE_Fortran_FLAGS "-fallow-argument-mismatch"  CACHE STRING "" FORCE)
set(HOMMEXX_CUDA_MAX_WARP_PER_TEAM 8 CACHE STRING "")
