#!/usr/bin/env python

"""
A script to merge ESMCI's cime development and make it into a PR for ACME
"""

from standard_script_setup import *
from acme_cime_mgmt import *

import sys, os, argparse

###############################################################################
def parse_command_line(args, description):
###############################################################################
    parser = argparse.ArgumentParser(
        usage="""\n{0} [--verbose]
OR
{0} --help
""".format(os.path.basename(args[0])),

description=description,

formatter_class=argparse.ArgumentDefaultsHelpFormatter
)

    CIME.utils.setup_standard_logging_options(parser)

    parser.add_argument("repo", nargs="?",
                        help="Location of repo to use, default is based on current location")

    parser.add_argument("--resume", action="store_true",
                        help="Resume merge after fixing conflicts")

    args = CIME.utils.parse_args_and_handle_standard_logging_options(args, parser)

    return args.repo, args.resume

###############################################################################
def _main_func(description):
###############################################################################
    repo, resume = parse_command_line(sys.argv, description)

    if repo is not None:
        os.chdir(repo)

    acme_cime_merge(resume)

###############################################################################

if (__name__ == "__main__"):
    _main_func(__doc__)
