#!/usr/bin/env python2

"""
Checks that case is set up correctly
"""

from standard_script_setup import *

from CIME.utils import expect, get_model, run_cmd
from CIME.case  import Case

logger = logging.getLogger(__name__)

parser = argparse.ArgumentParser()
CIME.utils.setup_standard_logging_options(parser)

caseroot = os.getcwd()
cmd = os.path.join(caseroot,"Tools/check_lockedfiles")
run_cmd(cmd)
cmd = os.path.join(caseroot,"preview_namelists")
run_cmd(cmd)

case  = Case(caseroot)
build_complete = case.get_value("BUILD_COMPLETE")
if not build_complete:
    expect(False,
           "Please rebuild the model interactively by calling case.build")

$logger->info( "check_case OK ");

