#!/bin/bash

cime_root=$(./xmlquery --value CIMEROOT)
input_data_dir=$(./xmlquery --value DIN_LOC_ROOT)
atmchange=$cime_root/../components/eamxx/scripts/atmchange
case_name=$(./xmlquery --value CASE)

# Turn on coupler budget diagnostics
./xmlchange BUDGETS=TRUE

# Turn on cosp and set frequency
$atmchange -b physics::atm_procs_list+="cosp"
$atmchange -b physics::cosp::cosp_frequency_units="hours"
$atmchange -b physics::cosp::cosp_frequency=1

# Need to explicitly turn on computing tendencies
$atmchange -b physics::mac_aero_mic::shoc::compute_tendencies=T_mid,qv
$atmchange -b physics::mac_aero_mic::p3::compute_tendencies=T_mid,qv
$atmchange -b physics::rrtmgp::compute_tendencies=T_mid
$atmchange -b homme::compute_tendencies=T_mid,qv,qc

# determine grid and set remap files
atm_grid=$(./xmlquery --value ATM_GRID)
if [[ "${atm_grid}" = "ne30np4.pg2" ]]; then
    hmapfile="${input_data_dir}/atm/scream/maps/map_ne30pg2_to_ne4pg2_20231201.nc"
    armmapfile="${input_data_dir}/atm/scream/maps/map_ne30pg2_to_DecadalSites_c20240130.nc"
    latlonmapfile="${input_data_dir}/atm/scream/maps/map_ne30pg2_to_20x40_20260112.nc"
elif [[ "${atm_grid}" = "ne4np4.pg2" ]]; then
    hmapfile="${input_data_dir}/atm/scream/maps/map_ne4pg2_to_ne2pg2_c20240902.nc"
    latlonmapfile="${input_data_dir}/atm/scream/maps/map_ne4pg2_to_10x20_20260112.nc"
    echo "Note: arm remap only works for ne30pg2 atm grids for now"
    armmapfile="not-supported-yet"
elif [[ "${atm_grid}" = "ne256np4.pg2" ]]; then
    hmapfile="${input_data_dir}/atm/scream/maps/map_ne256pg2_to_ne30pg2_traave.20240206.nc"
    latlonmapfile="${input_data_dir}/atm/scream/maps/map_ne4pg2_to_10x20_20260112.nc"
    echo "Note: arm remap only works for ne30pg2 atm grids for now"
    armmapfile="not-supported-yet"
    echo "Note: latlon remap only works for ne4pg2 and ne30pg2 atm grids for now"
    latlonmapfile="not-supported-yet"
else
    echo "Note: horiz/arm/latlon remaps only work for ne30pg2 and ne4pg2 atm grids for now"
    hmapfile="not-supported-yet"
    armmapfile="not-supported-yet"
    latlonmapfile="not-supported-yet"
fi

# set the output yaml files
output_yaml_files=$(find ${cime_root}/../components/eamxx/cime_config/testdefs/testmods_dirs/eamxx/prod/yaml_outs/ -maxdepth 1 -type f)
for file in ${output_yaml_files[@]}; do
    # Grab the proper map file (if any)
    mapfile=""
    if [[ "${file}" == *"_coarse.yaml" ]]; then
        mapfile=${hmapfile}
    elif [[ "${file}" == *"_arm.yaml" ]]; then
        mapfile=${armmapfile}
    elif [[ "${file}" == *"_latlon.yaml" ]]; then
        mapfile=${latlonmapfile}
    fi
    # If remap is needed,but not supported for this res, skip this yaml
    if [[ "${mapfile}" == "not-supported-yet" ]]; then
      continue
    fi
    # Copy yaml to case dir
    cp -v ${file} ./
    # Append to output list
    $atmchange -b output_yaml_files+="./$(basename ${file})"
    # Replace horiz remap file
    sed -i "s|horiz_remap_file:.*|horiz_remap_file: ${mapfile}|" ./$(basename ${file})
    # Replace all filename prefixes so that st_archive works...
    sed -i "s|eamxx_output.decadal|${case_name}.scream|" ./$(basename ${file})
done
