#!/usr/bin/env perl
#-----------------------------------------------------------------------------------------------
#
# elm build-namelist driver
#
# Placing all of build-namelist into ELMBuildNamelist.pm means we can unit test the module.
#
require 5;

use strict;

BEGIN {
  # ensure that the cesm create_X scripts can find ELMBuildNamelist.pm
  use File::Basename qw(dirname);
  use Cwd qw(abs_path);
  my $dirname = dirname(abs_path($0));
  my @dirs = ($dirname, );
  unshift @INC, @dirs;
}

use ELMBuildNamelist qw(main);

ELMBuildNamelist::main();
