#!/usr/bin/env python3
"""Generate share/util/shr_field_limits_mod.F90 from share/field_limits.yaml.

Each entry is checked against seq_flds_mod.F90 of both drivers (driver-mct and
driver-moab): the field must be registered as sent by its component, any
where_positive field must be sent by the same component, and the units must
match the field's metadata.

Usage:
    python share/gen_field_limits.py           # validate and write the Fortran module
    python share/gen_field_limits.py --check   # validate; fail if the module is out of date

Requires PyYAML.
"""

import argparse
import math
import re
import sys
from pathlib import Path

import yaml

SHARE = Path(__file__).resolve().parent
SRCROOT = SHARE.parent
YAML_FILE = SHARE / "field_limits.yaml"
FORTRAN_FILE = SHARE / "util" / "shr_field_limits_mod.F90"
SEQ_FLDS_FILES = [SRCROOT / d / "shr" / "seq_flds_mod.F90" for d in ("driver-mct", "driver-moab")]

# component name -> prefix of the attribute vectors it sends in seq_flds_mod
COMPONENT_PREFIX = {
    "atm": "a2x", "lnd": "l2x", "ice": "i2x", "ocn": "o2x",
    "rof": "r2x", "glc": "g2x", "wav": "w2x", "iac": "z2x",
}
NAMELEN = 32
UNITSLEN = 16
KEYS = {"component", "units", "min", "max", "min_inclusive", "max_inclusive",
        "where_positive", "owner", "reason"}


def parse_seq_flds(path):
    """Return ({prefix: set of field names}, {field name: units})."""
    sent, units = {}, {}
    current_units = None
    add_re = re.compile(r'call\s+seq_flds_add\(\s*([a-z])2x_(?:states|fluxes)\w*\s*,\s*"(\w+)"')
    for line in path.read_text().splitlines():
        code = line.split("!", 1)[0]
        for letter, name in add_re.findall(code):
            sent.setdefault(letter + "2x", set()).add(name)
        m = re.match(r"\s*units\s*=\s*'([^']*)'", code)
        if m:
            current_units = m.group(1)
        m = re.match(r"\s*attname\s*=\s*'([^']*)'", code)
        if m:
            units[m.group(1)] = current_units
    return sent, units


def validate(fields, sent, units):
    errors = []
    for name, entry in fields.items():
        where = f"{name}:"
        if len(name) > NAMELEN:
            errors.append(f"{where} name longer than {NAMELEN} characters")
        unknown = set(entry) - KEYS
        if unknown:
            errors.append(f"{where} unknown keys {sorted(unknown)}")
        for key in ("component", "units", "owner"):
            if key not in entry:
                errors.append(f"{where} missing '{key}'")
        comp = entry.get("component")
        prefix = COMPONENT_PREFIX.get(comp)
        if prefix is None:
            errors.append(f"{where} unknown component '{comp}'")
            continue
        if name not in sent.get(prefix, set()):
            errors.append(f"{where} not registered in {prefix}")
        if str(entry.get("units")) != units.get(name):
            errors.append(f"{where} units '{entry.get('units')}' do not match "
                          f"'{units.get(name)}'")
        if len(str(entry.get("units", ""))) > UNITSLEN:
            errors.append(f"{where} units longer than {UNITSLEN} characters")
        if "min" not in entry and "max" not in entry:
            errors.append(f"{where} needs 'min', 'max' or both")
        for key in ("min", "max"):
            if key in entry and (isinstance(entry[key], bool) or
                                 not isinstance(entry[key], (int, float)) or
                                 not math.isfinite(entry[key])):
                errors.append(f"{where} '{key}' is not a finite number")
        if isinstance(entry.get("min"), (int, float)) and \
           isinstance(entry.get("max"), (int, float)) and entry["min"] > entry["max"]:
            errors.append(f"{where} min > max")
        wp = entry.get("where_positive")
        if wp is not None and wp not in sent.get(prefix, set()):
            errors.append(f"{where} where_positive '{wp}' is not sent by {comp}")
    return errors


def fortran_real(value):
    # repr gives the shortest round-trip form, e.g. 0.0 or 1e-05
    return repr(float(value)) + "_r8"


def fortran_logical(value):
    return ".true." if value else ".false."


def generate(meta, fields):
    rows = []
    for name, e in fields.items():
        args = [f"'{name}'", f"'{e['component']}'", f"'{e['units']}'",
                fortran_logical("min" in e), fortran_real(e.get("min", 0.0)),
                fortran_logical(e.get("min_inclusive", True)),
                fortran_logical("max" in e), fortran_real(e.get("max", 0.0)),
                fortran_logical(e.get("max_inclusive", True)),
                f"'{e.get('where_positive', '')}'"]
        rows.append("       shr_field_limit_type(" + ", ".join(args) + ")")
    lines = [
        "! WARNING! DO NOT EDIT THIS FILE!",
        "! This file was generated automatically from share/field_limits.yaml",
        "! by share/gen_field_limits.py. Edit the YAML file and rerun the generator.",
        "",
        "module shr_field_limits_mod",
        "",
        "  ! Physical limits on fields sent from components to the coupler.",
        "",
        "  use shr_kind_mod, only: r8 => shr_kind_r8",
        "",
        "  implicit none",
        "  private",
        "",
        f"  character(len=*), parameter, public :: shr_field_limits_version = \"{meta['version_number']}\"",
        f"  integer, parameter, public :: shr_field_limits_nflds = {len(rows)}",
        "",
        "  type, public :: shr_field_limit_type",
        f"     character(len={NAMELEN}) :: name            ! coupler field name",
        "     character(len=3)  :: component       ! component that sends it",
        f"     character(len={UNITSLEN}) :: units",
        "     logical           :: has_min         ! false: no lower limit",
        "     real(r8)          :: min_value",
        "     logical           :: min_inclusive",
        "     logical           :: has_max         ! false: no upper limit",
        "     real(r8)          :: max_value",
        "     logical           :: max_inclusive",
        f"     character(len={NAMELEN}) :: where_positive  ! check only where this field > 0",
        "  end type shr_field_limit_type",
        "",
        "  type(shr_field_limit_type), parameter, public :: shr_field_limits(shr_field_limits_nflds) = [ &",
        ", &\n".join(rows) + " ]",
        "",
        "end module shr_field_limits_mod",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="validate and fail if the Fortran module is out of date")
    args = parser.parse_args()

    with open(YAML_FILE) as fh:
        data = yaml.safe_load(fh)["field_limits"]
    fields = data["fields"]
    errors = []
    for seq_flds_file in SEQ_FLDS_FILES:
        sent, units = parse_seq_flds(seq_flds_file)
        errors += [f"{seq_flds_file.relative_to(SRCROOT)}: {e}"
                   for e in validate(fields, sent, units)]
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    text = generate(data, fields)
    if args.check:
        if not FORTRAN_FILE.exists() or FORTRAN_FILE.read_text() != text:
            print(f"{FORTRAN_FILE} is out of date; run share/gen_field_limits.py", file=sys.stderr)
            return 1
        print(f"{len(fields)} entries valid; {FORTRAN_FILE.name} is up to date")
        return 0
    FORTRAN_FILE.write_text(text)
    print(f"{len(fields)} entries valid; wrote {FORTRAN_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
