#! /usr/bin/env perl
use strict;
use Cwd;

if ($#ARGV == -1) {
    die " ERROR mpas-cice buildnml: must specify a caseroot input argument";
}
my ($CASEROOT) = @ARGV;
chdir "${CASEROOT}";

my $CIMEROOT        = `./xmlquery  CIMEROOT             -value`;
my $CASEROOT        = `./xmlquery  CASEROOT		-value`;
my $CASEBUILD       = `./xmlquery  CASEBUILD		-value`;
my $COMPSET         = `./xmlquery  CCSM_COMPSET         -value`;
my $SRCROOT         = `./xmlquery  SRCROOT              -value`;
my $OBJROOT         = `./xmlquery  OBJROOT		-value`;
my $SCRIPTSROOT	    = `./xmlquery  SCRIPTSROOT		-value`;
my $COMP_INTERFACE  = `./xmlquery  COMP_INTERFACE	-value`;
my $DIN_LOC_ROOT    = `./xmlquery  DIN_LOC_ROOT		-value`;
my $ICE_GRID        = `./xmlquery  ICE_GRID		-value`;
my $ICE_MASK        = `./xmlquery  MASK_GRID            -value`;
my $IC_MODE         = `./xmlquery  MPASCICE_IC_MODE     -value`;
my $NTASKS_ICE      = `./xmlquery  NTASKS_ICE		-value`;
#my $NINST_ICE       = `./xmlquery  NINST_ICE		-value`;
my $NINST_ICE       = 1; # Change if you want multiple instances... though this isn't coded yet.
my $RUNDIR          = `./xmlquery  RUNDIR		-value`;
my $STREAM_NAME     = 'streams.cice';

my @dirs = ("$CIMEROOT/utils/perl5lib");
unshift @INC, @dirs;
require Config::SetupTools;
my $sysmod;


if (! -d "$CASEBUILD/mpas-ciceconf" ) {
    $sysmod = "mkdir $CASEBUILD/mpas-ciceconf";
    system($sysmod) == 0 or die "ERROR mpas-cice buildnml: $sysmod failed: $?\n";
}

#--------------------------------------------------------------------
# Determine date stamp, from grid names
#--------------------------------------------------------------------

my $grid_date = '';
my $grid_prefix = '';
my $decomp_date = '';
my $decomp_prefix = '';

if ( $ICE_GRID eq 'oEC60to30' ) {
	$grid_date .= '151020';
	$grid_prefix .= 'cice.EC60to30km';
	$decomp_date .= '151020';
	$decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oEC60to30_ICG' ) {
        $grid_date .= '160827';
	$grid_prefix .= 'cice.EC60to30km.restartFrom_eos1b';
	$decomp_date .= '151020';
	$decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oEC60to30v3' ) {
        $grid_date .= '161222';
	$grid_prefix .= 'cice.EC60to30v3';
	$decomp_date .= '161222';
	$decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oEC60to30v3_ICG' ) {
        $grid_date .= '170111';
	$grid_prefix .= 'seaice.EC60to30v3.ICG_a16q_yr60';
	$decomp_date .= '161222';
	$decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oEC60to30wLI' ) {
        $grid_date .= '160830';
        $grid_prefix .= 'cice.EC60to30wLI';
        $decomp_date .= '160830';
        $decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'mpas120' ) {
	$grid_date .= '121116';
	$grid_prefix .= 'cice120km';
	$decomp_date .= '121116';
	$decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oQU120' ) {
	$grid_date .= '151209';
	$grid_prefix .= 'seaice.oQU120km';
	$decomp_date .= '151209';
	$decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oQU240' ) {
	$grid_date .= '151209';
	$grid_prefix .= 'seaice.oQU240km';
	$decomp_date .= '151209';
	$decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oQU240wLI' ) {
        $grid_date .= '160929';
        $grid_prefix .= 'cice.QU240wLI';
        $decomp_date .= '160929';
        $decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'mpasgx1' ) {
	$grid_date .= '121116';
	$grid_prefix .= 'grid_gx1';
	$decomp_date .= '121116';
	$decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oRRS30to10' ) {
        $grid_date .= '151031';
        $grid_prefix .= 'seaice.RRS.30-10km';
        $decomp_date .= '151031';
        $decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oRRS30to10v3' ) {
        $grid_date .= '161221';
        $grid_prefix .= 'oRRS30to10v3';
        $decomp_date .= '161221';
        $decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oRRS30to10wLI' ) {
        $grid_date .= '160930';
        $grid_prefix .= 'seaice.RRS30-10wLI';
        $decomp_date .= '160930';
        $decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oRRS18to6' ) {
        $grid_date .= '160830';
        $grid_prefix .= 'seaice.RRS.18to6km';
        $decomp_date .= '160830';
        $decomp_prefix .= 'mpas-cice.graph.info.';
} elsif ( $ICE_GRID eq 'oRRS18to6v3' ) {
        $grid_date .= '170111';
        $grid_prefix .= 'seaice.RRS18to6v3';
        $decomp_date .= '170111';
        $decomp_prefix .= 'mpas-cice.graph.info.lblat_3.';
} elsif ( $ICE_GRID eq 'oRRS15to5' ) {
        $grid_date .= '151209';
        $grid_prefix .= 'seaice.RRS.15to5km';
        $decomp_date .= '151209';
        $decomp_prefix .= 'mpas-cice.graph.info.';
}

chdir "$CASEBUILD/mpas-ciceconf";

#--------------------------------------------------------------------
# Generate input data file
#--------------------------------------------------------------------

open(my $input_list, "+>", "$CASEBUILD/mpas-cice.input_data_list");
print $input_list "mesh = $DIN_LOC_ROOT/ice/mpas-cice/$ICE_MASK/$grid_prefix.$grid_date.nc\n";
#print $input_list "full_graph = $DIN_LOC_ROOT/ice/mpas-cice/$ICE_GRID/$decomp_prefix$grid_date\n";
print $input_list "graph$NTASKS_ICE = $DIN_LOC_ROOT/ice/mpas-cice/$ICE_MASK/$decomp_prefix$decomp_date.part.$NTASKS_ICE\n";
close($input_list);

#--------------------------------------------------------------------
# Invoke mpas build-namelist - output will go in $CASEBUILD/mpas-ciceconf
#--------------------------------------------------------------------

my $inst_string;
my $inst_counter = 1;
while ($inst_counter <= $NINST_ICE) {

    # -----------------------------------------------------
    # determine instance string 
    # -----------------------------------------------------

    $inst_string = "";       
    if ($NINST_ICE > 1) {
		$inst_string = `printf _%04d $inst_counter`;

		# If multi-instance case does not have restart file, use single-case restart
		# for each instance
		if ( (! -e "$RUNDIR/rpointer.ice${inst_string}") && (-e "$RUNDIR/rpointer.ice") ) {
				$sysmod = "cp -v $RUNDIR/rpointer.ice $RUNDIR/rpointer.ice${inst_string}";
				system($sysmod) == 0 or die "ERROR mpas-cice.buildnml: $sysmod failed: $?\n";
		}
    }

    # -----------------------------------------------------
    # create mpas-ciceconf/cesm_namelist
    # -----------------------------------------------------

    SetupTools::create_namelist_infile("$CASEROOT", 
				       "$CASEROOT/user_nl_mpascice${inst_string}",
				       "$CASEBUILD/mpas-ciceconf/cesm_namelist"); 

    # -----------------------------------------------------
    # call build-namelist- output will go in $CASEBUILD/mpas-ciceconf/mpas-cice_in
    # -----------------------------------------------------

    #$sysmod = "$SRCROOT/components/mpas-cice/bld/build-namelist";
    #$sysmod = "$sysmod -infile $CASEBUILD/mpas-ciceconf/cesm_namelist";
    #$sysmod = "$sysmod -inputdata $CASEBUILD/mpas-cice.input_data_list";
    #$sysmod = "$sysmod -rundir $RUNDIR";
    #$sysmod = "$sysmod -caseroot $CASEROOT";
    #$sysmod = "$sysmod -scriptsroot $SCRIPTSROOT";
    #$sysmod = "$sysmod -inst_string \"$inst_string\"";
    #$sysmod = "$sysmod -namelist \"\&cice $CICE_NAMELIST_OPTS\/\" ";
    #$sysmod = "$sysmod -config config_cache.xml";

    $sysmod =  "$SRCROOT/components/mpas-cice/bld/build-namelist";
	$sysmod .= " -infile $CASEBUILD/mpas-ciceconf/cesm_namelist";
	$sysmod .= " -caseroot $CASEROOT";
	$sysmod .= " -casebuild $CASEBUILD";
	$sysmod .= " -cimeroot $CIMEROOT";
	$sysmod .= " -inst_string '$inst_string'";
	$sysmod .= " -date_stamp '$decomp_date'";
	$sysmod .= " -ice_grid '$ICE_MASK'";
	$sysmod .= " -ic_mode '$IC_MODE'";

    # pass in ICE_MASK for now as a short-cut for the grid
    # at some point, we may want to pass both -- but for now this is simpler
    # also, pass in decomp_date for date_stamp, since that's the one required by the scripts

    system($sysmod) == 0 or die "ERROR mpas-cice.buildnml: $sysmod failed: $?\n";

    # -----------------------------------------------------
    # Copy resolved namelist to $RUNDIR
    # -----------------------------------------------------

    my $default_in_filename = "mpas-cice_in";
    my $in_filename = "${default_in_filename}${inst_string}";
    if ( -d ${RUNDIR} ) {
	$sysmod = "cp $CASEBUILD/mpas-ciceconf/mpas-cice_in ${RUNDIR}/$in_filename";
	system($sysmod) == 0 or die "ERROR mpas-cice.buildnml: $sysmod failed: $?\n";
    }

    # -----------------------------------------------------
    # increment instance counter
    # -----------------------------------------------------

    $inst_counter = $inst_counter + 1;
}

# Write streams file if there isn't one in SourceMods

if ( -e "$CASEROOT/SourceMods/src.mpas-cice/$STREAM_NAME" ) {
	$sysmod = "cp $CASEROOT/SourceMods/src.mpas-cice/$STREAM_NAME $RUNDIR/$STREAM_NAME";
	system($sysmod) == 0 or die "ERROR mpas-cice.buildnml: $sysmod fails: $?\n";
} else {
	open(my $stream_file, "+>", "$RUNDIR/$STREAM_NAME");

	print $stream_file '<streams>' . "\n";
	print $stream_file '<immutable_stream name="mesh"' . "\n";
	print $stream_file '                  type="none"' . "\n";
	print $stream_file '                  filename_template="mesh_variables.nc" />' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<immutable_stream name="input"' . "\n";
	print $stream_file '                  type="input"' . "\n";
	print $stream_file '                  filename_interval="none"' . "\n";
	print $stream_file "                  filename_template=" . '"' 
						. "$DIN_LOC_ROOT/ice/mpas-cice/$ICE_MASK/$grid_prefix.$grid_date.nc" 
						. '"' . "\n";
	print $stream_file '                  input_interval="initial_only" />' . "\n";
	print $stream_file '' . "\n";
	print $stream_file "<!--\n";
	print $stream_file "The restart stream is actually controlled via the coupler.\n";
	print $stream_file "Changing output_interval here will not have any affect on\n";
	print $stream_file "the frequency restart files are written.\n";
	print $stream_file "\n";
	print $stream_file "Changing the output_interval could cause loss of data.\n";
	print $stream_file "\n";
	print $stream_file "The output_interval is set to 1 second to ensure each restart frame has a\n";
	print $stream_file "unique file.\n";
	print $stream_file "-->\n";
	print $stream_file '' . "\n";
	print $stream_file '<immutable_stream name="restart"' . "\n";
	print $stream_file '                  type="input;output"' . "\n";
	print $stream_file '                  filename_template="mpascice.rst.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '                  filename_interval="output_interval"' . "\n";
	print $stream_file '                  input_interval="initial_only"' . "\n";
	print $stream_file '                  clobber_mode="replace_files"' . "\n";
	print $stream_file '                  output_interval="00-00-00_00:00:01" />' . "\n";
	print $stream_file '' . "\n";

        if ( $IC_MODE eq 'spunup' ) {
                print $stream_file '<immutable_stream name="restart_ic"' . "\n";
                print $stream_file '                  type="input"' . "\n";
                print $stream_file "                  filename_template=" . '"'
                                                        . "$DIN_LOC_ROOT/ice/mpas-cice/$ICE_MASK/$grid_prefix.$grid_date.nc"
                                                        . '"' . "\n";
                print $stream_file '                  filename_interval="none"' . "\n";
                print $stream_file '                  input_interval="initial_only" />' . "\n";
                print $stream_file '' . "\n";
        }

	print $stream_file '<stream name="output"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        filename_template="mpascice.hist.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '        filename_interval="01-00-00_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="replace_files"' . "\n";
	print $stream_file '        output_interval="none" >' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<immutable_stream name="LYqSixHourlyForcing"' . "\n";
	print $stream_file '                  type="input"' . "\n";
	print $stream_file '                  filename_template="forcing/atmosphere_forcing_six_hourly.$Y.nc"' . "\n";
	print $stream_file '                  filename_interval="0001-00-00_00:00:00"' . "\n";
	print $stream_file '                  reference_time="2000-01-01_03:00:00"' . "\n";
	print $stream_file '                  input_interval="none" />' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<immutable_stream name="LYqMonthlyForcing"' . "\n";
	print $stream_file '                  type="input"' . "\n";
	print $stream_file '                  filename_template="forcing/atmosphere_forcing_monthly.nc"' . "\n";
	print $stream_file '                  filename_interval="none"' . "\n";
	print $stream_file '                  input_interval="none" />' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<immutable_stream name="NCARMonthlySSTForcing"' . "\n";
	print $stream_file '                  type="input"' . "\n";
	print $stream_file '                  filename_template="forcing/ocean_forcing_monthly.nc"' . "\n";
	print $stream_file '                  filename_interval="none"' . "\n";
	print $stream_file '                  input_interval="none" />' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<immutable_stream name="NCARMonthlyForcing"' . "\n";
	print $stream_file '                  type="input"' . "\n";
	print $stream_file '                  filename_template="forcing/ocean_forcing_monthly.nc"' . "\n";
	print $stream_file '                  filename_interval="none"' . "\n";
	print $stream_file '                  input_interval="none" />' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="highFrequencyOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        filename_template="mpascice.hist.am.highFrequencyOutput.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        output_interval="none"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="highFrequencyOutputAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '	<var name="xtime"/>' . "\n";
	print $stream_file '	<stream name="mesh"/>' . "\n";
	print $stream_file '	<var name="iceAreaCellCategory1"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="regionalStatisticsOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        filename_template="mpascice.hist.am.regionalStatistics.$Y.nc"' . "\n";
	print $stream_file '        filename_interval="01-00-00_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-00-00_01:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="regionalStatisticsAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '	<var name="xtime"/>' . "\n";
	print $stream_file '	<var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '	<var name="totalIceArea"/>' . "\n";
	print $stream_file '	<var name="totalIceExtent"/>' . "\n";
	print $stream_file '	<var name="totalIceVolume"/>' . "\n";
	print $stream_file '	<var name="totalSnowVolume"/>' . "\n";
	print $stream_file '	<var name="totalKineticEnergy"/>' . "\n";
	print $stream_file '	<var name="rmsIceSpeed"/>' . "\n";
	print $stream_file '	<var name="averageAlbedo"/>' . "\n";
	print $stream_file '	<var name="maximumIceVolume"/>' . "\n";
	print $stream_file '	<var name="maximumIcePressure"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="conservationCheckOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        filename_template="mpascicehist.am.conservationCheck.$Y.nc"' . "\n";
	print $stream_file '        filename_interval="01-00-00_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="conservationCheckAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '	<var name="xtime"/>' . "\n";
	print $stream_file '	<var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '	<var name="initialEnergy"/>' . "\n";
	print $stream_file '	<var name="finalEnergy"/>' . "\n";
	print $stream_file '	<var name="energyChange"/>' . "\n";
	print $stream_file '	<var name="netEnergyFlux"/>' . "\n";
	print $stream_file '	<var name="absoluteEnergyError"/>' . "\n";
	print $stream_file '	<var name="relativeEnergyError"/>' . "\n";
	print $stream_file '	<var name="initialMass"/>' . "\n";
	print $stream_file '	<var name="finalMass"/>' . "\n";
	print $stream_file '	<var name="massChange"/>' . "\n";
	print $stream_file '	<var name="netMassFlux"/>' . "\n";
	print $stream_file '	<var name="absoluteMassError"/>' . "\n";
	print $stream_file '	<var name="relativeMassError"/>' . "\n";
	print $stream_file '	<var name="initialSalt"/>' . "\n";
	print $stream_file '	<var name="finalSalt"/>' . "\n";
	print $stream_file '	<var name="saltChange"/>' . "\n";
	print $stream_file '	<var name="netSaltFlux"/>' . "\n";
	print $stream_file '	<var name="absoluteSaltError"/>' . "\n";
	print $stream_file '	<var name="relativeSaltError"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="loadBalanceOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        filename_template="mpascice.hist.am.cice_loadBalance.$Y.nc"' . "\n";
	print $stream_file '        filename_interval="01-00-00_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-00-00_01:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="loadBalanceAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '	<var name="xtime"/>' . "\n";
	print $stream_file '	<var name="nCellsProcWithSeaIce"/>' . "\n";
	print $stream_file '	<var name="nCellsProc"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="maximumIcePresenceOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        filename_template="mpascice.hist.am.cice_maximumIcePresence.$Y.nc"' . "\n";
	print $stream_file '        filename_interval="01-00-00_00:00:00"' . "\n";
	print $stream_file '        output_interval="01-00-00_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="maximumIcePresenceAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '	<var name="xtime"/>' . "\n";
	print $stream_file '	<stream name="mesh"/>' . "\n";
	print $stream_file '	<var name="maximumIcePresence"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsDailyOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        filename_template="mpascice.hist.am.timeSeriesStatsDaily.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-00-01_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="timeSeriesStatsDailyAMPKG">' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsDailyRestart"' . "\n";
	print $stream_file '        type="input;output"' . "\n";
	print $stream_file '        filename_template="mpascice.rst.am.timeSeriesStatsDaily.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '        filename_interval="output_interval"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="timeSeriesStatsDailyAMPKG"' . "\n";
	print $stream_file '        input_interval="initial_only"' . "\n";
	print $stream_file '        output_interval="stream:restart:output_interval">' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsMonthlyOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        filename_template="mpascice.hist.am.timeSeriesStatsMonthly.$Y-$M-$D.nc"' . "\n";
	print $stream_file '        filename_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        output_interval="00-01-00_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="timeSeriesStatsMonthlyAMPKG">' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '	<var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '	<var name="icePresent"/>' . "\n";
	print $stream_file '	<var name="iceAreaCell"/>' . "\n";
	print $stream_file '	<var name="iceVolumeCell"/>' . "\n";
	print $stream_file '	<var name="snowVolumeCell"/>' . "\n";
	print $stream_file '	<var name="surfaceTemperatureCell"/>' . "\n";
	print $stream_file '	<var name="uVelocityGeo"/>' . "\n";
	print $stream_file '	<var name="vVelocityGeo"/>' . "\n";
	print $stream_file '	<var name="shortwaveDown"/>' . "\n";
	print $stream_file '	<var name="longwaveDown"/>' . "\n";
	print $stream_file '	<var name="seaSurfaceTemperature"/>' . "\n";
	print $stream_file '	<var name="seaSurfaceSalinity"/>' . "\n";
	print $stream_file '	<var name="uOceanVelocityVertexGeo"/>' . "\n";
	print $stream_file '	<var name="vOceanVelocityVertexGeo"/>' . "\n";
	print $stream_file '	<var name="freezingMeltingPotential"/>' . "\n";
	print $stream_file '	<var name="shortwaveScalingFactor"/>' . "\n";
	print $stream_file '	<var name="airTemperature"/>' . "\n";
	print $stream_file '	<var name="congelation"/>' . "\n";
	print $stream_file '	<var name="frazilFormation"/>' . "\n";
	print $stream_file '	<var name="snowiceFormation"/>' . "\n";
	print $stream_file '	<var name="snowMelt"/>' . "\n";
	print $stream_file '	<var name="surfaceIceMelt"/>' . "\n";
	print $stream_file '	<var name="basalIceMelt"/>' . "\n";
	print $stream_file '	<var name="lateralIceMelt"/>' . "\n";
	print $stream_file '	<var name="airStressVertexUGeo"/>' . "\n";
	print $stream_file '	<var name="airStressVertexVGeo"/>' . "\n";
	print $stream_file '	<var name="icePressure"/>' . "\n";
	print $stream_file '	<var name="divergence"/>' . "\n";
	print $stream_file '	<var name="shear"/>' . "\n";
	print $stream_file '	<var name="principalStress1Var"/>' . "\n";
	print $stream_file '	<var name="principalStress2Var"/>' . "\n";
	print $stream_file '	<var name="iceVolumeTendencyThermodynamics"/>' . "\n";
	print $stream_file '	<var name="iceVolumeTendencyTransport"/>' . "\n";
	print $stream_file '	<var name="iceAreaTendencyThermodynamics"/>' . "\n";
	print $stream_file '	<var name="iceAreaTendencyTransport"/>' . "\n";
	print $stream_file '	<var name="iceAgeTendencyThermodynamics"/>' . "\n";
	print $stream_file '	<var name="iceAgeTendencyTransport"/>' . "\n";
	print $stream_file '	<var name="iceAgeCell"/>' . "\n";
	print $stream_file '	<var name="firstYearIceAreaCell"/>' . "\n";
	print $stream_file '	<var name="levelIceAreaCell"/>' . "\n";
	print $stream_file '	<var name="levelIceVolumeCell"/>' . "\n";
	print $stream_file '	<var name="ridgedIceAreaAverage"/>' . "\n";
	print $stream_file '	<var name="ridgedIceVolumeAverage"/>' . "\n";
	print $stream_file '	<var name="bulkSalinity"/>' . "\n";
	print $stream_file '	<var name="broadbandAlbedo"/>' . "\n";
	print $stream_file '	<var name="absorbedShortwaveFluxInitialArea"/>' . "\n";
	print $stream_file '	<var name="latentHeatFluxInitialArea"/>' . "\n";
	print $stream_file '	<var name="sensibleHeatFluxInitialArea"/>' . "\n";
	print $stream_file '	<var name="longwaveUpInitialArea"/>' . "\n";
	print $stream_file '	<var name="evaporativeWaterFluxInitialArea"/>' . "\n";
	print $stream_file '	<var name="meltPondAreaFinalArea"/>' . "\n";
	print $stream_file '	<var name="meltPondDepthFinalArea"/>' . "\n";
	print $stream_file '	<var name="meltPondLidThicknessFinalArea"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsMonthlyRestart"' . "\n";
	print $stream_file '        type="input;output"' . "\n";
	print $stream_file '        filename_template="mpascice.rst.am.timeSeriesStatsMonthly.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '        filename_interval="output_interval"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="timeSeriesStatsMonthlyAMPKG"' . "\n";
	print $stream_file '        input_interval="initial_only"' . "\n";
	print $stream_file '        output_interval="stream:restart:output_interval">' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsClimatologyOutput"' . "\n";
	print $stream_file '        type="output"' . "\n";
	print $stream_file '        filename_template="mpascice.hist.am.timeSeriesStatsClimatology.$Y.nc"' . "\n";
	print $stream_file '        filename_interval="01-00-00_00:00:00"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="timeSeriesStatsClimatologyAMPKG"' . "\n";
	print $stream_file '        output_interval="10-00-00_00:00:00" >' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '	<var name="daysSinceStartOfSim"/>' . "\n";
	print $stream_file '	<var name="icePresent"/>' . "\n";
	print $stream_file '	<var name="iceAreaCell"/>' . "\n";
	print $stream_file '	<var name="iceVolumeCell"/>' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
	print $stream_file '<stream name="timeSeriesStatsClimatologyRestart"' . "\n";
	print $stream_file '        type="input;output"' . "\n";
	print $stream_file '        filename_template="mpascice.rst.am.timeSeriesStatsClimatology.$Y-$M-$D_$S.nc"' . "\n";
	print $stream_file '        filename_interval="output_interval"' . "\n";
	print $stream_file '        clobber_mode="truncate"' . "\n";
	print $stream_file '        packages="timeSeriesStatsClimatologyAMPKG"' . "\n";
	print $stream_file '        input_interval="initial_only"' . "\n";
	print $stream_file '        output_interval="stream:restart:output_interval">' . "\n";
	print $stream_file '</stream>' . "\n";
	print $stream_file '' . "\n";
        print $stream_file '<stream name="landIceMasks"' . "\n";
        print $stream_file '       type="input"' . "\n";
        print $stream_file '       input_interval="initial_only"' . "\n";
        print $stream_file "       filename_template=" . '"'
                                                . "$DIN_LOC_ROOT/ice/mpas-cice/$ICE_MASK/$grid_prefix.$grid_date.nc"
                                                . '">' . "\n";
        print $stream_file '' . "\n";
        print $stream_file '       <var name="landIceMask"/>' . "\n";
        print $stream_file '</stream>' . "\n";
        print $stream_file '' . "\n";
	print $stream_file '</streams>' . "\n";

}

exit (0);


