set(CTEST_PROJECT_NAME "HOMME")
set(CTEST_NIGHTLY_START_TIME "00:00:00 UTC")

set(CTEST_DROP_METHOD "https")
set(CTEST_CURL_OPTIONS
  "CURLOPT_SSL_VERIFYPEER_OFF"
  "CURLOPT_SSL_VERIFYHOST_OFF"
)
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=E3SM")
set(CTEST_DROP_SITE_CDASH TRUE)
