#! /usr/bin/env perl
use strict;

if ($#ARGV == -1) {
    die " ERROR ww3 buildlib: must specify a caseroot input argument";
}
my ($CASEROOT) = @ARGV;
chdir "${CASEROOT}";

my $CASEROOT		= `./xmlquery CASEROOT       --value`;
my $CASETOOLS		= `./xmlquery CASETOOLS      --value`;
my $SRCROOT		= `./xmlquery SRCROOT        --value`;
my $MACH		= `./xmlquery MACH           --value`;
my $OBJROOT		= `./xmlquery OBJROOT        --value`;
my $LIBROOT		= `./xmlquery LIBROOT        --value`;
my $GMAKE_J		= `./xmlquery GMAKE_J        --value`;
my $GMAKE		= `./xmlquery GMAKE          --value`;
my $COMPILER            = `./xmlquery COMPILER       --value`;
my $MPILIB              = `./xmlquery MPILIB         --value`;
my $COMP_INTERFACE      = `./xmlquery COMP_INTERFACE --value`;
my $EXEROOT             = `./xmlquery EXEROOT        --value`;
my $NINST_VALUE         = `./xmlquery NINST_VALUE    --value`;
my $RUNDIR              = `./xmlquery RUNDIR         --value`;

# Define WW3 repository directories
my $repodir = "$SRCROOT/components/ww3/src/source";
my $modeldir = "$repodir/WW3/model";
my $bindir = "$modeldir/bin";
my $exedir = "$modeldir/exe";
my $tmpdir = "$modeldir/tmp";

# Run w3_setup to create wwatch3.env file
chdir $bindir;
if ( -f "$bindir/wwatch3.env"){
  `rm wwatch3.env`
}
my $comp = ucfirst($COMPILER);
`cp $repodir/switch_E3SM $bindir`;
open(file,">w3_setup.inp") or die "Could not open file w3_setup.inp to write";
print file "y\n";
print file "\n";
print file "ifort\n";
print file "icc\n";
print file "$tmpdir\n";
print file "\n";
print file "\n";
print file "y\n";
close(file);
`./w3_setup $modeldir -c $comp -s E3SM < w3_setup.inp`;
`rm w3_setup.inp`;
`rm switch_E3SM`;

# Generate pre-processed WW3 source code
my $tarfile = "$modeldir/work/ww3_shel.tar.gz";
`./w3_source ww3_shel`;
`mv $tarfile $tmpdir`;
chdir $tmpdir;
`tar -xzvf ww3_shel.tar.gz`;

chdir "$OBJROOT/wav/obj";
open(file,">Filepath") or die "Could not open file Filepath to write";
print file "${CASEROOT}/SourceMods/src.ww3\n";
print file "${tmpdir}\n";
print file "${SRCROOT}/components/ww3/src/cpl\n";
close(file);
my $sysmod = "$GMAKE complib -j $GMAKE_J MODEL=ww3 COMPLIB=$LIBROOT/libwav.a -f $CASETOOLS/Makefile CASEROOT=$CASEROOT CASETOOLS=$CASETOOLS COMPILER=$COMPILER MPILIB=$MPILIB COMP_INTERFACE=$COMP_INTERFACE EXEROOT=$EXEROOT NINST_VALUE=$NINST_VALUE";
system($sysmod) == 0 or die "ERROR: $sysmod failed: $?\n";

# Compile ww3_grid and move to run directory
chdir $bindir;
$ENV{'WWATCH3_NETCDF'} = "NC4";
my $ncconfig = `which nc-config`;
chomp $ncconfig;
$ENV{'NETCDF_CONFIG'} = $ncconfig;
open(file,">w3_make.inp") or die "Could not open file w3_make.inp to write";
print file "k\n";
close(file); 
`./w3_make ww3_grid < w3_make.inp > out.txt`;
`rm w3_make.inp`;
chdir $exedir;
`mv ww3_grid $RUNDIR`;

# Run ww3_grid
chdir $RUNDIR;
`./ww3_grid`;

# Cleanup untracked file
chdir $modeldir;
`rm makefile`;

exit(0);

