&ctl_nl
disable_diagnostics     = .false.
se_partmethod           = 4
se_topology             = "cube"
se_ftype                = ${HOMME_SE_FTYPE}
se_limiter_option       = ${HOMME_TEST_LIM}
se_ne                   = ${HOMME_TEST_NE}
se_geometry             = "sphere"
se_tstep                = ${HOMME_TEST_TIME_STEP}
mesh_file               = '/dev/null'
rotate_grid             = 0
u_perturb               = 1
statefreq               = 9999
tstep_type              = ${HOMME_TTYPE}
dt_remap_factor         = ${HOMME_TEST_REMAP_FACTOR}
dt_tracer_factor        = ${HOMME_TEST_TRACERS_FACTOR}
nu                      = ${HOMME_TEST_NU}
nu_div                  = ${HOMME_TEST_NU}
nu_p                    = ${HOMME_TEST_NU}
nu_q                    = ${HOMME_TEST_NU}
nu_s                    =-1
nu_top                  = ${HOMME_TEST_NUTOP}
vert_remap_q_alg        = 1
hypervis_scaling        = ${HOMME_TEST_HVSCALING}
hypervis_order          = 2
hypervis_subcycle       = ${HOMME_TEST_HVS}
hypervis_subcycle_tom   = ${HOMME_TEST_HVS_TOM}
hypervis_subcycle_q     = 1
theta_hydrostatic_mode  = ${HOMME_THETA_HY_MODE}
theta_advect_form       = ${HOMME_THETA_FORM}
COORD_TRANSFORM_METHOD  = 0
Z2_MAP_METHOD           = 0
vthreads                = 1    ! number of vertical/column threads per horizontal thread
npart                   = 0
numnodes                = 0
se_ne_x                 = 0             ! element resolution factor in x-dir for planar
se_ne_y                 = 0             ! element resolution factor in y-dir for planar
integration             = "explicit"    ! integration method
transport_alg           = 0      ! SE Eulerianclassical SLcell-integrated SL
semi_lagrange_cdr_alg   = 0
semi_lagrange_cdr_check = .false.
semi_lagrange_hv_q      = 0
semi_lagrange_nearest_point_lev = 0
cubed_sphere_map        = 0
prescribed_wind         = 0
tom_sponge_start        = 0
dcmip16_mu              = 0
dcmip16_mu_s            = 0
dcmip16_mu_q            = 0
dcmip16_prec_type       = 0
dcmip16_pbl_type        = 0
smooth_phis_numcycle    = 0
smooth_phis_p2filt      = 0
smooth_phis_nudt        = 0
initial_total_mass      = 0
vtheta_thresh           = 0
pgrad_correction        = 0
hv_ref_profiles         = 0
hv_theta_correction     = 0
hv_theta_thresh         = 0
vert_remap_u_alg        = 0
/
