# MAKEFILE written by Christoph Erath
# number of processors
NPROC     = 3
# NP has to be at least >=2
NP        = 4
# NC has to be at >=4
NC        = 4
PLEV      = 4
EXECUTE   = fvm
# EXECUTE   =  sweqx
# EXECUTE     = primdgx
INPUT     = fvm.nl
# INPUT     = baro.nl
# INPUT     = cs-swtc5-ne5.nl 
HNAME     = $(shell hostname -s)
ARCH      = $(shell uname -s)
ADIR      = $(shell pwd)
all:
	@echo "********** Running HOMME-$(EXECUTE) on $(HNAME): Operating system $(ARCH) **********"
	@echo
	@echo "*** BUILD $(EXECUTE) in build/" 
	cd ../../build/$(EXECUTE)/ && make -j 4
	
run: 
	cp $(INPUT) input.nl
	@echo "*** COPY $(EXECUTE) TO $(ADIR)"
	cp ../../build/$(EXECUTE)/$(EXECUTE) .
	@echo
	@echo " ************* RUN $(EXECUTE) with the command mpirun: -np $(NPROC) ./$(EXECUTE) **********"
	@echo " ********************************--->"
	@echo
	mpirun -np $(NPROC) ./$(EXECUTE) < input.nl
#	rm ./mesh/allmesh.dat && cat mesh/mesh*.dat |sort >> ./mesh/allmesh.dat
#	rm mesh/mesh*.dat
#	scp ./mesh/allmesh.dat tram:matlab/

cleansource:
	@echo "*** Clean Source from $(EXECUTE) in build/$(EXECUTE)" 
	cd ../../build/$(EXECUTE)/ && make clean
	cd $(ADIR)

depends:
	@echo "*** RENEW DEPENDENCIES in Source from $(EXECUTE) in build/$(EXECUTE)"
	cd ../../build/$(EXECUTE)/ && make clean-depends && make depends
	cd $(ADIR)
	@echo "*** DONE: RENEW DEPENDENCIES in Source from $(EXECUTE) in build/$(EXECUTE)"

clean:
	rm -rf *.error *.output *.errors *~ fort.* swtc*.* core.* sweq.*

tclean:	
	rm -rf *.txt mpi_profile.* events.trc

pclean:
	rm -rf corun.* vnrun.* debug.*

dclean:
	rm -rf ./data/*.out ./movies/*.nc

clear: tclean clean dclean

comp:
	@echo "**** Running everything for HOMME-$(EXECUTE) on $(HNAME): Operating system $(ARCH) ******"
	cd ../../build/$(EXECUTE)/ && autoheader && aclocal && autoconf && automake && ./configure NC=$(NC) NP=$(NP) PLEV=$(PLEV) --enable-blas --enable-lapack --enable-pio --enable-fvm --with-arch=Darwin --with-pnetcdf=$(PNETCDF_PATH) --with-netcdf=$(NETCDF_PATH) && make clean-depends  && make depends  
	make cleansource
	make  
