# CMake initial cache file for Sandia's redsky
SET (CMAKE_Fortran_COMPILER mpif90 CACHE FILEPATH "")
SET (CMAKE_C_COMPILER mpicc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER mpicc CACHE FILEPATH "")
SET (ADD_Fortran_FLAGS "-traceback" CACHE STRING "")
SET (ENABLE_OPENMP TRUE CACHE BOOL "")
SET (NETCDF_DIR $ENV{NETCDF_PATH} CACHE FILEPATH "")
SET (PNETCDF_DIR $ENV{PNETCDF_PATH} CACHE FILEPATH "")
SET (USE_QUEUING FALSE CACHE BOOL "")
SET (HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")

