mpi_abort.o:
mpi_comm_dup.o: m_mpi0.o
mpi_comm_free.o: m_mpi0.o
mpi_comm_rank.o: m_mpi0.o
mpi_comm_size.o: m_mpi0.o
mpi_error_string.o:
mpi_finalize.o: m_mpi0.o Const_MPItype.H
mpi_init.o: m_mpi0.o Const_MPItype.H
mpi_initialized.o: m_mpi0.o
mpi_wtick.o:
mpi_wtime.o:
mpi_barrier.o: m_mpi0.o
mpi_bcast.o: m_mpi0.o
mpi_gather.o: m_mpi0.o
m_mpi0.o:
mpi0_copy.o: m_mpi0.o
Const_MPItype.H:
