#! /bin/csh -f

source ./Tools/ccsm_getenv || exit -2

rm -r -f $EXEROOT/*/obj        >& /dev/null
rm -r -f $EXEROOT/*/source     >& /dev/null
rm -r -f $EXEROOT/csm_share    >& /dev/null
rm -r -f $EXEROOT/mct          >& /dev/null
rm -r -f $EXEROOT/pio          >& /dev/null
rm -r -f $EXEROOT/*/obj        >& /dev/null
rm -r -f $EXEROOT/*/source     >& /dev/null
rm -r -f $EXEROOT/csm_share    >& /dev/null
rm -r -f $EXEROOT/mct          >& /dev/null
rm -r -f $EXEROOT/pio          >& /dev/null
rm -r -f $LIBROOT              >& /dev/null
rm    -f $EXEROOT/cesm.exe     >& /dev/null
rm    -f $EXEROOT/config.cache >& /dev/null

rm -f LockedFiles/env_build*  >& /dev/null

./xmlchange -file env_build.xml -id SMP_BUILD -val 0
./xmlchange -file env_build.xml -id NINST_BUILD -val 0
./xmlchange -file env_build.xml -id BUILD_COMPLETE -val FALSE
./xmlchange -file env_build.xml -id BUILD_STATUS -val 0

echo "CESM $CASE clean_build FINISHED SUCCESSFULLY"

exit 0

