#include "dtypes.h"
!===================================================
! DO NOT EDIT THIS FILE, it was generated using /home/santos/Utilities/genf90.pl
! Any changes you make to this file may be lost
! Jinyun Tang cleared up to cunstomize it for sbetr
!===================================================
module bshr_assert_mod

! Assert subroutines for common debugging operations.

use bshr_kind_mod, only: &
     r4 => shr_kind_r4,  &
     r8 => shr_kind_r8,  &
     i4 => shr_kind_i4,  &
     i8 => shr_kind_i8
use BetrStatusType, only : betr_status_type
use bshr_sys_mod, only: &
     shr_sys_abort

use bshr_log_mod, only: &
     shr_log_Unit

use bshr_infnan_mod, only: shr_infnan_isnan

implicit none
private
  character(len=*), private, parameter :: mod_filename = &
       __FILE__
save

! Assert that a logical is true.
public :: shr_assert
public :: shr_assert_all
public :: shr_assert_any


interface shr_assert_all
   module procedure shr_assert
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_all_1d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_all_2d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_all_3d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_all_4d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_all_5d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_all_6d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_all_7d
end interface


interface shr_assert_any
   module procedure shr_assert
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_any_1d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_any_2d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_any_3d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_any_4d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_any_5d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_any_6d
   ! DIMS 1,2,3,4,5,6,7
   module procedure shr_assert_any_7d
end interface


! Private utilities.


contains


subroutine shr_assert(var, msg, bstatus)

  type(betr_status_type), intent(out) :: bstatus
  ! Logical being asserted.
  logical, intent(in) :: var
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg

  call bstatus%reset()
  if (.not. var) call bstatus%set_msg(msg,err=-1)

end subroutine shr_assert

! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_all_1d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(all(var), msg, bstatus)

end subroutine shr_assert_all_1d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_all_2d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(all(var), msg, bstatus)

end subroutine shr_assert_all_2d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_all_3d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(all(var), msg, bstatus)

end subroutine shr_assert_all_3d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_all_4d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:,:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(all(var), msg, bstatus)

end subroutine shr_assert_all_4d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_all_5d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:,:,:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(all(var), msg, bstatus)

end subroutine shr_assert_all_5d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_all_6d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:,:,:,:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(all(var), msg, bstatus)

end subroutine shr_assert_all_6d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_all_7d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:,:,:,:,:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(all(var), msg, bstatus)

end subroutine shr_assert_all_7d

! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_any_1d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(any(var), msg, bstatus)

end subroutine shr_assert_any_1d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_any_2d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(any(var), msg, bstatus)

end subroutine shr_assert_any_2d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_any_3d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(any(var), msg, bstatus)

end subroutine shr_assert_any_3d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_any_4d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:,:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(any(var), msg, bstatus)

end subroutine shr_assert_any_4d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_any_5d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:,:,:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(any(var), msg, bstatus)

end subroutine shr_assert_any_5d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_any_6d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:,:,:,:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(any(var), msg, bstatus)

end subroutine shr_assert_any_6d
! DIMS 1,2,3,4,5,6,7

subroutine shr_assert_any_7d(var, msg, bstatus)

  ! Logical being asserted.
  logical, intent(in) :: var(:,:,:,:,:,:,:)
  ! Optional error message if assert fails.
  character(len=*), intent(in) :: msg
  type(betr_status_type), intent(out) :: bstatus

  call shr_assert(any(var), msg, bstatus)

end subroutine shr_assert_any_7d



end module bshr_assert_mod
