name: CI/CD Build Workflow

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  CANCEL_OTHERS: true
  PATHS_IGNORE: '["**/README.md", "**/docs/**", "**/examples/**", "**/misc/**", "**/.vscode/**", "**/.github/pull_request_template.md", "**/.github/ISSUE_TEMPLATE"]'

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: ${{ env.CANCEL_OTHERS }}
          paths_ignore: ${{ env.PATHS_IGNORE }}

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Checkout Code Repository
        uses: actions/checkout@v3

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        # Run all pre-commit hooks on all the files.
        # Getting only staged files can be tricky in case a new PR is opened
        # since the action is run on a branch in detached head state
        name: Install and Run Pre-commit
        uses: pre-commit/action@v3.0.0

  build:
    name: Build (Python ${{ matrix.python-version }})
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: ${{ env.CANCEL_OTHERS }}
          paths_ignore: ${{ env.PATHS_IGNORE }}

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        uses: actions/checkout@v3

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Cache Conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if conda-env/ci.yml has not changed in the workflow
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-${{ matrix.python-version }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-env/ci.yml') }}

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "e3sm_diags_ci"
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          mamba-version: "*"
          environment-file: conda-env/ci.yml
          channel-priority: strict
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Install e3sm_diags
        run: |
          python -m pip install .

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Check conda env
        run: |
          mamba list
          mamba info

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Run Tests
        env:
          CHECK_IMAGES: False
        run: bash tests/test.sh

  publish-docs:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache Conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if conda-env/ci.yml has not changed in the workflow
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-env/ci.yml') }}

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "e3sm_diags_ci"
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          mamba-version: "*"
          environment-file: conda-env/ci.yml
          channel-priority: strict
          auto-update-conda: true

      - name: Build Sphinx Docs
        run: |
          cd docs
          sphinx-multiversion source _build/html

      - name: Copy Docs and Commit
        run: |
          # gh-pages branch must already exist
          git clone https://github.com/E3SM-Project/e3sm_diags.git --branch gh-pages --single-branch gh-pages

          # Make sure we're in the gh-pages directory.
          cd gh-pages

          # Create `.nojekyll` (if it doesn't already exist) for proper GH Pages configuration.
          touch .nojekyll

          # Add `index.html` to point to the `main` branch automatically.
          printf '<meta http-equiv="refresh" content="0; url=./_build/html/main/index.html" />' > index.html

          # Only replace `main` docs with latest changes. Docs for tags should be untouched.
          rm -rf _build/html/main
          mkdir -p _build/html/main
          cp -r ../docs/_build/html/main _build/html

          # Configure git using GitHub Actions credentials.
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # The below command will fail if no changes were present, so we ignore it
          git add .
          git commit -m "Update documentation" -a || true

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
