name: eamxx-v1

on:
  # Runs on PRs against master
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, ready_for_review, reopened]
    paths:
      # first, yes to these
      - '.github/workflows/eamxx-v1-testing.yml'
      - 'cime_config/machine/config_machines.xml'
      - 'components/eamxx/**'
      - 'components/homme/**'
      - 'components/eam/src/physics/rrtmgp/**'
      - 'externals/ekat'
      - 'externals/mam4xx'
      - 'externals/haero'
      - 'externals/scorpio'
      # second, no to these
      - '!components/eamxx/docs/**'
      - '!components/eamxx/mkdocs.yml'

  # Manual run is used to bless
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Job to run'
        required: true
        type: choice
        options:
          - cpu-gcc
          - all
      bless:
        description: 'Generate baselines'
        required: true
        type: boolean

concurrency:
  # Two runs are in the same group if they are testing the same git ref
  #  - if trigger=pull_request, the ref is refs/pull/<PR_NUMBER>/merge
  #  - for other triggers, the ref is the branch tested
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Submit to cdash only for nightlies or if the user explicitly forced a submission via workflow dispatch
  submit: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch') }}
  # Generate only if user requested via workflow_dispatch
  generate: ${{ github.event_name == 'workflow_dispatch' && inputs.bless }}
  # Correct case folder suffix for this test (includes sha and compare/generate suffix), used to find files to upload as artifacts
  compgen_suffix: ${{ github.event_name == 'workflow_dispatch' && inputs.bless && '.G.' || '.C.' }}
  # Compare/generate flags for create_test
  flags: ${{ github.event_name == 'workflow_dispatch' && inputs.bless && '-o -g -b master' || '-c -b master' }}

jobs:
  cpu-gcc:
    if: |
      ${{
        github.event_name != 'workflow_dispatch' ||
        (
          github.event.inputs.job_to_run == 'cpu-gcc' || 
          github.event.inputs.job_to_run == 'all'
        )
      }}
    runs-on:  [self-hosted, gcc, ghci-snl-cpu]
    strategy:
      matrix:
        test:
          - full_name: ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.ghci-snl-cpu_gnu.eamxx-output-preset-2
            short_name: ERS.ne4np4.F2000-SCREAMv1-AQP.output-preset-2
            id: 1
          - full_name: ERS_P16_Ln22.ne30pg2_ne30pg2.FIOP-SCREAMv1-DP.ghci-snl-cpu_gnu.eamxx-dpxx-arm97
            short_name: ERS.ne30pg2.FIOP-SCREAMv1-DP.dpxx-arm97
            id: 2
          - full_name: ERS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.ghci-snl-cpu_gnu.eamxx-small_kernels--eamxx-output-preset-5
            short_name: ERS.ne4pg2.F2010-SCREAMv1.small-kernels--output-preset-5
            id: 3
          - full_name: REP_D_Ln5.ne4pg2_oQU480.F2010-EAMxx-MAM4xx.ghci-snl-cpu_gnu
            short_name: REP.ne4pg2.F2010-EAMxx-MAM4xx
            id: 4
          - full_name: ERS.ne4pg2_ne4pg2.F2010-SCREAMv1.ghci-snl-cpu_gnu.eamxx-prod
            short_name: ERS.ne4pg2.F2010-SCREAMv1.prod
            id: 5
      fail-fast: false
    name: cpu-gcc / ${{ matrix.test.short_name }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
          submodules: recursive
      - name: Show action trigger
        uses: ./.github/actions/show-workflow-trigger
      - name: Set CA certificates env var
        run: |
          # Ensure the operating system is Linux
          if [ "$(uname)" != "Linux" ]; then
            echo "This action only supports Linux."
            exit 1
          fi
          # Set env var to be used in upload-artifacts phase
          if [ -f /etc/debian_version ]; then
            echo "NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt" >> $GITHUB_ENV
          elif [ -f /etc/redhat-release ] || [ -f /etc/centos-release ] || [ -f /etc/fedora-release ]; then
            echo "NODE_EXTRA_CA_CERTS=/etc/pki/tls/certs/ca-bundle.crt" >> $GITHUB_ENV
          else
            echo "Unsupported Linux distribution"
            exit 1
          fi
      - name: Set test id
        run: |
          GITHUB_SHA=${{ github.sha }}
          SHORT_SHA=${GITHUB_SHA::7}
          TESTID=$SHORT_SHA-${{ matrix.test.id }}-$(date -u +"%y%m%d-%H%M%S")
          echo "testid=$TESTID" >> $GITHUB_ENV
      - name: Run test
        id: run-tests
        run: |
          ./cime/scripts/create_test ${{ matrix.test.full_name }} ${{ env.flags }} -t ${{ env.testid }} --wait
      - name: Upload log files
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: logs.${{ matrix.test.short_name }}
          path: |
            /projects/e3sm/scratch/${{ matrix.test.full_name }}${{ env.compgen_suffix }}${{ env.testid }}/TestStatus
            /projects/e3sm/scratch/${{ matrix.test.full_name }}${{ env.compgen_suffix }}${{ env.testid }}/TestStatus.log
            /projects/e3sm/scratch/${{ matrix.test.full_name }}${{ env.compgen_suffix }}${{ env.testid }}/bld/**/*.bldlog.*
            /projects/e3sm/scratch/${{ matrix.test.full_name }}${{ env.compgen_suffix }}${{ env.testid }}/run/**/*.log.*
            /projects/e3sm/scratch/${{ matrix.test.full_name }}${{ env.compgen_suffix }}${{ env.testid }}/run/**/*.cprnc.out
          retention-days: 14
        env:
          NODE_EXTRA_CA_CERTS: ${{ env.NODE_EXTRA_CA_CERTS }}
      - name: Upload nc files
        if: ${{ failure() && steps.run-tests.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: outputs.${{ matrix.test.short_name }}
          path: |
            /projects/e3sm/scratch/${{ matrix.test.full_name }}${{ env.compgen_suffix }}${{ env.testid }}/run/**/*.nc*
          retention-days: 14
        env:
          NODE_EXTRA_CA_CERTS: ${{ env.NODE_EXTRA_CA_CERTS }}
      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -rf /projects/e3sm/scratch/${{ matrix.test.full_name }}${{ env.compgen_suffix }}${{ env.testid }}
          rm -f /projects/e3sm/scratch/cs.status.${{ env.testid }}
