name: Publish to Anaconda

on:
  release:
    types: [published]

jobs:
  publish-to-anaconda:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Cache Conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if conda/e3sm_diags_env_dev.yml has not changed in the workflow
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-publish

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "e3sm_diags_publishing"
          channel-priority: strict
          python-version: 3.7
          auto-update-conda: true
          # IMPORTANT: This needs to be set for caching to work properly!
          use-only-tar-bz2: true

      - name: Additional Conda Config
        run: |
          conda install anaconda-client conda-build conda-verify
          conda config --set anaconda_upload no

      - name: Build Conda Package
        run: conda build -c conda-forge --output-folder . .

      - name: Publish to Anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: anaconda upload --label main noarch/*.tar.bz2 --force
