name: CI/CD Workflow

on:
  push:
    branches: [master]
    paths-ignore: ["docs/**"]

  pull_request:
    branches: [master]
    paths-ignore: ["docs/**"]

env:
  UVCDAT_ANONYMOUS_LOG: False

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Run all pre-commit hooks on all the files.
      # Getting only staged files can be tricky in case a new PR is opened
      # since the action is run on a branch in detached head state
      - name: Install and Run Pre-commit
        uses: pre-commit/action@v2.0.0

  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Cache Conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if conda/e3sm_diags_env_dev.yml has not changed in the workflow
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda/e3sm_diags_env_dev.yml') }}

      - name: Build Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: e3sm_diags_env_dev
          environment-file: conda/e3sm_diags_env_dev.yml
          channel-priority: strict
          python-version: 3.7
          auto-update-conda: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Show Conda Environment Info
        run: |
          conda config --set anaconda_upload no
          conda info
          conda list

      - name: Install `e3sm-diags` Package
        run: pip install .

      - name: Run Tests
        run: |
          bash tests/test.sh

  publish:
    if: ${{ github.ref == 'master' && github.event.action != 'pull_request'}}
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Cache Conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-publish

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "e3sm_diags"
          channel-priority: strict
          python-version: 3.7
          auto-update-conda: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Additional Conda Config
        run: |
          conda install anaconda-client conda-build conda-verify
          conda config --set anaconda_upload no

      - name: Build Conda Package
        run: conda build -c conda-forge --output-folder . .

      - name: Publish to Anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: anaconda upload --label main noarch/*.tar.bz2 --force
