#! /usr/bin/env perl
use strict;

if ($#ARGV == -1) {
    die " ERROR eam buildlib: must specify a caseroot input argument";
}
my ($CASEROOT) = @ARGV;
chdir "${CASEROOT}";

my $CASEBUILD = `./xmlquery CASEBUILD -value`;
my $CASETOOLS = `./xmlquery CASETOOLS -value`;
my $OBJROOT   = `./xmlquery OBJROOT   -value`;
my $LIBROOT   = `./xmlquery LIBROOT   -value`;
my $GMAKE_J   = `./xmlquery GMAKE_J   -value`;
my $GMAKE     = `./xmlquery GMAKE     -value`;
my $MAKE_ARGS = `./Tools/get_standard_makefile_args`;
chomp($MAKE_ARGS);

chdir "${OBJROOT}/atm/obj";

if (-f "$CASEBUILD/eamconf/Filepath") {
    my $sysmod = "cp ${CASEBUILD}/eamconf/Filepath ./tmp_filepath"; 
    system($sysmod) == 0 or die "ERROR eam buildlib: $sysmod failed: $?\n";
} else {
    die "ERROR eam buildlib  - missing $CASEBUILD/eamconf/Filepath";
}

if (-f "Filepath") {
    my $sysmod = "cmp -s tmp_filepath Filepath || mv -f tmp_filepath Filepath ";
    system($sysmod) == 0 or die "ERROR eam buildlib: $sysmod failed: $?\n";
} else {
    my $sysmod = "mv -f tmp_filepath Filepath ";
    system($sysmod) == 0 or die "ERROR eam buildlib: $sysmod failed: $?\n";
}

my $camdefs = `cat $CASEBUILD/eamconf/CCSM_cppdefs`;
#my $camdefs = `cat $CASEBUILD/eamconf/CIME_cppdefs`;
chomp($camdefs);
my $sysmod = "$GMAKE complib -j ${GMAKE_J} MODEL=eam COMPLIB=${LIBROOT}/libatm.a USER_CPPDEFS=\"${camdefs}\" -f ${CASETOOLS}/Makefile ${MAKE_ARGS}";
system($sysmod) == 0 or die "ERROR: eam buildlib $sysmod failed: $?\n";

exit(0);
